### ISSUE TITLE
Ignored triggers are included in permittedTriggers

### ISSUE THREAD

**Issue by beyon** [dotnet-state-machine/stateless#1]
Re-posting on GitHub since I noticed project has moved:

What steps will reproduce the problem?
1. Create a Statemachine with substates
2. In a substate Ignore a trigger allowed in it's Superstate
3. Transition your state machine to above substate
4. Examine yourStateMachine.ToString()

The ignored trigger will be listed among the Permitted triggers even though the trigger won't be allowed by yourStateMachine.CanFire(substate)

Cause seem to be the union with the superstates permittedTriggers:

```
        public IEnumerable<TTrigger> PermittedTriggers
        {
            get
            {
                var result = _triggerBehaviours
                    .Where(t => t.Value.Any(a => a.IsGuardConditionMet))
                    .Select(t => t.Key);

                if (Superstate != null)
                    result = result.Union(Superstate.PermittedTriggers);

                return result.ToArray();
            }
        }
```

**Comment by Maximusya** [comment]
It's not just about substate-superstate: plain old StateMachine with Ignored trigger configured still lists the trigger as Permitted.

Take TelephoneCallExample
https://github.com/dotnet-state-machine/stateless/blob/master/TelephoneCallExample/Program.cs

```csharp
phoneCall.Configure(State.Connected)
	.OnEntry(t => StartCallTimer())
	.OnExit(t => StopCallTimer())
		.Permit(Trigger.LeftMessage, State.OffHook)
		.Permit(Trigger.HungUp, State.OffHook)
		.Permit(Trigger.PlacedOnHold, State.OnHold);
```

If you add `.Ignore(Trigger.CallDialed)` and "lure" the SM into State.Connected, it will output

> [Status:] StateMachine { State = Connected, PermittedTriggers = { LeftMessage, HungUp, PlacedOnHold, CallDialed }}

It is just that Ignored trigger is internally added with a TriggerBehavior with NoGuard (true returning Func) - and there is no distinction between different implementations of TriggerBehavior in the PermittedTriggers getter you posted above.

Should PermittedTriggers return only those added via Permit? Then it is a bug.
Should PermittedTriggers be interpreted as a list of triggers not causing UnhandledTriggerAction? Then the behavior is correct - it is the naming that should be fixed.

**Comment by nblumhardt** [comment]
@Maximusya I think it's the latter - the behaviour is intended, but the name should probably be more like "triggers that can validly be fired".

What the trigger does (whether it is ignored, or causes a transition) is encapsulated in the statemachine to some extent, so distinguishing between "permitted and causes a transition" and just "ignored" doesn't seem necessary here.

The question probably needs to be framed now as, is the issue enough of a problem to warrant an API change? Or, could we just improve the documentation of `PermittedTriggers` and call it a day?

Thanks!
Nick

**Comment by HenningNT** [comment]
I thought that the point of the .Ignore(trigger) would actually tell the state machine to not act on that particular trigger. As it is now the state machine ends up in the default state when the trigger is fired. This is not documented in the XML comment which says: Ignore the specified trigger when in the configured state.

I would like the .Ignore to cause an internal transition, without any trigger handlers being executed.
I've already started on adding internal transitions, maybe we could have .Ignore just add an internal transition?

**Comment by nblumhardt** [comment]
@HenningNT ah, right - I may have misread that one, `Ignore()` should absolutely ignore the trigger, no transition at all should happen...

**Comment by Maximusya** [comment]
> As it is now the state machine ends up in the default state when the trigger is fired

_IgnoredTriggerBehavior_:
```csharp
public override bool ResultsInTransitionFrom(TState source, object[] args, out TState destination)
{
    destination = default(TState);
    **return false**;
}
```

_StateMachine.InternalFire_:
```csharp
void InternalFire(TTrigger trigger, params object[] args)
{
    TriggerWithParameters configuration;
    if (_triggerConfiguration.TryGetValue(trigger, out configuration))
        configuration.ValidateParameters(args);

    var source = State;
    var representativeState = GetRepresentation(source);

    TriggerBehaviour triggerBehaviour;
    if (!representativeState.TryFindHandler(trigger, out triggerBehaviour))
    {
        _unhandledTriggerAction(representativeState.UnderlyingState, trigger);
        return;
    }

    TState destination;
    if (triggerBehaviour.ResultsInTransitionFrom(source, args, out destination))
    {
        var transition = new Transition(source, destination, trigger);

        representativeState.Exit(transition);

        State = transition.Destination;
        var newRepresentation = GetRepresentation(transition.Destination);
        var onTransitioned = _onTransitioned;
        if (onTransitioned != null)
            onTransitioned(transition);

        newRepresentation.Enter(transition, args);
    }
}
```

SM does not change state to default - the trigger is ignored in the common sense of the word "ignore" :).

**Comment by HenningNT** [comment]
Hm, I think I have to update my sources, my files might be out of date...
Disregard my previous comment until further notice ;-)
