### ISSUE TITLE
Request: Add NETFX35 Target to compilation and nuget package

### ISSUE THREAD

**Issue by podostro** [dotnet-state-machine/stateless#101]
I'm working on a unity game project and it's also has .net backend. 
I wanted to use stateless to take care of my state machine needs in both the front and back ends with the same code (shared assembly).

But I can't use it because there's no 3.5 target 
(As you may know, Unity is not compatible with 4.0+/Core assemblies; and only partly 3.5)

I have dowloaded and re configured the stateless vs project to compile for NETFX35 so I can now use it.
Only had to change two lines of code in DotGraph.cs where passing a List<string> to String.Join, to call .ToArray() explicitly.

But it would be great if the official package had this compatibility by default.

**Comment by nblumhardt** [comment]
Hi @podostro - thanks for the note. I had a look at this, there's still a bit more work to do `#if`-ing out various uses of `Task` before a clean .NET 3.5 build is possible.

Stateless version 2.3 supports .NET 3.5:

https://www.nuget.org/packages/Stateless/2.3.1.1

Are you able to try out this version (`Install-Package Stateless -Version 2.3.1.1`) and see whether it suits your needs?

Cheers!

**Comment by podostro** [comment]
Hi @nblumhardt, thanks for the answer.
I've not downloaded the latest version of stateless yet. v2.5.84 did only need those two lines :+1: 

Unfortunately I don't have the time right now to try if an older version complies with my needs; I will keep my modified version for the moment and when I have the time to review this I will try it.

Thanks again!!

**Comment by nblumhardt** [comment]
:+1: thanks for the follow-up. Cheers!
