### ISSUE TITLE
How to persistence the graph status?

### ISSUE THREAD

**Issue by biapar** [dotnet-state-machine/stateless#104]
How to persistence the graph status?

**Comment by HenningNT** [comment]
Do mean " how to store the state to disk " ?

**Comment by biapar** [comment]
Yes

**Comment by HenningNT** [comment]
I would say that there are several options.
One option is to create a text file containing the information needed to restore an object.
I tried to do this with the Bug example, so I added to methods ToJson and From Json to the Bug class.

The Bug class has only tree items that is needed, the title, the name of the assigned, and finally the state of the bug. I also added a struct to have somewhere to store this information. I use the new method to create a string that can be written to disk, and the static method to create a new object from a string (read from disk). I added a private constructor to be used by the FromJson method.

Disclaimer: This is my first ever attempt at doing anything with json, so you should propably get a second opinion ;-)


	using System;
	using Stateless;
	using Newtonsoft.Json;

	namespace BugTrackerExample
	{
		public class Bug
		{
			enum State { Open, Assigned, Deferred, Resolved, Closed }
			enum Trigger { Assign, Defer, Resolve, Close }

			State _state = State.Open;
			StateMachine<State, Trigger> _machine;
			StateMachine<State, Trigger>.TriggerWithParameters<string> _assignTrigger;

			string _title;
			string _assignee;

			public Bug(string title)
			{
				_title = title;

				ConfigureStateMachine();
			}
			private Bug(BugStorage bugInfo)
			{
				_title = bugInfo.Title;
				_assignee = bugInfo.Assignee;
				_state = (State)Enum.Parse(typeof(State), bugInfo.State);

				ConfigureStateMachine();
			}

			private void ConfigureStateMachine()
			{
				_machine = new StateMachine<State, Trigger>(() => _state, s => _state = s);

				_assignTrigger = _machine.SetTriggerParameters<string>(Trigger.Assign);

				_machine.Configure(State.Open)
					.Permit(Trigger.Assign, State.Assigned);

				_machine.Configure(State.Assigned)
					.SubstateOf(State.Open)
					.OnEntryFrom(_assignTrigger, assignee => OnAssigned(assignee))
					.PermitReentry(Trigger.Assign)
					.Permit(Trigger.Close, State.Closed)
					.Permit(Trigger.Defer, State.Deferred)
					.OnExit(() => OnDeassigned());

				_machine.Configure(State.Deferred)
					.OnEntry(() => _assignee = null)
					.Permit(Trigger.Assign, State.Assigned);
			}

			public void Close()
			{
				_machine.Fire(Trigger.Close);
			}

			public void Assign(string assignee)
			{
				_machine.Fire(_assignTrigger, assignee);
			}

			public bool CanAssign
			{
				get
				{
					return _machine.CanFire(Trigger.Assign);
				}
			}

			public void Defer()
			{
				_machine.Fire(Trigger.Defer);
			}

			void OnAssigned(string assignee)
			{
				if (_assignee != null && assignee != _assignee)
					SendEmailToAssignee("Don't forget to help the new guy.");

				_assignee = assignee;
				SendEmailToAssignee("You own it.");
			}

			void OnDeassigned()
			{
				SendEmailToAssignee("You're off the hook.");
			}

			void SendEmailToAssignee(string message)
			{
				Console.WriteLine("{0}, RE {1}: {2}", _assignee, _title, message);
			}

			public string ToJson()
			{
				var store = new BugStorage() { Assignee = _assignee, Title = _title, State = _machine.State.ToString() };
				return JsonConvert.SerializeObject(store);
			}
			public static Bug FromJson(string jsostring)
			{
				var bugInfo = JsonConvert.DeserializeObject<BugStorage>(jsostring);
				return new Bug(bugInfo);
			}
		}
		struct BugStorage
		{
			public string State;
			public string Title;
			public string Assignee;
		}
	}

**Comment by orthros** [comment]
I too am a relative novice with JSON, but your solution definitely passes from my perspective. 

A question though: do you think there could be a built-in function to serialize/deserialize the actual machine so we do not need to configure it again? I know this is probably more difficult than it sounds (hooking up method calls etc), but I can see a need for it if you are deserializing an "older" version of your machine and need it to maintain that behavior (assuming the necessary methods are present)

If this is best suited for another issue, I'll open a new one

**Comment by nblumhardt** [comment]
@orthros serializing/deserializing the machine itself isn't possible given Stateless's feature set today. Usually it's not necessary though - just re-creating the machine wires everything up, and since the state is stored externally there's no "work-in-progress"-type information to worry about.

**Comment by biapar** [comment]
@orthros The problem is if the server goes down or similar your lost your status. So you can save the status ( ToJson ) for the single step and restart from there.
The graph is rebuilded when you restart the program.
