### ISSUE TITLE
No "runtimes" section in examples project.json files

### ISSUE THREAD

**Issue by HenningNT** [dotnet-state-machine/stateless#105]
The examples should be runnable and they all have a Program.cs file. I guess the runtimes section hasn't been added yet.

I wouldn't mind doing a little PR on this, but I don't really know what runtimes to add.
This page lists all sorts of runtimes supported by dotnet, I tried adding 'any' and 'base' to project.json but it didn't work.

I tried adding this, which does work on my win10 machine:

	  "runtimes": { 
			"win": { },
			"osx": { },
			"linux": { }
	}

**Comment by TerribleDev** [comment]
you shouldn't have to add runtimes unless the app is being packaged as a [self contained app](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/) where the dotnet runtime is literally bundled in with the app.

**Comment by HenningNT** [comment]
If there isn't a "runtimes" section in the project.json file I get this error when compiling:
``
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : 1. The project has not been restored or restore failed - run `dotnet restore`
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : 2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
``

Something isn't right...

**Comment by HenningNT** [comment]
So what's the verdict on this?
Should the examples be runnable, and do we need the runtimes section in the project.json for each example?

**Comment by nblumhardt** [comment]
Hi @HenningNT  - I just opened the solution, set _BugTrackerExample_ as the startup project and hit F5 - all runs as expected. If you're hitting a roadblock, I don't think there would be any harm in adding the runtimes section though if you need to (no time to dig in further personally right now).

**Comment by HenningNT** [comment]
Sounds like the problem is at my end...
