### ISSUE TITLE
Consider using Interlocked when firing events

### ISSUE THREAD

**Issue by paulomorgado** [dotnet-state-machine/stateless#108]
I concurrent access occurs to `StateMachine.FireInternal`, a simple Boolean won't guarantee exclusive access because the `_firing` might already been evaluated and not yet changed in one thread while another is evaluating it.

Consider using something like this:

    int _firing;

    ...

    /// <summary>
    /// Queue events and then fire in order.
    /// If only one event is queued, this behaves identically to the non-queued version.
    /// </summary>
    /// <param name="trigger">  The trigger. </param>
    /// <param name="args">     A variable-length parameters list containing arguments. </param>
    void InternalFire(TTrigger trigger, params object[] args)
    {
        if (Interlocked.CompareExchange(ref _firing, 1, 0) == 1)
        {
            _eventQueue.Enqueue(new QueuedTrigger { Trigger = trigger, Args = args });
            return;
        }

        try
        {
            InternalFireOne(trigger, args);

            while (_eventQueue.Count != 0)
            {
                var queuedEvent = _eventQueue.Dequeue();
                InternalFireOne(queuedEvent.Trigger, queuedEvent.Args);
            }
        }
        finally
        {
            Interlocked.Exchange(ref _firing, 0);
        }
    }

**Comment by nblumhardt** [comment]
Thanks for the note Paulo. Stateless is completely non-thread-safe - you need to protect the StateMachine with a lock/mutex if multiple threads need to access it.

**Comment by paulomorgado** [comment]
OK! So this is just for reentrancy, right?

**Comment by nblumhardt** [comment]
Hi @paulomorgado, thanks for the follow-up. I think reentrancy is already handled via the internal event queue - is there a scenario currently in which it breaks? Cheers!

**Comment by paulomorgado** [comment]
No. I just though it was to handle concurrency.

**Comment by nblumhardt** [comment]
Great, thanks for closing the loop.
