### ISSUE TITLE
Use trigger queue in FireAsync()

### ISSUE THREAD

**Issue by nblumhardt** [dotnet-state-machine/stateless#109]
The synchronous `Fire()` uses the internal trigger queue to ensure any triggers fired recursively are processed after the current handlers complete. The `FireAsync()` version does not implement this.

**Comment by HenningNT** [comment]
I don't know if this is a bug or not, but it got me thinking;  If we duplicate the InternalFireOne, but make everything awaitable, then do we not risk firing off several triggers more or less at once, and all of them can run in parallell and potentially posting more triggers to the queue? I haven't used await/async that much, but isn't the point that execution can continue while a time consuming task completes? If so, we are not executing triggers atomically and do not run to completion, causing state to be manipulated in several places. If my assumptions are correct ;-)

**Comment by nblumhardt** [comment]
Async state machines can already be called during the interleaving of an async call and its continuation, e.g. if there are async `OnEntry` actions (thus firing off multiple transitions concurrently - in error). This change would just make the behaviour of `Fire` consistent between the sync/async versions.

**Comment by nblumhardt** [comment]
Fixed in #140
