### ISSUE TITLE
Entry/Exit Exception Handling

### ISSUE THREAD

**Issue by sfalik** [dotnet-state-machine/stateless#110]
Should the state machine be allowed to enter a state if the OnEntry event fails with an unhandled exception?  At this point, the OnExit event has completed, and the state machine is in the new state even though the OnEntry event I defined threw an exception.  Consider the following simple example:

            var machine = new StateMachine<int, string>(0);

            machine.Configure(0)
                .OnExit(() => Console.WriteLine("Exiting State 0..."))
                .Permit("Trigger", 1);

            machine.Configure(1)
                .OnEntry(() => { throw new Exception("Doh"); });

            Console.WriteLine($"Machine is now in State:{machine.State}, firing trigger...");

            try
            {
                machine.Fire("Trigger");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }

            Console.WriteLine($"Machine is now in State:{machine.State}");

This produces the output:
![image](https://cloud.githubusercontent.com/assets/17600811/20731996/b601a144-b65a-11e6-98ac-382cbf2289d2.png)

Is this the intended behaviour?

**Comment by HenningNT** [comment]
Well, the OnEntry can't be executed unless the state machine has entered the state... so I would think that is the "correct" behaviour.

**Comment by nblumhardt** [comment]
I think arguments could be made either way, but the current behaviour hasn't been problematic so far.

@sfalik have you investigated `PermitIf` or `PermitDynamic` to cover your scenarios?

**Comment by sfalik** [comment]
thanks @nblumhardt , It sounds like this is 'working as designed', so I will rethink my error handling scenarios with the understanding that the state transition still happens even if the OnEntry action throws an exception (meaning the state transition happened but the OnEntry logic for the new state has not run successfully).  I can certainly use a Guard to try to prevent the transition if any anticipated conditions are not met -- but I will still need to deal with any exceptions that might be thrown.

**Comment by nblumhardt** [comment]
Thanks @sfalik - it will be interesting to hear how you go.

**Comment by clottman** [comment]
This is good info on how exceptions are handled - @nblumhardt perhaps the test scenario is something you might want to post on your blog for easier future discovery by others?

**Comment by nblumhardt** [comment]
@clottman thanks for the suggestion; perhaps we could add a brief description to the README?

**Comment by clottman** [comment]
Yeah I think that would work.
