### ISSUE TITLE
Multiple trigger parameters for same trigger fails

### ISSUE THREAD

**Issue by pardahlman** [dotnet-state-machine/stateless#111]
Awesome job with the lib! I've been playing around with it for a couple and weeks and it looks like it is going to make my life easier 👍 .

However, there is one limitation that I don't understand the reason for: why can't I declare multiple trigger parameter for the same trigger? Running this code (inspired of the phone example)

```csharp
var intTrigger = phoneCall.SetTriggerParameters<int>(Trigger.SetVolume);
var strTrigger = phoneCall.SetTriggerParameters<string>(Trigger.SetVolume);
```
Results in an `InvalidOperationException` ("Parameters for the trigger 'Stateless.StateMachine`2+TriggerWithParameters`1[TelephoneCallExample.Program+State,TelephoneCallExample.Program+Trigger,System.String]' have already been configured."). As a side note, the exception information is a bit of, as there is a trigger for `int`, not `string`.

I expected the code above not to throw, but to allow me to invoke different callbacks depending on which trigger parameter type I fired with

```csharp
phoneCall.Fire(intTrigger , 5);
phoneCall.Fire(strTrigger , "five");
```

**Comment by nblumhardt** [comment]
Closing as per discussion in #113.
