### ISSUE TITLE
PCL Target

### ISSUE THREAD

**Issue by fvaillancourt** [dotnet-state-machine/stateless#116]
Hi, we are working on a multi-platform project which use a lot of PCL projects. Also, as we are using a lot of async code, we would like to use version 3 of Stateless rather than 2.5.x. However it seems the PCL target was removed in version 3. We are aware that the world is moving away from PCL but it is not possible to switch all the code base in a day. Could you add the ".NETPortable,Version=4.5,Profile=Profile7" target or the same target that was supported by version 2.5.x to help ease the transition?
I tested it by adding only the target below in project.json and everything seemed to compile and work fine.
```
    ".NETPortable,Version=4.5,Profile=Profile7": {
      "buildOptions": {
        "define": [ "PORTABLE_REFLECTION", "TASKS" ]
      }
```

**Comment by nblumhardt** [comment]
Hi @fvaillancourt - thanks for getting in touch. I think we can do this (unless anyone else can see a downside?), would you be interested in submitting a PR? Thanks!

**Comment by fvaillancourt** [comment]
The -dev-00132 was successfully referenced by a PCL project, itself referenced by a Xamarin iOS app.

**Comment by nblumhardt** [comment]
Great, thank you.
