### ISSUE TITLE
Transition handled by SubState but not by SuperState for a trigger accepted in both

### ISSUE THREAD

**Issue by heltonbiker** [dotnet-state-machine/stateless#119]
I have the code below.

I want the method "Reset" to be executed in every state (thus the internal transition is defined in a global superstate), but _also_ when its trigger (ComandoColeta.Reset) is fired in the Paused state (EstadoColeta.Pausada).

The problem is: Reset() is in fact executed in every substate _except_ in the Paused state. It's as if the event is handled by the substate and "swallowed", that is, it doesn't "bubble" to the superstate.

#### The questions:

So is this the expected behavior?

How can I get the behavior I desire: having both SubState _and_ SuperState to handle the event - that is, both handlers will be executed - ?

``` csharp

_state_machine.Configure(EstadoColeta.Geral)
	.InternalTransition(ComandoColeta.Reset, (t) => Reset());

_state_machine.Configure(EstadoColeta.Parada)
	.SubstateOf(EstadoColeta.Geral)
	.OnEntry(Stop)
	.Permit(ComandoColeta.Play, EstadoColeta.Coletando);

_state_machine.Configure(EstadoColeta.Coletando)
	.SubstateOf(EstadoColeta.Geral)
	.OnEntry(Play)
	.Permit(ComandoColeta.Pause, EstadoColeta.Pausada)
	.Permit(ComandoColeta.Stop, EstadoColeta.Parada);

_state_machine.Configure(EstadoColeta.Pausada)
	.SubstateOf(EstadoColeta.Geral)
	.OnEntry(Pause)
	.Permit(ComandoColeta.Play, EstadoColeta.Coletando)
	.Permit(ComandoColeta.Stop, EstadoColeta.Parada)
	.Permit(ComandoColeta.Reset, EstadoColeta.Parada);

```

**Comment by HenningNT** [comment]
I'm afraid that is the expected behaviour.

Maybe you can add a SuperReset trigger, which posted by the reset trigger?

Or maybe handle the reset stuff in the entry action of parade?

**Comment by nblumhardt** [comment]
Another option:

```csharp
_state_machine.Configure(EstadoColeta.Pausada)
	.SubstateOf(EstadoColeta.Geral)
	.OnEntry(Pause)
        .OnExit(t => {
            if (t.Trigger == ComandoColeta.Reset) {
                Reset();
            }
        })
	.Permit(ComandoColeta.Play, EstadoColeta.Coletando)
	.Permit(ComandoColeta.Stop, EstadoColeta.Parada)
	.Permit(ComandoColeta.Reset, EstadoColeta.Parada);
```

**Comment by nblumhardt** [comment]
(`OnExitBy()`, which is a missing analogue of `OnEntryFrom()`, would cover this more cleanly.)

**Comment by heltonbiker** [comment]
@nblumhardt your first suggestion (which uses current API) is a bit dirty to my taste. I had done some similar stuff before posting here.

Your second suggestion seems quite interesting. I would call the method `OnExitTo()`, though.

Do you think the project would benefit from this method? Do you think it is easy and safe enough to implement it so that I can post its pull request myself?

**Comment by nblumhardt** [comment]
Thanks for the follow-up @heltonbiker; `OnEntryFrom()` is a bit misleading - it's not _from_ a particular state, but _from_ a trigger. Hence the asymmetric suggestion (I would go back and change the other method's name, given the chance, but too late for that I suppose).

Definitely up for a PR; I think all of the 8 overloads would still make sense but I'm not certain - would need to be investigated. Let me know if you need any help.

Cheers!
Nick

**Comment by HenningNT** [comment]
Could we add an overload to the Permit, so that it executes an action when doing the state change?

```.Permit(ComandoColeta.Reset, EstadoColeta.Parada, DoTheResetThing);```

Maybe something like this?
```public StateConfiguration Permit(TTrigger trigger, TState destinationState, Action action = null)```

And if we add the action to TriggerBehaviour class we can do something like this in InternalFireOne:

                if (triggerBehaviour.ResultsInTransitionFrom(source, args, out destination))
                {
                triggerBehaviour.executeTransitionAction();
                
                var transition = new Transition(source, destination, trigger);

I think that if we specify the transition and an associated action then it will be easier to read the state machine.

**Comment by heltonbiker** [comment]
Hi, Folks

I ended up achieving my desired behaviour by getting rid of the super state and adding another state. It's at the same time amazing and painful how many options you have to represent a given state machine behaviour with a given set of states and triggers, or also how subtle behavioral changes might imply an almost complete redesign of the state diagram...

Final result:

```csharp
_state_machine.Configure(EstadoColeta.Resetada)
	.OnEntry(Reset)
	.Permit(ComandoColeta.Play, EstadoColeta.Coletando);

_state_machine.Configure(EstadoColeta.Parada)
	.OnEntry(Stop)
	.Permit(ComandoColeta.Play, EstadoColeta.Coletando)
	.Permit(ComandoColeta.Reset, EstadoColeta.Resetada);

_state_machine.Configure(EstadoColeta.Coletando)
	.OnEntry(Play)
	.InternalTransition(ComandoColeta.Reset, (t) => Reset())  // only remaining occurrence of internal transition
	.Permit(ComandoColeta.Pause, EstadoColeta.Pausada)
	.Permit(ComandoColeta.Stop, EstadoColeta.Parada);

_state_machine.Configure(EstadoColeta.Pausada)
	.OnEntry(Pause)
	.Permit(ComandoColeta.Play, EstadoColeta.Coletando)
	.Permit(ComandoColeta.Stop, EstadoColeta.Parada)
	.Permit(ComandoColeta.Reset, EstadoColeta.Resetada);
```
