### ISSUE TITLE
Adding an Action to Permit

### ISSUE THREAD

**Issue by HenningNT** [dotnet-state-machine/stateless#128]
Would there be any interest in adding an Action to Permit (and all the conditionals)?
Something like `Permit(TTrigger trigger, TState destinationState, Action action = NullAction)`, maybe?
Together with InternalTransition it would make OnEntryFrom more or less redundant, but that's another matter. I'm used to transitions having associated actions, and I think it would be useful not just for me :-)

The Bug example could be written as:

        public Bug(string title)
        {
            _title = title;

            _machine = new StateMachine<State, Trigger>(() => _state, s => _state = s);

            _assignTrigger = _machine.SetTriggerParameters<string>(Trigger.Assign);

            _machine.Configure(State.Open)
                .Permit(Trigger.Assign, State.Assigned, assignee => OnAssigned(assignee));

            _machine.Configure(State.Assigned)
                .SubstateOf(State.Open)
                .InternalTransition(_assignTrigger, assignee => OnAssigned(assignee))
                .Permit(Trigger.Close, State.Closed)
                .Permit(Trigger.Defer, State.Deferred)
                .OnExit(() => OnDeassigned());

            _machine.Configure(State.Deferred)
                .OnEntry(() => _assignee = null)
                .Permit(Trigger.Assign, State.Assigned, assignee => OnAssigned(assignee));
        }

If this is accepted then one interesting item of discussion is when the action should be executed.
In the QP framework I have worked with the action is performed in the source state:
TransistionAction() -> ExitAction() -> EntryAction().

**Comment by nblumhardt** [comment]
Thanks for the idea @HenningNT!

I think saving a line of code is worthwhile when we can do it, but I think the (false) implied symmetry between `Permit()` and `PermitIf()` make this one questionable:

```csharp
            .Permit(Trigger.Close, State.Closed, () => Action())
            .PermitIf(Trigger.Close, State.Closed, () => Condition())
```

What do you think?

**Comment by HenningNT** [comment]
Or worse, I can foresee that someone does:
`    .Permit(Trigger.Close, State.Closed, OnClose)`
`    .PermitIf(Trigger.Close, State.Closed, OnClose)`

The compiler would complain about it, but you have a good point.

However, I still think it's a worthwhile addition. The associated action would be optional.
I don't use the PermitIf that much, probably because I have used the QM modeller so much. I think the guards clutter the model too much, making it harder to read the model. That's hardly a good reason for introducing a new trigger action, though...

Some time ago I made a class that loaded a configuration when transitioning from idle to 'active'. In hind sight I could have done it differently, but I ended up using the entry action of a transient state to load the configuration. If I had the trigger action available at the time I could have used that, and reduced the complexity a bit. Something like this:

            _machine.Configure(State.Idle)
                .OnEntry(OnEnterIdle)
                .InternalTransition(Trigger.ButtonPress, HandleButtonPress)
                .Permit(Trigger.MakeCoffeeFromArabicaBeans, State.GrindBeans, LoadArabicaBeans)
                .Permit(Trigger.MakeCoffeeFromEspressoBeans, State.GrindBeans, LoadEspressoBeans)
                .PermitIf(Trigger.DispenseHotWater, State.HotWater, IsHotWaterAvailable)
                .PermitIf(Trigger.SteamedMilk, State.SteamMilk, IsHotWaterAvailable);

HandleButtonPress would then evaluate what button was pressed, and Fire the corresponding Trigger. However, you could very well argue that LoadArabicaBeans and LoadEspressoBeans (and the conditions) could be done in HandleButtonPress :-D  But then all logic ends up in HandleButtonPress.

I would like to add the trigger action as it adds a bit more flexibility and convenience, but I see that it could be confusing.

**Comment by nblumhardt** [comment]
It's a tough one.

Would the addition of an `OnExitBy()` (analogous to `OnEntryFrom()`) be an improvement? (I think it was discussed in #119 also).

**Comment by HenningNT** [comment]
`OnExitBy()` would achieve the same goal as adding an Action to `Permit()` (and all it's variations...), that's true... I don't really like `OnEntryFrom()` as it implies knowledge of the past and of what has happened in another state. Maybe that's just me, I think that states should not care what has happened because that knowledge creates a "dependency" between states.

Adding a `OnExitBy()` would add a bit of complexity in assigning the Action to a Trigger, and make the configuration more verbose as it would require two lines instead of one. I prefer having all information about a Trigger on one line.

**Comment by nblumhardt** [comment]
> I don't really like OnEntryFrom() as it implies knowledge of the past and of what has happened in another state.

I know what you mean. I think the tricky thing is that the configuration has to be either state- or transition-centric; Stateless chooses state-centric configuration, so the transitions have to be configured at one end or the other.

The `OnEntryFrom`/`OnExitBy` methods could probably be justified more clearly by saying that each executes _in_ the state where is configuration is declared. For example, an `OnEntryFrom` action can make assumptions about the state machine based on the state that it's in. Putting this at the other end of the transition would mean having more state-specific assumptions made from the configuration for _a different state_, which wouldn't be desirable either.

Hope this makes sense :-) Cheers!

**Comment by HenningNT** [comment]
It occurred to me that I can use the existing methods to hook up an "action" to a transition, so I can re-write this

        _machine.Configure(State.Idle)
            .OnEntry(OnEnterIdle)
            .InternalTransition(Trigger.ButtonPress, HandleButtonPress)
            .Permit(Trigger.MakeCoffeeFromArabicaBeans, State.GrindBeans, LoadArabicaBeans)
            .Permit(Trigger.MakeCoffeeFromEspressoBeans, State.GrindBeans, LoadEspressoBeans)
            .PermitIf(Trigger.DispenseHotWater, State.HotWater, IsHotWaterAvailable)
            .PermitIf(Trigger.SteamedMilk, State.SteamMilk, IsHotWaterAvailable);

By "abusing" the `PermitIf` like this:

        _machine.Configure(State.Idle)
            .OnEntry(OnEnterIdle)
            .InternalTransition(Trigger.ButtonPress, HandleButtonPress)
            .PermitIf(Trigger.MakeCoffeeFromArabicaBeans, State.GrindBeans, LoadArabicaBeans)
            .PermitIf(Trigger.MakeCoffeeFromEspressoBeans, State.GrindBeans, LoadEspressoBeans)
            .PermitIf(Trigger.DispenseHotWater, State.HotWater, IsHotWaterAvailable)
            .PermitIf(Trigger.SteamedMilk, State.SteamMilk, IsHotWaterAvailable);


Anyway, I think you make sense, but I have the opposite view :-P
`OnEntryFrom` can either be triggered by a ReEntry or an entry from any state. The state machine designer must be careful in setting up the logic (if needed), because the origin is not explicitly specified. 
On the other hand an `OnExitBy` (or `Permit(Trigger, State, Action) )` is explicitly configured to a specific state and trigger, and is configured to have a specific destination.

When extending an Active Object class additional states and triggers might be added to extend the functionality of the base class. This makes it harder to use the `OnEntryFrom`. I don't know if that's bad idea or an example of how `OnExitBy` makes it simpler to set up the state machine ;-)
