### ISSUE TITLE
InternalTransition using TriggerWithParameters with more than 1 arg

### ISSUE THREAD

**Issue by pardahlman** [dotnet-state-machine/stateless#129]
Hello,
There are trigger three flavors of `TriggerWithParameters` with generic parameters:

- `TriggerWithParameters<TArg0>`
-  `TriggerWithParameters<TArg0, TArg1>`
- `TriggerWithParameters<TArg0, TArg1, TArg2>`

These can be used both when firing events, as well as entering a new state. _However_, the `InternalTransition` only supports the usage of one-argument trigger. My question is: is there any particular reason for this? If not, would it make sense to add support for all `TriggerWithParameters` for `InternalTransition`? If so, I'd be happy to help out.

**Comment by HenningNT** [comment]
I didn't add support for more than one argument because i was lazy, and I only needed one parameter :-D

Please feel free to add more you want to 👍

**Comment by pardahlman** [comment]
Roger that! I only need two parameters, but I'm going to be generous and add support for three while I'm at it 😄

**Comment by pardahlman** [comment]
Hello again!

Thanks for quick answer. I've created a PR. If accepted, when can I expect this fix to be released? I'm wondering as I'm depending on this fix for my project.

Keep up the good work!

**Comment by HenningNT** [comment]
Released, as in released to NuGet?

**Comment by nblumhardt** [comment]
The `-dev` packages go to NuGet as soon as the PR is merged. Stable releases generally wait a while, but if you want to push the process along, verifying a `-dev` version works and commenting back on the (merged) PR would help add some certainty that everything is ready to go. HTH! Thanks for the PR, Per :-)

**Comment by kcragin** [comment]
Is there any thought to allowing regular triggers and internal triggers out to N parameters where N is "reasonably" high? Say 5? Ideally of course this rarely happens, but I've several places where I've gone to three.

What I've been doing prior to awaiting the stable release that has this PR, for internal transitions, is to create a wrapper method or an extension that calls code like this:

    var parameters = Tuple.Create(parameterOne, parameterTwo, parameterThree);
    sm.Fire(parameterizedTriggers, parameters)

I then unpack the `Tuple` in the `InternalTransition`'s action and pass those on to a strongly typed method that takes many parameters.

This works for external triggers too, but in both cases you have to deal with that shim.

**Comment by nblumhardt** [comment]
@kcragin the tuple workaround seems like a reasonable way to deal with > 3 triggers; since we're nearly 9 years into the project and no one's asked so far, it might not be worth pursuing... Thoughts?

**Comment by kcragin** [comment]
@nblumhardt, yeah I think you're right. It was an edge case for me and I wouldn't do anything for my edge case. If others spoke up, that would be the time for a re-eval. 

I've found the trusty Oberver pattern makes this pretty painless anyway; I configure up a state machine with delegates to a "state machine observer", which separates the configuration of the graph from what actually goes on when transitions occur. 

Thanks for this cool project.
