### ISSUE TITLE
Stateless should have it own exceptions - InvalidOperationException is all too common

### ISSUE THREAD

**Issue by Tuan-Minh** [dotnet-state-machine/stateless#133]
Today I lost half an hour to debug a problem, somehow perform a valid transition thrown InvalidOperationException. It turns out  the OnEntry method use First() on an empty sequence, which threw InvalidOperationException and confused the exception handling chain. To be able to handle the precise problem with invalid transition, I think Stateless should have its own set of exception.

**Comment by Tuan-Minh** [comment]
I will add a mechanism for client code to control what exception will be thrown - by default nothing change, exception will be InvalidOperationException, but this can be changed to any kind of exception client code want.

**Comment by HenningNT** [comment]
Would it be possible to share the code that resulted in that exception?
After the stae machine has been configured it should not throw exceptions when firing triggers.
You might have found a hole in the configuration argument checking, so adding a new test and fixing the hole would be nice!

**Comment by Tuan-Minh** [comment]
Never mind. The exception was thrown in my code, and because it's the same InvalidOperationException, I could not tell it apart from Stateless' ones. I have found how to customize stateless so that it throws my application exception instead of InvalidOperationException.
