### ISSUE TITLE
I need to get a list of all actions (transitions and internal actions) in the statemachine

### ISSUE THREAD

**Issue by Tuan-Minh** [dotnet-state-machine/stateless#134]
I need to get a list of all actions on all states, can I add a property AllTriggers to StateMachine?

**Comment by nblumhardt** [comment]
This is coming in #103 (reflection API), I think 👍

**Comment by Tuan-Minh** [comment]
Nice! I will make do with my version while waiting for that.

**Comment by HenningNT** [comment]
Can I just add that there is a method called PermittedTriggers? It has to be used on each state, though.

In what way would you use AllTriggers?

**Comment by vlm---** [comment]
@HenningNT For examle, we generate menu buttons from state machines and PermittedTriggers contains list of enabled button. AllTriggers would help with visibility. Right now, we have to set visibility from handpicked lists of triggers.

**Comment by Tuan-Minh** [comment]
@vlm--- ,@HenningNT exactly my situation, I need AllTrigger so that I can enable/disable things, and I don't know all the triggers as the system is extendable with new triggers by other.
