### ISSUE TITLE
Any plans to be able to inspect the state graph?

### ISSUE THREAD

**Issue by kcragin** [dotnet-state-machine/stateless#136]
Are there any plans to provide an API that allows you to walk the state graph? For example, I'd like to be able to answer the question, "If I am in state *X* can I get to state *Y*.

This would be useful in messaging systems for example.

**Comment by nblumhardt** [comment]
Hi! Yes, #103 is heading in this direction. Your input over there would be appreciated - thanks!

**Comment by kcragin** [comment]
I'll check that out. Thanks.
