### ISSUE TITLE
"Engine room" access

### ISSUE THREAD

**Issue by TheGissel** [dotnet-state-machine/stateless#139]
First of all, I would like to say that this is one of the most useful and timesaving .NET libs in the UNIVERSE! Thank you for that.

There is a lot of fields/properties that would be great to have access to when you subclass StateMachine (and properly other classes too).

For example, I often need timeout triggers in my projects so I have subclassed StateMachine and added my timeout features. But to make it perfect I would need access to private GetRepresentation(TState state) and perhaps other elements.

Is there something that talks against making the internal stuff protected?

Most of my additions are specialized for my needs, so they are not suitable for an official contribution to the project, but I would not mind sharing them for discussion.

Cheers

**Comment by nblumhardt** [comment]
@TheGissel thanks for getting in touch. The internal stuff is not really designed to be stable between versions, so it's probably best to fork the code if you need to do deep surgery at the moment. Hope this helps, NB

**Comment by TheGissel** [comment]
I can understand that, so no problem  :)
