### ISSUE TITLE
Please update Stateless to support .NET 4

### ISSUE THREAD

**Issue by jjroth** [dotnet-state-machine/stateless#14]
I have used the latest version of Stateless (2.5.11) in a recent project. It worked fine on my development machine. 

I ran into issues when I deployed to a UAT test machine.

I get the following error message whenever I call the CanFire method on the StateMachine:

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047) File name: 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at Stateless.StateMachine`2.StateRepresentation.TryFindLocalHandler(TTrigger trigger, TriggerBehaviour& handler)
   at Stateless.StateMachine`2.StateRepresentation.TryFindHandler(TTrigger trigger, TriggerBehaviour& handler)
   at Stateless.StateMachine`2.CanFire(TTrigger trigger)
   at Company.MyProject.Entities.Models.Form.TryUpdateStatus(FormTriggers trigger) in ...

The only way I was able to get around this was to install the Nuget package "Stateless for .NET 4.0" (https://www.nuget.org/packages/stateless-4.0/).

It would be nice if the changes made in that clone could be incorporated into the official stateless project so that stateless works properly in .NET 4.

**Comment by arun02139** [comment]
One think, I hope that if such moder support is added, backward compatibility will be maintained -- I am using parts of 3.5 (Unity development) and very happy that Stateless works in my environment ^^

**Comment by matt-richardson** [comment]
@jjroth - it appears you are missing a .net framework patch. I believe .net 4.0.3 fixes it (I found that in searches for a related problem)

**Comment by matt-richardson** [comment]
That said, it would be great if the nuget package built framework specific packages. The related issue I am facing is `warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.` during build, as Stateless tries to bind to `"System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes"`.

I understand that there is value in the PCL builds, but it would be good if they could exist side by side with .net 4.0 dlls.

**Comment by nblumhardt** [comment]
This is now supported by 3.x.x-dev.
