### ISSUE TITLE
Reflection API remaining tasks

### ISSUE THREAD

**Issue by nblumhardt** [dotnet-state-machine/stateless#143]
From #103 

 - [x] `Superstate` needs to be lazily linked up as per the transitions, so that `x.Superstate` is a fully-populated info object
 - [x] Use a common base class for all transitions, so that e.g. `DynamicTransitionInfo` and `TransitionInfo` can share  common attributes
 - [x] `DynamicTransitionInfo.Destination` -> `DestinationDescription`
 - [x] Consider `ActionInfo` to represent actions; in the process we may be able to standardize how `Description` values are handled (can we unify actions and guards as `InvocationInfo` or similar?)
 - [x] Update the DotGraph HTML work and merge
 - [x] `TriggerInfo.Value` -> `UnderlyingTrigger`
 - [x] `StateType` and `TriggerType` should be on `StateMachineInfo`
 - [x] `TransitionInfo.GuardDescription` should be plural - multiple guards can be attached to a single trigger

**Comment by HenningNT** [comment]
I don't like to bring bad news, especially considering all the amazing work that has been done... but I had a look this morning, and I couldn't get it to work. I tried it on the Bug example to get a DotGraph, and this resulted in a StackOverflowException.

CreateStateInfo has a recursive call when it generates a list of substates. A superstate always has substates, and so it then calls CreateStateInfo on each substate. The substates have superstates, so it calls CreateStateInfo on the superstate. This goes on until the stack is full.

I did a quick hack, which did produce graphs for the Bug example and the PhoneCall example:

        internal static StateInfo CreateStateInfo<TState, TTrigger>(StateMachine<TState, TTrigger>.StateRepresentation stateReperesentation)
        {
            if (stateReperesentation == null)
                throw new ArgumentException(nameof(stateReperesentation));

            var substates = stateReperesentation.GetSubstates().Select(s => CreateSubStateInfo(s)).ToList();
            var entryActions = stateReperesentation.EntryActions.Select(e => e.ActionDescription).ToList();
            var exitActions = stateReperesentation.ExitActions.Select(e => e.ActionDescription).ToList();
            var ignoredTriggers = FindIgnoredTriggers(stateReperesentation);

            StateInfo superstate = CreateSuperStateInfo(stateReperesentation.Superstate, substates);

            return new StateInfo(stateReperesentation.UnderlyingState, typeof(TState), superstate, substates, entryActions, exitActions, ignoredTriggers);
        }
        internal static StateInfo CreateSuperStateInfo<TState, TTrigger>(StateMachine<TState, TTrigger>.StateRepresentation stateReperesentation, List<StateInfo> substates)
        {
            if (stateReperesentation == null)
                return null;

            var entryActions = stateReperesentation.EntryActions.Select(e => e.ActionDescription).ToList();
            var exitActions = stateReperesentation.ExitActions.Select(e => e.ActionDescription).ToList();
            var ignoredTriggers = FindIgnoredTriggers(stateReperesentation);

            StateInfo superstate = null;

            if (stateReperesentation.Superstate != null)
                superstate = CreateStateInfo(stateReperesentation.Superstate);

            return new StateInfo(stateReperesentation.UnderlyingState, typeof(TState), superstate, substates, entryActions, exitActions, ignoredTriggers);
        }
        internal static StateInfo CreateSubStateInfo<TState, TTrigger>(StateMachine<TState, TTrigger>.StateRepresentation stateReperesentation)
        {
            var substates = stateReperesentation.GetSubstates().Select(s => CreateStateInfo(s)).ToList();
            var entryActions = stateReperesentation.EntryActions.Select(e => e.ActionDescription).ToList();
            var exitActions = stateReperesentation.ExitActions.Select(e => e.ActionDescription).ToList();
            var ignoredTriggers = FindIgnoredTriggers(stateReperesentation);

            return new StateInfo(stateReperesentation.UnderlyingState, typeof(TState), null, substates, entryActions, exitActions, ignoredTriggers);
        }
        private static List<TriggerInfo> FindIgnoredTriggers<TState, TTrigger>(StateMachine<TState, TTrigger>.StateRepresentation stateReperesentation)
        {
            List<TriggerInfo> ignoredTriggers = new List<TriggerInfo>();
            foreach (var triggerBehaviours in stateReperesentation.TriggerBehaviours)
            {
                foreach (var item in triggerBehaviours.Value)
                {
                    if (item is StateMachine<TState, TTrigger>.IgnoredTriggerBehaviour)
                        ignoredTriggers.Add(new TriggerInfo(triggerBehaviours.Key, typeof(TTrigger)));
                }
            }
            return ignoredTriggers;
        }

CreateStateInfo now calls CreateSuperStateInfo and CreateSubStateInfo for super and sub-states respectively, but it needs more testing with deeper state nesting.
Looking at ´StateMachineInfo GetInfo()´ it seems that the 'CreateStateInfo' doesn't have to be recursive, as it is run on each of the StateRepresentations?

**Comment by nblumhardt** [comment]
Thanks for checking it out @HenningNT - bit of an oversight from me there :-D

I've just pushed #144 that should resolve this and knock the top (related) item off of the checklist.

The bug tracker example produces:

```dot
digraph {
 Open -> Assigned [label="Assign"];
 Assigned -> Assigned [label="Assign"];
 Assigned -> Closed [label="Close"];
 Assigned -> Deferred [label="Defer"];
 Deferred -> Assigned [label="Assign"];
node [shape=box];
 Assigned -> "<.ctor>b__7_2" [label="On Entry" style=dotted];
 Assigned -> "<.ctor>b__7_3" [label="On Exit" style=dotted];
 Deferred -> "<.ctor>b__7_4" [label="On Entry" style=dotted];
}
```

I'm not sure about those last three; need to look into the generated labels (?). Should still be an improvement on `StackOverflowException` :-)

If you have any opportunity to kick the tires again, it'd be great to hear what you find!

**Comment by HenningNT** [comment]
I think the compiler converts lambda expressions into automatically named functions. Swapping out the lambda with the method name makes the output sensible.
Maybe this can be of use:
http://stackoverflow.com/questions/8225302/get-the-name-of-a-method-using-an-expression

**Comment by betty-crokker** [comment]
Why do classes like TriggerInfo have a TriggerType member?  Does it ever return anything besides typeof(Value)?

**Comment by betty-crokker** [comment]
I'm happy to work on some of these issues, but as Frodo once said "I do not know the way".  :-)

I'm not a collaborator on this main repo, so do I make my own personal github fork and work there?  If so, do I check things off of the list @nblumhardt made when I start working on them (so we don't duplicate efforts) or when I finish?

Or should I continue working on the @psibernetic 's fork?

**Comment by psibernetic** [comment]
@betty-crokker Create your own fork and a new branch based on dev branch. Issue new PR's back to this repo.

**Comment by psibernetic** [comment]
@betty-crokker typeof(Value) would return object I believe, you would need to use .GetType(). The intent was just to make it more obvious.

**Comment by betty-crokker** [comment]
To me, the TriggerType makes things less obvious.  It makes me think that somehow there's a TriggerType that is different from typeof(Value) ...

**Comment by nblumhardt** [comment]
@betty-crokker good point; I think `StateType` and `TriggerType` should actually be on `StateMachineInfo`.

**Comment by nblumhardt** [comment]
@HenningNT thanks - I think in these cases perhaps, we should just detect that we're looking at a lambda rather than a first-class method, and use the text `"(lambda)"` or something similar as names for the actions.

**Comment by psibernetic** [comment]
@nblumhardt  Good suggestions.

**Comment by betty-crokker** [comment]
@nblumhardt when you say "TriggerInfo.Value -> UnderlyingTrigger" are you saying that once we remove the 'TriggerType' property from TriggerInfo, it's just a wrapper around an 'object' (actually a TTrigger) so why not remove the entire TriggerInfo class and have DynamicTransitionInfo.Trigger (for example) just return that 'object' (actually TTrigger)?

**Comment by betty-crokker** [comment]
Have we thought about making our reflection/info classes generic?

e.g. instead of DynamicTransitionInfo, make it DynamicTransitionInfo<TState, TTrigger> and then properties like 'Trigger' could actually be of type TTrigger instead of object ...

**Comment by psibernetic** [comment]
@betty-crokker There was concern from @nblumhardt  and @HenningNT, I believe, that it was more noise than was necessary, I changed to object and associated Type properties accordingly. It does make it easier to work with serialization this way, but hard to work with the values. Trade-offs suck.

**Comment by betty-crokker** [comment]
@nblumhardt  - I'm new to github, so I'm not quite sure how a checklist works.  Clicking on it does nothing, do I need to be added as a collaborator in order to contribute to this project?

**Comment by nblumhardt** [comment]
Hi @betty-crokker - I think you'd need more permissions to check the list items off, but I don't think we can yet - AFAIK that item isn't done yet, correct? Thanks!

**Comment by betty-crokker** [comment]
So what do I need to do, in order to contribute to this project?

**Comment by nblumhardt** [comment]
In the top right of the GitHub page, you'll see a _Fork_ button, which you can use to create your personal working copy. When you have made changes to it, you can then create a _Pull Request_ to send the diff back here. We'll review it and possibly suggest some tweaks, which you will make on your fork, and then _Merge_ to bring those changes in. Does that help? Cheers!

**Comment by betty-crokker** [comment]
Thanks @nblumhardt , that's what I thought ... but then I saw how @HenningNT  did that fork for issue #147 , and I liked that because it made it really obvious in this issue that the "Extracting common abstract base class for transition info" item was being worked on.  But I can certainly do a manual notice here saying what I'm working on, and then my own fork.  Thanks!

**Comment by HenningNT** [comment]
@betty-crokker , #147 is actually a pull request, not an issue. What I did was pull in other changes from dev from this repository to my fork, then did my changes in my fork, and then opened a pull request to pull my changes back into this repository again. I'm rather new to GitHub and git, but I think that is one way to do it :-)

**Comment by betty-crokker** [comment]
Cool thanks!

OK, I'm moving StateType and TriggerType into StateMachineInfo

**Comment by betty-crokker** [comment]
So that I could work on stateless, I upgraded from Windows 7 to Windows 10 and from Visual Studio 2015 to Visual Studio 2017.  All is well except that VS2017 believes there aren't any tests in my solution.  Has anyone else encountered this?

**Comment by betty-crokker** [comment]
BTW, I'm working on ActionInfo now.

**Comment by betty-crokker** [comment]
I brought in the HTML code for DOT graph creation that @sle118 wrote, it's in a new branch in my fork named [DotGraph_HTML](https://github.com/betty-crokker/stateless/tree/DotGraph_HTML).  As soon as we agree to merge or delete these other PRs, I'll do the final steps to use the newest reflection info.

**Comment by HenningNT** [comment]
I marked "Use a common base class for all transitions, so that e.g. DynamicTransitionInfo and TransitionInfo can share common attributes"  and "TransitionInfo.GuardDescription should be plural - multiple guards can be attached to a single trigger" as done, it looks like those are completed.

**Comment by betty-crokker** [comment]
Regarding DynamicTransitionInfo.Destination: I went even further and replaced DestinationDescription with DestinationStateSelectorDescription (an awkward name to be sure) because it's now an InvocationInfo not just a string.

**Comment by jsobell** [comment]
OK, but is there a fundamental issue in this statement in general? :
> TransitionInfo.GuardDescription should be plural - multiple guards can be attached to a single trigger

Guards in workflows don't exist on Triggers, they exist on transitions. When a trigger occurs, all of the potential trigger-keyed transitions are considered, but only the one with the true guard condition is honoured.
As such, a transition can only have a single description, and I'd say the transition itself is where the description should be defined. Why do we differentiate between guarded transitions, non-guarded, and internal?
I suspect this might be a low-level issue at the moment. Sure, it all works because it's simply a state machine engine, but I suspect it's targeted towards people not using guard expressions, because as soon as you use them in earnest you hit issues for reason related to those mentioned above.

**Comment by betty-crokker** [comment]
@nblumhardt @HenningNT Do we consider this issue complete?  Ready to ship as a new NuGet version?

**Comment by HenningNT** [comment]
As far as I can tell the remainder of the open issues has been completed, so I closed them. I guess it's show time?

**Comment by nblumhardt** [comment]
I guess it is! I'll set up a "4.0" release PR so that we can see the whole changeset for the release; some testing of the currently-published dev package will be needed if anyone out there can try it:

https://www.nuget.org/packages/Stateless/4.0.0-dev-00244

:-)

**Comment by HenningNT** [comment]
I gave it a go on my projects, and it (still) worked as expected 👍
