### ISSUE TITLE
How to split a larger statemachine in separate sub-statemachines as distinct classes?

### ISSUE THREAD

**Issue by BrainCrumbz** [dotnet-state-machine/stateless#15]
Substates are great, but when state machine starts to have a number of states that have substates, the whole thing starts to be a little bit too large, and less easy to manage. As per question, is there a way to split a larger state-machine in a number of smaller _sub_ state-machines? 

Just by mean of example, think as if I have a state machine made of _LoggedOutState_ and _LoggedInState_, which in turn has a number of substates, _UserEditing_, _UserAdding_, ...  
I would like to define a high-level state-machine with the two states, and then a state-machine dedicated to just the _LoggedIn_ scenarios. Then somehow make it so that triggers defined for entering in _LoggedInState_ could start/enter a state in the lower-level state-machine, as well as triggers defined to exit _LoggedInState_ could stop/leave a lower-level state.

Thanks all

PS we just posted also a question on [StackOverflow](http://stackoverflow.com/questions/28995177/split-state-machine-in-several-classes-using-stateless-library).

**Comment by nbarbettini** [comment]
I also think this would be useful!

**Comment by nblumhardt** [comment]
This may be out of left field, but I wonder if there's any way to take advantage of the fact that states can be represented by any value:

```csharp
// May use the delegates to externalze state storage
var sm1 = new StateMachine<State, Trigger>();
var sm2 = new StateMachine<State, Trigger>();

var master = new StateMachine<StateMachine<State, Trigger>, MasterTrigger>();

master.Configure(sm1)
  .OnEntry(t => sm1.Fire(Trigger.Starting))
  .Permit(MasterTrigger.MoveOn, sm2)
```

The API gets pretty crazy, but then, I think any API to do this kind of thing will suffer some complexity.

Not knowing much more about how the requirements fit together it's hard to say more - hope this helps!

**Comment by teo-mateo** [comment]
One can even derive from the main state machine. However this approach is
suitable for a use case that is at least slightly different... yeah.
anyway here's what I came up with:

See this and the comments inside: http://pastebin.com/Sm0BvG79
