### ISSUE TITLE
Confusion with Example

### ISSUE THREAD

**Issue by jasel-lewis** [dotnet-state-machine/stateless#150]
Greetings.  One thing that has always confused me is the primary example (the first block of code in the `README.md` file).

There are two allowable transitions _to_ `State.OffHook` once `Trigger.HungUp` has been fired.  One from `State.Ringing` and one from `State.Connected`.

Should `State.OffHook` really be `State.OnHook`?

When a phone is hung up, it is placed back "on hook."  When it is said to be "off hook," the phone has been lifted from its cradle, thereby allowing you to place a call or otherwise communicate over an established connection.

When I first looked at `Stateless` about a year ago in order to implement it within a project, this point of confusion really bothered me and made it overly difficult to understand the configuration purely from the example (which should have been very simple as the example is as concise as it can be).

Now that I am once again implementing `Stateless` into a different project, I am just as befuddled at having re-encountered the confusion within the example.  Unless I am completely missing something, I believe `State.OffHook` should really be `State.OnHook`.

I believe the correction should also apply to the similar `.Permit(Trigger.HungUp, State.OffHook)` configuration example in the **Hierarchical States** section.

If I _am_ mistaken, please help clear the confusion for me.  This truly has, in the past, prevented me from digging in deep and implementing `Stateless` to its fullest capability (a need which I presently have, as this current project requires full implementation of triggers, guard clauses and entrance criteria).

Thank you,
R. J.

**Comment by HenningNT** [comment]
If you see it from the perspective of the caller/telephone user, then I think it makes sense the way it is written. 
The user has picked up the phone, and dials a number causes the transition from OffHook to Ringing, and so on.
When the other end terminates the connection (.Permit(Trigger.HungUp, State.OffHook)) the user still has the phone in hand, and the state is OffHook.

One of the hardest things with state machines is deciding how to model behaviour. Soemething that is perfectly clear to one might be confusion to others. Maybe we should add something to the example to describe the actors perspective?

**Comment by jasel-lewis** [comment]
I completely agree with your statement that perspective is key.  It is always a struggle to stay focused unless you pick a single perspective and stick with it.  For me, I try to keep the perspective of the object itself - in this instance the phone.  I would not be modeling the user.  Granted, the user _performs_ actions, but the actions are performed against (impact) the modeled object.

As you say, all a matter of perspective.  Being this is so, it would be helpful to stick to a single perspective per example.  In the first example, the configured states make it clear that the phone is the object being modeled (it would not be logical for the user to be in one of the `State.OffHook`, `State.Ringing` or `State.Connected` states).  It would be a rather correct assumption to expect the same perspective to be necessary when fluently identifying the permissions (composed of the triggering action and the to-be state) - being that the phone is hung up and the phone enters the next state of `State.OnHook` (as opposed to `State.OffHook`).

I don't mean to nit-pick - I am just mulling over what you replied with and what I'm still seeing.  What is required by the framework is clear to me now.  Your reply helped with that - thank you!  I just still see the example as blending two perspectives (the user and the phone) in a single line of code - this is the confusing part.

**Comment by jasel-lewis** [comment]
@HenningNT I did not want to edit my last post - but once I sent it, I re-read your reply and I can see what you are saying.  You modeled the action of the _other_ phone, being that once the _other_ phone is HungUp, the connection is terminated, yet _our_ user may still have his/her phone (the primary phone being modeled) in his or her hand (`State.OffHook`).  Got it.

Yeah... something needs to be said in the example text which identifies this.  I'm not sure how to make that clear, though...

**Comment by nblumhardt** [comment]
Re-reading the example, I think it's still a little confusing whether it's one party or the other "hanging up".

Could we just make up a slightly different set of states/triggers without the ambiguity? Happy to update it if we can come up with a clearer one 👍

**Comment by HenningNT** [comment]
What if we change the Trigger HungUp to CalleHungUp. If the callee hangs up the connection isn't actually terminated. This is by design so that the callee can put down the receiver and pick up the receiver in another room and continue the call...


            phoneCall.Configure(State.OffHook)

	            .Permit(Trigger.CallDialed, State.Ringing);



            phoneCall.Configure(State.Ringing)

	            .Permit(Trigger.CalleeHungUp, State.OffHook)

	            .Permit(Trigger.CallConnected, State.Connected);



            phoneCall.Configure(State.Connected)

                .OnEntry(t => StartCallTimer())

                .OnExit(t => StopCallTimer())

                .InternalTransition(Trigger.MuteMicrophone, t => OnMute())

                .InternalTransition(Trigger.UnmuteMicrophone, t => OnUnmute())

                .InternalTransition<int>(setVolumeTrigger, (volume, t) => OnSetVolume(volume))

                .Permit(Trigger.LeftMessage, State.OffHook)

	            .Permit(Trigger.HungUp, State.OffHook)

	            .Permit(Trigger.PlacedOnHold, State.OnHold);



            phoneCall.Configure(State.OnHold)

                .SubstateOf(State.Connected)

                .Permit(Trigger.TakenOffHold, State.Connected)

                .Permit(Trigger.CalleeHungUp, State.OffHook)

                .Permit(Trigger.PhoneHurledAgainstWall, State.PhoneDestroyed);
