### ISSUE TITLE
PermitDynamic remaining in the same state?

### ISSUE THREAD

**Issue by mgefvert** [dotnet-state-machine/stateless#151]
Is it possible to use PermitDynamic to return a value that allows the StateMachine to remain in the same state without switching?

I assume that's what PermitDynamicIf is for - figure out whether to switch, and then calculate the next state using the dynamic function. However, in some cases, those are both results of the same call; you call the hypothetical function FigureOutNextState to see if it wants to switch; and then call FigureOutNextState again to see what state it wanted to switch to. If the calculation is complex, it seems unnecessary.

Based on the source code, it seems that if that the dynamic function returns the same state, OnEnter/OnExit will be processed again?

**Comment by nblumhardt** [comment]
Thanks for the note. Yes, `PermitDynamicIf()` is going to be the way to go here. Unfortunately, the self-transition (re-entry) behavior is going to be used out there in the wild, so changing the semantics of `PermitDynamic()` is probably not an option at this stage.

**Comment by mgefvert** [comment]
Yeah, I thought about that as well. After playing around with my design a little bit, I refactored things and removed the dependency on PermitDynamic altogether - which I think in the long run is better. Thanks for your quick reply though - much appreciated!

**Comment by nblumhardt** [comment]
You're welcome - glad you found a suitable solution 👍
