### ISSUE TITLE
vNext release date?

### ISSUE THREAD

**Issue by edoreat** [dotnet-state-machine/stateless#152]
Hi!

I am new to using Stateless (actually using 3.1.0) and I am really loving it. Good job! I looked at the dev branch and found out the GetInfo() method in StateMachine. I wonder when do you plan to release the next version since this is exactly what I need for a required feature.

Thank you!

**Comment by nblumhardt** [comment]
Hello, thanks for the question!

There's no set date - we have some work items remaining in #143 to get through, and then would seek more feedback before calling it "done".

You can, however, install the `-pre` packages today to try it out; it would help a lot to know what works (and what is lacking) for your use case. Please feel free to comment on the linked issue, if so.

Thanks!

**Comment by edoreat** [comment]
Ok I will try it out and get back to you. Thanks for the quick answer and keep up the good work!
