### ISSUE TITLE
PermitIf with parameters

### ISSUE THREAD

**Issue by sharonrk** [dotnet-state-machine/stateless#155]
I'd like to be able to pass an object to my guard clause but I haven't found a way for that. Does it exist? If not, was that a specific design decision?

**Comment by nblumhardt** [comment]
Hi Sharon - I don't believe there's currently an API for this, but neither was it specifically ruled out.

It might be worth digging around to see how much implementation effort is involved; I'm not sure how this would fit into the design but it sounds reasonable.

**Comment by HenningNT** [comment]
I think this is an excellent question, and I would to have this feature.

I had a look into how the guards are handled, and I think we would have to re-write a fair bit of to make it happen.

Please feel free to submit a PR 😁

**Comment by KrauseT** [comment]
This sounds like an interesting and useful feature. If I find the time, I will also look at the handling of the guards.

**Comment by Doan-Van-Tuan** [comment]
Is anyone working on parameterized Permit and PermitIf? I'd like to have this feature so if no one currently working on that I'll.

**Comment by ArturKarbone** [comment]
@Sharonrk have you considered using lambdas. Yes you can't pass an object directly but you can reference it via lambda. For instance

```
Machine.Configure(ApplicationStatus.PendingConfirmation)
                    .PermitIf(Activity.Submit, ApplicationStatus.Submitted, () => this.Application.HasAllRequestedFiles)
                    .Permit(Activity.Withdraw, ApplicationStatus.Withdrawn);
```

**Comment by Sharonrk** [comment]
@ArturKarbone that sounds like an interesting idea. Currently, my state machines are being configured out of static classes so it won't work without some refactoring. I will try it out with the TelephoneCallExample

**Comment by jsobell** [comment]
At the moment we can have multiple PermitIf, so long as they are mutually exclusive, but I don't see any way to know which was in play.
In out state machine scenario we perform actions on transitions, so we either have to be able to add actions to a guarded transition (messy), or we have to use the `OnTransitioned` handler to look at the transition being performed and act on that.
The issue at the moment is that there doesn't appear to be any way to know which transition was performed.  Sure, we can see the source and destination states, but when there are multiple transitions available between those states we don't know which it is.

Essentially, we need either an `OnTransition` raised by transitions, or the State's `OnEntry` has to be given something identifying the transition that went there. The current `OnTransitioned` is too late.
I would imagine we would also need an ID associated with the guarded transition. At the moment we have a description.

Unless someone has another suggestion, how can an action be applied during the transitions below without knowing which of these transitions was followed?

![image](https://cloud.githubusercontent.com/assets/834155/26182965/117c6902-3bbf-11e7-9afc-f0c25d66eed7.png)

**Comment by KrauseT** [comment]
I think this should be a new issue because it has nothing to do with this issue.
In principle, I think that your problem can be solved with an _OnEntryFrom_ because this must be configured together with the trigger that was responsible for the transition.

**Comment by jsobell** [comment]
You're probably right, I'll move it to a new issue.
Incidentally, `OnEntryFrom` won't help because the trigger is not the transition. In the above example the trigger was `CallDialled` in both cases, but there's no way to distinguish between the transitions that were followed.

**Comment by dannyzhan** [comment]
guys, I need this feature too, thanks!
is there any plan to add the feature? it's been opened for 7 months, very long ago.

**Comment by HenningNT** [comment]
Added in #233, closing this.
