### ISSUE TITLE
Accept pre-built parameterized triggers

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [dotnet-state-machine/stateless#159]
Currently, parameterized triggers are defined at instance level of state machine. Sometimes one might need   to define static action. Can I add this functionality?

**Comment by HenningNT** [comment]
Do you mean "can I add functionality to create static parameterized triggers"?

**Comment by Doan-Van-Tuan** [comment]
Yeah, that is what I need. Trigger created via SetTriggerParameters<> is tied to instance of the state machine, there are no option to create trigger for a concrete state machine type.

**Comment by HenningNT** [comment]
How would you use this?
Two (or more) state machine instances could use the same trigger, and the parameter could change randomly?

**Comment by Doan-Van-Tuan** [comment]
I'm experimenting with making SaveTriggerConfiguration() a protected method so that if one wishes, he can derive from StateMachine and define a static parameterized trigger collection. My code is similar to this snippet:
`
    public class ParameterizedTrigger<TState, TTrigger, TArgument>: StateMachine<TState, TTrigger>.TriggerWithParameters<TArgument>
    {
        public ParameterizedTrigger(TTrigger underlyingTrigger) : base(underlyingTrigger)
        {
        }
    }
    public class CustomStateMachine<TState, TTrigger> : StateMachine<TState, TTrigger>
    {
        private static readonly Dictionary<TTrigger, TriggerWithParameters> StaticTriggers = new Dictionary<TTrigger, TriggerWithParameters>();

        public CustomStateMachine(Func<TState> stateAccessor, Action<TState> stateMutator) : base(stateAccessor, stateMutator)
        {
            foreach (var trigger in StaticTriggers)
                SetTriggerParameters(trigger);
        }

        public static ParameterizedTrigger<TState, TTrigger, TArgument> CreateStaticParameterizedTrigger<TArgument>(TTrigger underlyingTrigger)
        {
            var trigger = new ParameterizedTrigger<TState, TTrigger, TArgument>(underlyingTrigger);
            StaticTriggers.Add(underlyingTrigger, trigger);
            return trigger;
        }
    }
`

**Comment by Doan-Van-Tuan** [comment]
The methods SetTriggerParameters() do two things: define a parameterized trigger AND register it. 
What I need is actually the option to define trigger and register trigger independently. To do this, I need to call SaveTriggerConfiguration() directly. I'm right now using dynamic to call it.

**Comment by nblumhardt** [comment]
Thanks for the details, @Doan-Van-Tuan.

As Henning pointed out, a parameterised trigger in Stateless is an instance-level concept. I can see some scenarios where keeping track of the trigger object per statemachine could be extra work, but I don't think static triggers is a direction we want to take the API at this point.

**Comment by Doan-Van-Tuan** [comment]
What I see is there is a discrepancy in the API. This is my journey with Stateless:

- There is no type constraint on TTrigger and TState, so the first version of the software will use enums for both trigger and state.
- Then I have better grip of the library, I introduce an IActionInfo interface to serve as HATEOAS actions, and use this as the trigger. The statemachine will conveniently return a list of usable actions. All the actions are defined as static read-only field of a class.
- Then I discover that the trigger can be parameterized. Neat! My code will be much cleaner with these. And there I got hit by the road block: the parameterized trigger cannot reside in the same Actions class because I cannot define one independently from the statemachine. The state machine insists that it will define AND register the trigger in one go, unlike unparameterized one where you define them at one place and register it with the state machine.

So what I need is not static triggers that common to all the statemachines of the same type, but the ability to register a pre-formed trigger in the same way with registering my own instance of un-parameterized  trigger.

The code would be similar to this:
'var commentAction = new ParameterizedAction<string>("Reject");
sm.InternalTransition(commentAction, SaveComment);'

**Comment by Doan-Van-Tuan** [comment]
By the way, there is no Permit and PermitIf with parameters. Would you tell me the reason, or can I add these?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. You may need to adjust your design, so that for each `StateMachine` you're keeping track of, you keep with it the parameterized trigger objects as well. The state machine and its triggers need to live together, if you're using Stateless.

#155 is the tracking issue for `PermitIf` with parameters.

Thanks!

**Comment by Doan-Van-Tuan** [comment]
My question now is: Why the state machine happily accept a unparameterized trigger from client code without caring where the trigger instance came from, but insist on creating and managing parameterized trigger instance on it own?

**Comment by nblumhardt** [comment]
Triggers are assumed to be by-value. An int `42` is the same as another int `42`, regardless of where it came from.

Instance-based triggers are just the way the API is designed - the mechanism ensures trigger parameter types always match what the state machine expects.

```csharp
var sm1, sm2;
var t1 = sm1.SetTriggerParameters<string>(Trigger.Assign);
var t2 = sm2.SetTriggerParametesr<int, string>(Trigger.Assign);
sm1.Fire(t2, 42, "Hello"); // Wrong params; we detect and prevent this today
```

It could be designed another way - but this is how Stateless works - we could re-design it with different goals and constraints, but sticking with a single way of doing things seems better for the health of the API in the long run. HTH!

**Comment by Doan-Van-Tuan** [comment]
@nblumhardt 
Please have look at the test: https://github.com/Doan-Van-Tuan/stateless/blob/externalize-parameterized-trigger/test/Stateless.Tests/ExternalTriggerWithParameter.cs

To me, semantically, the two actions Close and Comment have no difference. Both are triggers. Both can be misused the same way (e.g. register the trigger at sm1 then use it with sm2 like the situation in your previous comment). I do not see any problem with using Trigger that way. The one with parameter behave exactly the same with the one without, all the type constraint preserved. Why treat them differently?

**Comment by nblumhardt** [comment]
In the case you've linked, the triggers can be used with either statemachine because they _are_ the same. This is the `42` === `42` case. Parameterized triggers are different because each state machine might require different _parameters_ for the same underlying trigger object. It's instance/configuration-specific, not something that can be decided at the type level.

I will close this ticket because I don't want to take up more of your time when chances of taking this path seem negligible. Thanks again for your input and thoughts though!

Regards,
Nick

**Comment by Doan-Van-Tuan** [comment]
@nblumhardt Oh, thanks for your care regarding my time. Don't worry, I do this in my work time :).

I'll bother you one last time regarding this topic: can I enable the sharing of trigger instances between state machine _in a way that it would not change the library behavior out of the box_: the method SaveTriggerConfiguration can be change to **protectec virtual** so that anyone want to share the trigger must extend StateMachine<> to use the method?
