### ISSUE TITLE
Introduce Shoudly for assertions

### ISSUE THREAD

**Issue by ArturKarbone** [dotnet-state-machine/stateless#162]
Hi Team

What do yot think if we can leverage [Shouldy](https://github.com/shouldly) library for asserting part of the tests? For couple of reasons:

1. In general it has more convenient syntax
2. In some cases we will be able to write in more functional/fluent way without introducing temp variables (just to assert the later on).

Have a look at original VS fluent+Shoudly way of this:

```
        [Fact]
        public void IncludesUnderlyingState()
        {
            var stateRepresentation = CreateRepresentation(State.B);
            Assert.True(stateRepresentation.Includes(State.B));
        } 
````

```
        [Fact]
        public void IncludesUnderlyingState()
        {
            CreateRepresentation(State.B)
                .Includes(State.B)
                .ShouldBeTrue();         
        }
```

Ready to contribute.

**Comment by HenningNT** [comment]
I think we should use it just because it has a method named AssertAwesomely 😁

**Comment by nblumhardt** [comment]
Thanks for the suggestion. I don't think the advantages justify the churn at this point. Shouldly is nice, but there are benefits both ways depending on the type and complexity of the test (being able to quickly scan for lines beginning with `Assert.` being one).

**Comment by ArturKarbone** [comment]
Thanks for the feedack. My interpretation is that Shouldy not needed at this point. If so we can close the issue.

**Comment by nblumhardt** [comment]
Thanks Artur. If we were starting from scratch today I think it'd be a strong contender. Maybe the next project! :-) 👍

**Comment by ArturKarbone** [comment]
Sure, Nicholas .
