### ISSUE TITLE
InvalidCastException raised within AddRelationships (in StateInfo.cs)

### ISSUE THREAD

**Issue by itsjohno** [dotnet-state-machine/stateless#163]
I've been looking to utilise this project at work and love the ability to export to DOT graph. The library is just downright fantastic! I see there's been a bit of change in that area thanks to the awesome work done in PR #100 and #158, however there seems to be a bug when running the Telephone example and exporting to DOT.

This seems to have been introduced with the changes "Replacing InternalTransitionInfo and ExternalTransitionInfo with new class: FixedTransitionInfo" where StateInfo.cs was modified to iterate over all the items and looks for items of type **TransitioningTriggerBehaviour** or **InternalTriggerBehaviour**. The exception is thrown when the cast to **TransitioningTriggerBehaviour** is attempted on an item of type **InternalTriggerBehaviour** which is utilised within the Telephone example. I'm not sure how best to proceed since this a _fairly_ minor bug (I'm guessing since it hasn't cropped up yet), I've never performed a fix/pull request before, and not sure if it should/could just be added to the changeset of PR #158?

Thanks! :)

**Comment by nblumhardt** [comment]
Hey Johnathan, thanks for the report! Sounds like a bug - ideally we'd get the fix in through a targeted PR. Any help would be appreciated.

**Comment by HenningNT** [comment]
Looks like I tried to simplify too much, and OR'ed the two types together in a single foreach. I've split them out so that the code runs properly now :-)
