### ISSUE TITLE
No way to identify the transition used to change states

### ISSUE THREAD

**Issue by jsobell** [dotnet-state-machine/stateless#166]
At the moment we can have multiple PermitIf, so long as they are mutually exclusive, but I don't see any way to know which was in play when the guard was true.
In our state machine scenario we perform actions on transitions, so we either have to be able to add actions to a guarded transition (messy), or we have to use the `OnTransitioned` handler to look at the transition that was followed and act on that.
The issue at the moment is that there doesn't appear to be any way to know which transition was performed.  Sure, we can see the source and destination states, but when there are multiple transitions available between those states we don't know which it is.

Essentially, we need either an `OnTransition` raised by transitions, or the State's `OnEntry` has to be given something identifying the transition that went there. The current `OnTransitioned` is too late.
I would imagine we would also need an ID associated with the guarded transition. At the moment we have a description, but even that is not available.

Unless someone has another suggestion, how can an action be applied during the transitions below when we can't see which of these transitions was followed?

![image](https://cloud.githubusercontent.com/assets/834155/26182965/117c6902-3bbf-11e7-9afc-f0c25d66eed7.png)

**Comment by HenningNT** [comment]
I would configure the OnButtonPress handler in the OffHook state to examine the number dialled, and log the number if needed, then post the CallDialed trigger. I don't really see the need to know which trigger caused a transition. In fact, I don't think a state should need to "know" anything about the past, but that might just be me.

**Comment by jsobell** [comment]
I don't think any of that is relevant to this issue. You're suggesting every trigger call be prefixed with a check to see which guard would be met, and perform the action before the state machine is called? Doesn't that defeat the whole reason for using a state machine?

A state doesn't know anything about the past, but entering a state through a transition is not in the past, it's what is happening at that moment. `OnTransitioned` includes `source` and `destination`, and the transition is the path followed between them. The `trigger` is the thing that caused the transitions to be considered.

**Comment by HenningNT** [comment]
No, that's not what I was suggesting.
Let's say that we have a phone class that has a few public methods, including ButtonPress(). Each time a button is pressed, the ButtonPress method is called. This method places an buttonPress event in the message queue. The phone object has a timer that checks the queue every so often, and calls Fire on the sttae machine. The state machine is configured to handle each button press in the OffHook state. When a valid number has been identified the CallDialed can be posted to the queue. The same handler can also determine if logging should be enabled or not.

**Comment by jsobell** [comment]
I think you're getting bogged down in some sort of application coding suggestion. What you describe involves creating a structure outside of the workflow, and means code has to execute prior to raising an event.
This is a workflow solution, and the workflow controls all aspects and events. Knowing which transition was used is a common feature of workflows as many systems allow you to execute code on entry to a state based on the transition that the flow followed, not based on the trigger condition.

Take a look at the diagram below from [SMC](http://smc.sourceforge.net/). You'll see two direct links between 'Routing' and 'PlayingMessage' states, each with a different guard condition. Then you'll see an action `playEmergency()` on one, and `playInvalidNumber()` on another. These are actions executed at transition time, and not some queued task added before triggers occur.
At the moment there appears to be no way to implement this feature of a state engine in this library, because while I am notified that a transition from `Routing` to `PlayingMessage` occurred, I'm not told which of the transitions was used.

We currently use SMC to generate C# code, which we then compile into state machines, but it's all pretty horrible spawning a Java app to create the code, and the syntax is messy, hence why I'm looking at Stateless.

![image](https://cloud.githubusercontent.com/assets/834155/26208767/4766c07a-3c2e-11e7-988b-420869679823.png)

**Comment by betty-crokker** [comment]
@jsobell I have also been thinking about this, but for a slightly different reason.

I have a state machine that is parsing tokens, and depending on the state of the machine dealing with the tokens in different ways.  So I'm ending up with a lot of code like this:

Configure(State.A)
   .Permit(Trigger.M, State.B)
   .Permit(Trigger.N, State.B)
   .Permit(Trigger.P, State.B);
Configure(State.B)
   .OnEntryFrom(Trigger.M, () => gotMstateA());
   .OnEntryFrom(Trigger.N, () => gotNstateA());
   .OnEntryFrom(Trigger.P, () => gotPstateA());

I was imagining extending 'Permit' to take a function:

Configure(State.A)
   .Permit(Trigger.M, State.B, () => gotMstateA())
   .Permit(Trigger.N, State.B, () => gotNstateA())
   .Permit(Trigger.P, State.B, () => gotPstateA());
Configure(State.B);

I may play with this idea, and then extend it to your problem by adding a second function to the 'PermitIf':

PermitIf(Trigger.CallDialed, () => IsAdmin(), () => DisableLogging());
PermitIf(Trigger.CallDialed, () => !IsAdmin(), () => EnableLogging());

Would that work for what you're trying to accomplish?

p.s. the lambda syntax "() =>" may or may not be appropriate, I'm just using it in this post to make it clear I'm talking about method calls.

**Comment by betty-crokker** [comment]
See #167

**Comment by HenningNT** [comment]
If the object needs to be doing something special in the PlayingMessage state when the Emergency event is triggered, doesn't that mean that the object is in another state compared to when it wasn't not triggered? Could you not use either sub/superstates, or two distinct states to model this behaviour?

**Comment by jsobell** [comment]
No, that's an implementation assumption. You and I have no idea how or why states might be used, or the relationship between any object and any 'state' associated with it. Forcing intermediary states is wrong, and we're moving the flow logic definitions out of the workflow and into an underlying code implementation.

There is a very good reason why the feature of knowing which transition is occurring is supported in almost every state-machine workflow engine; because many solutions need it.

**Comment by nblumhardt** [comment]
Hey all, am I missing something, or are you just looking for `OnEntry(Action<Transition>)` @jsobell ?

https://github.com/dotnet-state-machine/stateless/blob/dev/src/Stateless/StateConfiguration.cs#L435

E.g.

```csharp
    .OnEntry(t => /* t is the Transition object here, with the info you're after */)
```

If not, can you please post a sketch of what the desired API should look like?

Thanks!

**Comment by jsobell** [comment]
Yes, but something critical is missing from Transition objects. It currently contains Source, Destination, and Trigger, but this does not provide a unique transition because we have guard conditions.
I've given an example here: https://github.com/dotnet-state-machine/stateless/issues/167#issuecomment-303720773

**Comment by jsobell** [comment]
The question is how to allow the developer to identify a transition. If we weren't pushing fluent syntax we could use instances (although they are non-serialisable) and pass a reference to the `GuardCondition` (messy), but in absence of that each transition needs some form of identifier. In theory we could simply use the description, as the only things that can possibly differentiate two transitions at the moment are the guard condition or the description, and the guard condition is code.
The current implication assumes that there will only be need for a single path between any two states per trigger, but it allows (quite rightly) multiple paths.
What it doesn't provide (which is the issue) is any means of knowing which of those multiple transitions is in play, because the key [source,destination,trigger] is not unique and not sufficient.

The million-dollar question is how you allow identification of each transition. Description shouldn't be used because it's not intended for metadata, so should it be a string, an integer, or a user-definable datatype.

Note that this only applies to `PermitIf`, because `Permit` statements must be mutually exclusive, so the `Transition` object's three properties uniquely identify them.

**Comment by jsobell** [comment]
> If not, can you please post a sketch of what the desired API should look like?
Good question!
Do we have `StateMachine<TState, TTrigger, TIdentifier>` to allow definition of the data to be passed into `PermitIf`s?
Do we simply allow an `object` as an identifier on `PermitIf`, or better still allow a fluent `.As()` to assign any object or action to the `GuardAction`, and ensure that's made available in the `Transition` object in the callbacks.

**Comment by betty-crokker** [comment]
Also take a look at #167 which is basically the same problem, with some different ideas for solving it.

**Comment by jsobell** [comment]
This is like being in the Twilight Zone... or is it Groundhog day? :)

**Comment by HenningNT** [comment]
One "solution" would be to NOT allow a trigger to be used in multiple PermitIf/Permit to transition to the same destination state. Uniqueness would then be guaranteed.

**Comment by jsobell** [comment]
Not being able to identify a guarded transaction is like having a keyboard handler that doesn't know whether the shift, control, or alt key was pressed in conjunction with the [A] key.

The solution to that problem is not to remove the keyboard handler. The solution is to find a way passing out the additional information.

**Comment by betty-crokker** [comment]
See PR #173 "Add options to triggers"

**Comment by HenningNT** [comment]
@jsobell , that is an excellent example of orthogonal regions.
State machines model something, and we want to be able to visualize the model. This usually means that the model is two-dimensional. To model a keyboard wo would need at least tree dimensions (Scroll Lock, Num Lock and Caps lock) and adding even more if we model Alt, Ctrl and Shift.
This makes it hard to model, so what we do instead is model the most important states, and  introduce extended state variables to keep track of the rest.
To solve your problem you have a few options, either re-design the state machine model so that all transitions are identifiable, or introduce extended state variables to keep track of what has happened before. Or maybe both.

**Comment by jsobell** [comment]
Again, you're being too literal. You don't know if or why we might need the supporting information, so you can't say they are orthogonal.
You seem to be trying to justify not fully supporting multiple guard statements, but it's an irrelevant argument because they are often needed, and hence are supported in most (if not every) state machine workflow system.
Re your two options, neither are realistic. The first is not possible as it is the crux of this whole discussion, and the second is unacceptable because it's not stateless.

Let's move on, because @betty-crokker has already submitted a solution: #173

**Comment by HenningNT** [comment]
I'm trying prevent adding more functions to the API that are not really needed. We can add tags, but it isn't really necessary.

What I find interesting about developing software is that most (if not all) software problems can be solved 
in more ways than one. You seems to be locked in a single solution to your problem. Take a step back and consider your problem gain. Are there really only one possible solution? I'm confident you can find a way to work around the limitations of stateless.

**Comment by jsobell** [comment]
Good point, and it's always worth stopping and thinking.
In this case I'm not locked to one solution, it's just that nobody has suggested an alternative that meets the common usage scenario. In an ideal world we would only have actions on entering or leaving states, as that makes the initialisation and cleanup nice and simple, but one of the intentions of the FSM is to avoid stateful data, and while guard conditions are far from ideal, they are the standard for simplification of diagrams.

A state machine on its own is awesome, but once we bring in the humans (what we refer to as "requirements") we have issues. It's great to be able to say "I don't care about the past, just tell me where you are now", but in the real world we sometimes users want to know how they go there. Not just where they came from, but the route they took.

We have this as a specific requirement. 
If a user goes from "Initial" to "Registered" via an SMS containing "REG" then we send them back an SMS thanking them.
If a user goes from "Initial" to "Registered" via an SMS containing "Q" then we send them back an SMS acknowledging the status, and we record todays date in their profile.
If a user goes from "Initial" to "Registered" via an SMS containing "Q 1 Jan 2018" then we send them back an SMS acknowledging the status, and we record that date in their profile.

Now all of these are identical start and end states. We can argue that we need a unique event for each transition, but what might that be? The event has to be a function, because "REG" and "Q" are simple, but "Q 23 Feb 2019" needs special processing.
In all of these cases we end up with the trigger being "SMS", and the message being an additional parameter, which is used by the guard to decide the appropriate actions (or would be if #155 was implemented!).
Add to that the fact that the workflow is generated dynamically based on the users drawing a flow-chart, and the users need to be able to visualise the chart with a red line showing the last transition...

I'm sure you get the idea :)  I'm not trying to be single minded, I'm just pushing back when it's suggested we tell our users to try some convoluted or unworkable alternative instead of addressing a problem that's already been resolved by most other state-machine compilers.

**Comment by nblumhardt** [comment]
@jsobell thanks for all the input. I think we should pause here, though (I appreciate the exploration in #173, @betty-crokker, but we should get some agreement on the direction first).

The flag being raise here is that this project has been ongoing for 10 years without the tags requirement being raised. It can be frustrating when you hit a blocker like this, but from the project perspective we can't afford to add every option for every use case. @HenningNT has been guiding a lot of our API and underlying model refinement over the last few years and I think is asking the right questions. If, over the 10 years of development, we added every option suggested (and every twist on the API) I don't think anyone would be using the project right now - the use cases are so broad we'd be dealing with a real monster :-).

Here's the goals heading from the [README](https://github.com/dotnet-state-machine/stateless):

> Project Goals
> This page is an almost-complete description of Stateless, and **its explicit aim is to remain minimal**.

I don't think this wall-of-text discussion is the way to go on this feature, and I don't think it warrants a change in the overall configuration syntax just now, although the direction is really interesting. @jsobell my suggestion would be to fork Stateless to your own repository, and do the minimal thing required to get your scenario working. I.e. just add an optional `tag:` argument to the overloads of `PermitIf()` you are using, and see how it goes. In the process you may find a better way to enable the concept in Stateless, which we can all benefit from as feedback.

@betty-crokker there's a lot of change still to stabilize in 4.0; I'd rather not adopt the additional configuration syntax in this release. Along with closing this thread, I'd like to close #173 for the time being and focus on stabilizing the current work-in-progress. We can definitely look at it further down the track, if you want to keep the branch alive, but for now just finishing, testing, documenting and releasing 4.0 seems like it will consume quite a bit more time yet.

Does this make sense, and give everyone a way of moving forward?

**Comment by jsobell** [comment]
Sure, that's fine. The Tag issue is something that probably hasn't been exposed because people aren't using Guards and the events. I'm not convinced that missing event data is the same as being 'minimalist', but as you say we can fix it in a fork.

**Comment by betty-crokker** [comment]
@nblumhardt I'm OK with moving #173 (and thus #166 and #167) into the "future consideration" bucket.

Can you add an issue for "what needs to be finished in order to call 4.0 complete"?

**Comment by nblumhardt** [comment]
@betty-crokker I'm due to review what's outstanding on #143 - I'll try to make that one the "master list" :-) 👍
