### ISSUE TITLE
Online designer

### ISSUE THREAD

**Issue by fatroze2000** [dotnet-state-machine/stateless#171]
Hi
How can I design it in drag & drop mode at runtime?
I've used [stateless-design](https://github.com/nblumhardt/stateless) but it's used via XML which generate C# class.

**Comment by nblumhardt** [comment]
Hi Yaser, thanks for getting in touch.

To answer both this and your other question #171, Stateless is a lower-level component than these concerns (design, persistence). It's more akin to `System.Collections.Generic.List<T>` - you can build a GUI designer for lists of items, and write code to load/save them, but it's not part of the `List<>` class itself.

One thing you might find handy, if you decide to pursue an implementation, is that Stateless works with a variety of types representing the states and triggers. `StateMachine<string, string>` is probably the best option if you want to configure it based on some kind of stored data.

Hope this helps,
Nick

**Comment by fatroze2000** [comment]
Thank you.
But to import & export state machine at runtime, how can I do that?
In WWF it used **DynamicActivity**. What about stateless?

**Comment by ArturKarbone** [comment]
@fatroze2000 you can export your to DotGraph format:
```
phoneCall.Configure(State.OffHook)
    .PermitIf(Trigger.CallDialled, State.Ringing, IsValidNumber);
    
string graph = phoneCall.ToDotGraph()
```
And visualize it here http://www.webgraphviz.com/.

See more details on README.md.

**Comment by HenningNT** [comment]
Take a look at #104, there an suggestion how to use JSON to save and restore the state.
It's only necessary to store the state and enough information to restore an object, one does not have to write the binary object itself to XML.
