### ISSUE TITLE
What does it mean to Activate or Deactivate a state?

### ISSUE THREAD

**Issue by betty-crokker** [dotnet-state-machine/stateless#174]
Does Activate == Entry, and Deactivate == Exit?  Are they just archaic terms for the same things, for backward compatibility?  If not, can we add a tiny bit to the Readme.md to explain this?

**Comment by nblumhardt** [comment]
Hi Chris,

These are for persistence purposes (Orleans actors were the original motivating case); some more info in: https://nblumhardt.com/2016/11/stateless-30/

HTH!

**Comment by HenningNT** [comment]
You can find a bit more information in PR #91

**Comment by nblumhardt** [comment]
(Assuming this one's answered.)
