### ISSUE TITLE
Allow IEquatable states and triggers

### ISSUE THREAD

**Issue by maiorfi** [dotnet-state-machine/stateless#18]
Hi.

If State and Trigger types aren't "primitive"/"scalar" types, but POCO classes, StateMachine model doesn't work at all!

Any suggestions?

Thanks.

**Comment by nkanani** [comment]
I have seen this work for my custom class - I just needed to implement IEquatable.Equals and override Object.Equals, Object.GetHashCode()

**Comment by psibernetic** [comment]
This may have been resolved in the time between now and opening of the issue, but I was able to do this fine. 

Reference code:
https://github.com/psibernetic/REstate/blob/master/src/REstate/State.cs

**Comment by psibernetic** [comment]
@nblumhardt I recommend closing this issue.

**Comment by nblumhardt** [comment]
Sounds like a good idea @psibernetic
