### ISSUE TITLE
Firing triggers from different events

### ISSUE THREAD

**Issue by mjgalindo** [dotnet-state-machine/stateless#181]
Hi, I'm developing an application that has some interaction with the user. Everything is handled with states.
So far, I've ported a single part of the application (imagine a mini-game in which you have to touch something on screen before the time runs out). 

Some states permit two triggers to exit, one would use the touch screen or a key and the other would be controlled by a timer that is started OnEntry.

```C#
stateMachine.Configure(State.StateX)
    .OnEntry(t => startStateXTimeout())
    .Permit(Trigger.StateXTimeout, State.StateY)
    .Permit(Trigger.EscKeyPressed, State.EndingState);
...
private void startStateXTimeout()
{
    Task.Delay(delayms).ContinueWith(t => stateMachine.Fire(Trigger.StateXTimeout));
}
```

So far it seems to be working fine, but I'm worried whether firing triggers from different threads may pose any issues in the future.

**Comment by HenningNT** [comment]
Allowing other object to manipulate the state directly can lead to serious and/or confusing problems. I recommend implementing a queue which other object can post events to, instead of allowing access to Fire() directly. So each object can have its own internal state machine, protected from the outside. Dr. Dobbs has some inspiration:
http://www.drdobbs.com/parallel/prefer-using-active-objects-instead-of-n/225700095

**Comment by mjgalindo** [comment]
I've kept on reading about the topic and found that to use different threads the access should be locked. 
So, how about instead of accessing Fire() directly I do it like this in my WPF application:

```c#
private void safeFire(Trigger t)
{
    lock (_stateMachineLock)
    {
         Dispatcher.BeginInvoke(new MethodInvoker(() => { stateMachine.Fire(t); }));
    }
}
```
I understand that the dispatcher will run all actions in the correct order so this way only the main UI thread should be accessing the state machine and therefore it should be safe to use, right?

**Comment by HenningNT** [comment]
No, there's really no need to use locking if you use active objects and asynchronous messaging.
