### ISSUE TITLE
Is there any visual editor for stateless?

### ISSUE THREAD

**Issue by wavebit** [dotnet-state-machine/stateless#183]
Hello,
If there are many states and transitions the code will become very complex and hard to modify, so is there a visual editor for stateless?
Thanks!

**Comment by HenningNT** [comment]
Not to my knowledge. Maybe someone else knows about one?

**Comment by nblumhardt** [comment]
https://marketplace.visualstudio.com/items?itemName=mfrederiksen.StatelessDesigner

https://channel9.msdn.com/coding4fun/blog/Putting-a-friendly-face-on-statelessness-the-Stateless-Designer-Visual-Studio-Extension

Haven't tried it personally, keen to hear how you go!

**Comment by wavebit** [comment]
In StatelessDesigner, I deleted some state from the stateless file, but the generated state code was still there.

**Comment by yaoyiqun** [comment]
@wavebit Generate code will triggered by save
