### ISSUE TITLE
Why Permit() has no transition action?

### ISSUE THREAD

**Issue by wavebit** [dotnet-state-machine/stateless#184]
Hello,
I think the API looks like this:
sm.Configure(stateA)
     .Permit(triggerB, stateB, actionAB) // If we delete this transition, the actionAB is deleted together.
     .Permit(triggerC, stateC, actionAC);

is more clear than below:

sm.Configure(stateA)
     .Permit(triggerB, stateB) // If we delete this transition, we have to search the associated action somewhere in the code. 
     .Permit(triggerC, stateC);

sm.Configure(stateB)
    .OnEntryFrom(stateA, actionAB); // ReSharper still show that actionAB() is still referenced.

sm.Configure(stateC)
     .OnEntryFrom(stateA, actionAC);

**Comment by HenningNT** [comment]
The option to add an action to a transition is currently missing from the API, so I'm afraid you'll have to work around that limitation.

This feature will most likely be added "soon", as there has been several requests for this.

**Comment by jsobell** [comment]
For the time being you can use https://github.com/appccelerate/statemachine
It supports it using this syntax:
```
fsm.In(State.A).On(Events.SMS).If<string>(a => a=="DOTHIS").Goto(State.B).Execute<string>(e => LogTransition($"Went from A-B with parameter {e}"));
```
