### ISSUE TITLE
Ability to set initial substate for superstates

### ISSUE THREAD

**Issue by JackUkleja** [dotnet-state-machine/stateless#185]
It's great to see that Stateless supports hierarchically nested states, but as far as I can tell it seems to be missing a way to set the initial substate for any given super-state. Typically in state machine notations there is a way to define what the entry state is for any given [sub]state. We have that for the top-level state via the `StateMachine` ctor `initialState` parameter, but the concept seems to be missing from that point on.

In lieu of that feature is there is suggested best-way accomplish this?

**Comment by JackUkleja** [comment]
Here is the current hack I have to do:

```
   _stateMachine.Configure(TemperatureControlState.Automatic)
                .OnEntry(() => _stateMachine.Fire(TemperatureControlTrigger.InternalStart))
                .Permit(TemperatureControlTrigger.InternalStart, TemperatureControlState.NotHeating)
                         .Permit(TemperatureControlTrigger.Stop, TemperatureControlState.Manual);
```

where `TemperatureControlState.NotHeating` is the initials substate of the` Automatic`.

**Comment by HenningNT** [comment]
I'm afraid stateless doesn't support this. If you know which sub state are needed then set up the transition to that. If not, I think your hack looks excellent!

**Comment by gerardog** [comment]
+1 vote that there should be a built-in way to do this without the hack.
