### ISSUE TITLE
Reconfigure state ability

### ISSUE THREAD

**Issue by acasciani** [dotnet-state-machine/stateless#187]
Is there (or can there be added) a method to Reconfigure a state that has already been created? The use for this would be if you extend a state machine implementation that already configures states (in the base class) and you need to completely change the behavior of the state in the subclass. Example:

**BaseClass.cs:**
machine.Configure(State.A).Permit(Trigger.Forward, Step.B);
**SubsetClass.cs : BaseClass.cs**
machine.Configure(State.A).Permit(Trigger.Forward, Step.C);

This will not work as there would technically be multiple transitions when the SubsetClass is configuring State.A. What I'm proposing is something like the following in StateMachine.cs:

```
public StateConfiguration Reconfigure(TState state)
{
    if (_stateConfiguration.ContainsKey(state))
        {
            _stateConfiguration.Remove(state);
        }
        return Configure(state);
    }
}
```

You then have:

**BaseClass.cs:**
machine.Configure(State.A).Permit(Trigger.Forward, Step.B);
**SubsetClass.cs : BaseClass.cs**
machine.Reconfigure(State.A).Permit(Trigger.Forward, Step.C);

Thoughts?

**Comment by nblumhardt** [comment]
Hi @acasciani - thanks for sharing your thoughts.

This can be achieved today by simply creating a new state machine with the modification in place. Check out the constructor of `StateMachine` that accepts delegates - when the state is stored externally, a new machine can be created pointing to the existing state and everything will work as expected.

Does this cover the case you have in mind here?

**Comment by acasciani** [comment]
Hi @nblumhardt, not really but that's okay. I'm pulling the project in; I should just be able to add the functionality I need since it is a partial class. I wouldn't say this is a bug, just a thought for the future! Thanks for the work!

**Comment by nblumhardt** [comment]
Thanks @acasciani - closing for now, but please get in touch if you need further help with it.
