### ISSUE TITLE
Shouldn't Reentry fire OnEntry from substate?

### ISSUE THREAD

**Issue by dpavlenkov** [dotnet-state-machine/stateless#191]
`

        [Fact]
        public void IfSelfTransitionPermited_ActionsFire_InSubstate()
        {
            var sm = new StateMachine<State, Trigger>(State.A);

            bool fired = false;

            sm.Configure(State.B)
                .OnEntry(t => fired = true)
                .PermitReentry(Trigger.X);

            sm.Configure(State.A)
                .SubstateOf(State.B);

            sm.Fire(Trigger.X);

            Assert.Equal(State.B, sm.State); // Ok
            Assert.True(fired);              // Fail
        }
`

**Comment by nblumhardt** [comment]
Thanks for the note; it appears to me that it should.

**Comment by HenningNT** [comment]
Extending the test a bit further reveals that OnExit isn't called either...
        [Fact]
        public void IfSelfTransitionPermited_ActionsFire_InSubstate()
        {
            var sm = new StateMachine<State, Trigger>(State.A);

            bool onEntryStateBfired = false;
            bool onExitStateBfired = false;
            bool onExitStateAfired = false;

            sm.Configure(State.B)
                .OnEntry(t => onEntryStateBfired = true)
                .PermitReentry(Trigger.X)
                .OnExit(t => onExitStateBfired = true);

            sm.Configure(State.A)
                .SubstateOf(State.B)
                .OnExit(t => onExitStateAfired = true);

            sm.Fire(Trigger.X);

            Assert.Equal(State.B, sm.State); // Ok
            Assert.True(onEntryStateBfired);              // Fail
            Assert.True(onExitStateBfired);              // Fail
            Assert.True(onExitStateAfired);              // True
        }

**Comment by HenningNT** [comment]
This also doesn't work properly:

        [Fact]
        public void FromSubstateToAnotherSubstae()
        {
            var sm = new StateMachine<State, Trigger>(State.A);

            bool onEntryStateDfired = false;
            bool onEntryStateCfired = false;
            bool onExitStateBfired = false;
            bool onExitStateAfired = false;

            sm.Configure(State.B)
                .OnExit(t => onExitStateBfired = true);

            sm.Configure(State.A)
                .SubstateOf(State.B)
                .Permit(Trigger.X, State.D)
                .OnExit(t => onExitStateAfired = true);

            sm.Configure(State.D)
                .OnEntry(t => onEntryStateDfired = true);

            sm.Configure(State.C)
                .SubstateOf(State.D)
                .OnEntry(t => onEntryStateCfired = true);

            sm.Fire(Trigger.X);

            Assert.Equal(State.D, sm.State); // Ok
            Assert.True(onEntryStateDfired);              // True
            Assert.True(onEntryStateCfired);              // Fail
            Assert.True(onExitStateBfired);              // True
            Assert.True(onExitStateAfired);              // True
        }

**Comment by DanielHutt** [comment]
Confirmed that I run into this on the latest release. When my state machine is in a sub-state and fires a trigger into a super-state, the OnEntry is not called.

**Comment by HenningNT** [comment]
I think I have a fix for this, please review PR #198.

**Comment by HenningNT** [comment]
A fix was merged in that fixed this, so I'm closing this.

**Comment by Arweenius** [comment]
When Trigger X is fired, It will run OnExit and then OnEntry after Changing from substate A to B.
Do you really want OnExit from Mainstate B fired when you leave the substate ?
