### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mikefonted** [dotnet-state-machine/stateless#193]
I have a project using Stateless (v3.1.0) and everything seemed fine until I have checked the application performance (a key point). It seems that Stateless is using, IMHO, too much CPU firing transition from the current state, as you can see in this capture (just a piece of code):
![fsm fire_cpuusage](https://user-images.githubusercontent.com/6642583/30157894-c730eb2c-93c3-11e7-91cf-3539ae2b5aa2.png)

The line is hit aprox 100000 times in a minute (an avg of 1700 hits/sec).
Do you consider this CPU usage as normal?

**Comment by nblumhardt** [comment]
Hey Mike! Thanks for the note.

Stateless is designed primarily as a workflow tool (although I've seen it used for various parsing tasks, too). I wouldn't be surprised if the performance is below what you'd expect in this kind of setting.

Stateless was also originally written in the days of "allocatey" .NET, so there are probably low-hanging fruit to remove allocations and generally modernise the approach to performance a bit. If you're keen to dig in and optimise, help along those lines would be welcome.

Cheers!
Nick
