### ISSUE TITLE
Question: Not thread-safe, how is that shown in code?

### ISSUE THREAD

**Issue by bhaidar** [dotnet-state-machine/stateless#195]
Hello,
I read a note on the home page of this repo that Stateless is not threadsafe. How come it is not? I mean if there are 2 threads each having its own StateMachine, why would there be any issues with multithreading?

NOTE: I am delving more into multithreading now.

**Comment by HenningNT** [comment]
It means that any object with a reference to the state machine object can call its public methods or change the public properties, and those methods directly change the state machine object internal state. There is no protection against that happening in Stateless.

I prefer to expose only public methods that allows other objects to post message in a queue (and return immediately). The queue is emptied by a private timer running owned by the object.

**Comment by bhaidar** [comment]
Thanks @HenningNT 

Let's assume I wrapped the StateMachine by an object. Then I exposed few methods on this wrapper object. Code outside would interact with those public methods which will internally call "Fire" for instance on the StateMachine. How is that "not thread-safe"? Maybe I am missing a gap here.

> I prefer to expose only public methods that allows other objects to post message in a queue (and return immediately). The queue is emptied by a private timer running owned by the object.

Can you share a sample code? I read this note for you somewhere else, but I am not sure how would that look like in terms of code and usage for the code.

Appreciate your assistance.

**Comment by HenningNT** [comment]
By wrapping the state machine you can make it thread safe, by guarding access to the object internal state.

**Comment by bhaidar** [comment]
@HenningNT Thanks :-) 
I am reading more on other issues and noticed that you always mention Active Objects / Queue / Timer. I do understand you might not be able to share the code, but can you guide me to an online resource that talks about Active Object / Queue / Timer in c#? I can re-create something close.

**Comment by bhaidar** [comment]
@HenningNT 
I've started working on a new Object wrapper. On the right way?

````
        public virtual AssignmentState State { get; set; }

        public Assignment()
        {
            this.State = AssignmentState.Open;

            _tickTimer = new System.Timers.Timer();
            _tickTimer.Interval = 60000; // 1 min
            _tickTimer.Enabled = true;
            _tickTimer.Elapsed += TickTimerCallback;
            _tickTimer.Start();

            _machine = new StateMachine<AssignmentState, AssignmentTrigger>(() => State, s => State = s);

            _assignToMemberTrigger = _machine.SetTriggerParameters<Assignment>(AssignmentTrigger.AssignToMember);
            _assignToCoordinatorTrigger = _machine.SetTriggerParameters<Assignment>(AssignmentTrigger.AssignToCoordinator);
            _completeTrigger = _machine.SetTriggerParameters<Assignment>(AssignmentTrigger.Complete);
            _cancelTrigger = _machine.SetTriggerParameters<Assignment>(AssignmentTrigger.Cancel);


        }

        private void ProcessTrigger(QueuedTrigger trigger)
        {
            _machine.Fire(trigger.Trigger, trigger.Args);
        }

        private void TickTimerCallback(object sender, System.Timers.ElapsedEventArgs e)
        {
            while (this._eventQueue.TryDequeue(out QueuedTrigger trigger))
            {
                ProcessTrigger(trigger);
            }
        }

        private StateMachine<AssignmentState, AssignmentTrigger> _machine;
        private StateMachine<AssignmentState, AssignmentTrigger>.TriggerWithParameters<Assignment> _assignToMemberTrigger;
        private StateMachine<AssignmentState, AssignmentTrigger>.TriggerWithParameters<Assignment> _assignToCoordinatorTrigger;
        private StateMachine<AssignmentState, AssignmentTrigger>.TriggerWithParameters<Assignment> _completeTrigger;
        private StateMachine<AssignmentState, AssignmentTrigger>.TriggerWithParameters<Assignment> _cancelTrigger;

        Thread _syncThread = null;
        readonly System.Timers.Timer _tickTimer;
        readonly ConcurrentQueue<QueuedTrigger> _eventQueue = new ConcurrentQueue<QueuedTrigger>();


        private class QueuedTrigger
        {
            public StateMachine<AssignmentState, AssignmentTrigger>.TriggerWithParameters<Assignment> Trigger { get; set; }
            public object[] Args { get; set; }
        }
````

**Comment by HenningNT** [comment]
Looks like a good start! I guess you want to make the AssignmentState setter private?

The next step is to add public methods that creates new QueuedTriggers and inserts them into the queue. Keeping the queue private is part of the thread-safety.

If you want to be able to unit test this (why wouldn't you) you should read this:
https://stackoverflow.com/questions/11495830/unit-testing-a-class-that-uses-a-timer
By providing the class with an ITimer or IScheduler or somthing that keeps track of time, you can control and test that your object executes triggers and does the transitions.

As a side note, I ended up extending ConcurrentQueue to be able to support LIFO posting as well as the ordinary FIFO.

**Comment by bhaidar** [comment]
Hi @HenningNT 
Thanks for your feedback. I will check the link you mentioned.
Mind you that I am building a Web App and not a WPF/Windows one. So is it ok to utilize such a timer? 

Also, one thing, how am I protecting and make my code thread-safe in this way?

Thanks

**Comment by HenningNT** [comment]
I haven't done any web App development, so I'm afraid you have to look into what Timers you have available yourself.

your making your objects more thread safe by not allowing any external object modify the internal state. Consider if an elevator controller object checked its state, and found it was possible to open the doors. At the same time another object tells the controller to start moving up. That would be bad ;-)

**Comment by nblumhardt** [comment]
Closing as I don't think there's much we can add here.
