### ISSUE TITLE
How to reuse state machine?

### ISSUE THREAD

**Issue by wizicer** [dotnet-state-machine/stateless#196]
I have a lots of states want to know their permitted operation. Currently I need to re-configure state machine for each state and get out the permitted operation, indeed they are same state machine, only difference are the data feeding to it.
So, want to know how to reuse the configured state machine. (I just presumed the read-only state property is by design)

PS: I already aware of Issue #104 which guide us to reconstruct state machine. But I want to reuse state machine which could gain much performance improvements.

**Comment by nblumhardt** [comment]
The constructor of `StateMachine` that accepts two delegates (state accessor and state mutator) can be used for this. Hook the delegates up to point to a "current state" variable, and set the variable before querying available transition. HTH!

**Comment by wizicer** [comment]
Brilliant design!

Previously, I just thought that constructor API is for initial value and final value, didn't try to use this way. Thanks again!

**Comment by nblumhardt** [comment]
Great, glad it helps 👍
