### ISSUE TITLE
Expose state graph

### ISSUE THREAD

**Issue by alprema** [dotnet-state-machine/stateless#197]
Hi,

We use `ToDotGraph()` for debugging purposes, but we'd like to get the list of states between two states programmatically (and parsing the output of `ToDotGraph()` seems a bit overkill).
Would it make sense to have a method that exposes the graph in a code-friendly manner ? (If so we'd happily make a PR for it).

Thanks,

Kévin

**Comment by HenningNT** [comment]
Seems like a good idea.
The UmlDotGraph bits should probably be moved into its own folder under Graph, and each exporter/formatter can live in its own folder. So if someone wants a JSON exporter, they can create a new folder under Graph.

What sort of output are you considering, and how would it be consumed?

**Comment by alprema** [comment]
I'm considering a simple POCO output, something like this:
``` csharp
public class State {
    public TState Value { get; }
    public IEnumerable<KVP<TTrigger, State>> { get; }
}
```
The goal is to consume it from our code, to compute the "route" between two given states.

**Comment by alprema** [comment]
Nevermind, it seems that the `GetInfo()` method exposes exactly what I need, I was not using the latest version, my bad.
