### ISSUE TITLE
Stepping back from this project - help wanted

### ISSUE THREAD

**Issue by nblumhardt** [dotnet-state-machine/stateless#199]
Hello, all!

Stateless is still one of my favorite libraries, but since it's not used in any of the applications I spend my days on, I'm no longer a good custodian of the project. It's time for me to hand the reigns to others with more head space, inspiration and new ideas.

My time for this project has been very limited over the past year, and I think that shows in the slow turnaround on issues and PRs. While waiting for my input, I think we're at risk of losing valuable new contributions, and while I _should_ be doing it, but am not, we're also neglecting the kind of refactoring and maintenance necessary for keeping the codebase clean and modern.

The @dotnet-state-machine/reviewers team already have full commit access and my support in taking this project forwards.

If you're on that team, or a recent Stateless contributor, and would be willing to take custodianship of the build account, NuGet publishing, and project admin rights, please email me privately - nblumhardt@nblumhardt.com - ideally we'd share this among a few maintainers, but it's definitely not a huge burden.

I'll still be lurking here, and will do my best to respond to `@` mentions, but _thanks for all the fish_ :-)

**Comment by HenningNT** [comment]
I'd like to be able to say that I could take over, but since I do most of Stateless work while working I'm afraid that there might be legal difficulties :-D
I'll have a chat with my boss in any case.

**Comment by JeremyCade** [comment]
@nblumhardt Happy to step in and attempt to fill the void.

**Comment by nblumhardt** [comment]
Thanks, Jeremy 🎩 - invitation sent.
