### ISSUE TITLE
Store and load states with ORM

### ISSUE THREAD

**Issue by sadeghhp** [dotnet-state-machine/stateless#201]
Hi, 
I think this is not clear how to store and load entity states with ORM .
it is useful to have a sample of storing and loading and initiating state machine with stored data.

**Comment by HenningNT** [comment]
This comes up now and again, so I think it's time to add an example :-)

I'll create a example on creating from a JSON string. I guess that the same technique can be applied to other sorts of storage.

**Comment by HenningNT** [comment]
@sadeghhp  Could you have a look at the example I added in my repository? Does it help at all?

**Comment by sadeghhp** [comment]
awesome!
thank you ;)
could you please move it to example folder?

**Comment by HenningNT** [comment]
Already done, just pull in the latest changes to the dev branch :-)
