### ISSUE TITLE
ToDotGraph is not exist

### ISSUE THREAD

**Issue by knopa** [dotnet-state-machine/stateless#204]
In latest nuget package 4.0.0 that method is missing.
Found a workaround, but it's not good to broke compatibility

`UmlDotGraph.Format(_machine.GetInfo())`

**Comment by HenningNT** [comment]
I believe that is the new way of doing this. Rather than depending on dot graph directly, we can use various formatters that accepts StateMachineInfo.

**Comment by anaximander23** [comment]
If this method no longer exists, could the documentation be updated to reflect this? I just spent ten minutes trying to work out why `.ToDotGraph()` didn't seem to be in scope when the readme said it should be.

**Comment by optical** [comment]
:+1: just spent 10 minutes cloning the solution trying to work out where the method was hiding.

**Comment by HenningNT** [comment]
Documentation updated!
