### ISSUE TITLE
Async implementation choices

### ISSUE THREAD

**Issue by smartcaveman** [dotnet-state-machine/stateless#209]
I really like this library.  I like it so much that I've used it enough to run into frustrating situations with the async implementation with respect to composition and consistency:

1.  The async APIs do not support cancellation.  This limits how well Stateless can coordinate with external events in a system.

2.  The async APIs do not `ConfigureAwait`.  This limits the usefulness of Stateless state machines in some contexts because additional work is required to prevent deadlocks and unresponsive UIs.  

3.  `Fire` and `FireAsync` do not process events consistently with each other.  It's possible to run synchronous actions asynchronously (e.g. `Task.Run(...)`) and asynchronous actions synchronously (e.g. `task.Result`/`task.Wait()`).  Given that the formal semantics of an FSM do not consider concurrency, my initial expectation was for Stateless to coalesce the synchronous and asynchronous behavior.  Stateless will run synchronous callbacks asynchronously.  However, the converse call causes an error.
 So, it's impossible to synchronously fire a trigger with registered async handlers, and there's this counterintuitive situation where a client could run `if(machine.CanFire(trigger)){ machine.Fire(trigger); }` and get an `InvalidOperationException`.  

4.  At least this one is documented, but Stateless state machines are not thread-safe.  This limits how effectively Stateless can be leveraged in a system that demands concurrency.

I'm happy to assist with resolving any or all of these issues.  However, I'm aware that these issues could just as easily be caused by a design choice as by oversight.  So, my questions with respect to each issue are:

1.  Why does Stateless do it this way?
2.  Should Stateless continue to do it this way?

**Comment by smartcaveman** [comment]
@HenningNT @nblumhardt

**Comment by nblumhardt** [comment]
Howdy!

1. Cancellation support would be a great addition 👍 
2. Adding `ConfigureAwait()` would be a good bug-fix 👍 
3. This is a tough design space - `InvalidOperationException` seems like the best by-design option we have, for this one - I'm also okay with the asymmetry, the asymmetry is there in all C# that makes use of async
4. Stateless isn't designed to be used from multiple threads; it's not possible to make the current design thread-safe without the possibility of introducing deadlock foot-guns; concurrent state machine design is an interesting problem, might be better explored in a new library

HTH, and thanks for the input! :-)

**Comment by smartcaveman** [comment]
@nblumhardt - re #3, what do you think of a configuration setting

**Comment by smartcaveman** [comment]
I can help with #1 and #2 if there are no one else is already working on it.

@nblumhardt 
Re #3, I see how you'd get here given that a sync call might be ambiguous between a non-blocking/fire-and-forget behavior or a blocking behavior.  I think it might be worth considering as a configuration setting, but I really appreciate how minimal the stateless API is, so maybe it wouldn't be worthwhile

Re #4, I can imagine ways to do this (my first idea would be to encapsulate the fsm with an actor that queues requests and processes synchronously), but I'd agree that it's probably good judgment to keep stateless's scope more limited.

**Comment by nblumhardt** [comment]
@smartcaveman thanks for the reply! [I've stepped away from this project](https://github.com/dotnet-state-machine/stateless/issues/199), but I would guess that help with 1 and 2 will be appreciated. Cheers!

**Comment by pdinnissen** [comment]
I have submitted a pull request for the ConfigureAwait(false) #222.  Implementing cancellation should probably be done in a separate PR.  I'll submit a PR for that in a few days.

**Comment by HenningNT** [comment]
@pdinnissen do you still want to do anything with the cancellation issue, or can I close this? The code has changed a bit since November...

**Comment by pdinnissen** [comment]
Sorry, I got side tracked in the past the few months.  But I have a new project requiring this library so I will do this change as well.  Please give me a couple more weeks.

Sent from my Windows 10 phone

**Comment by HenningNT** [comment]
Awesome, I look forward to it!

**Comment by smartcaveman** [comment]
@pdinnissen you still planning on doing this one in the near future?

**Comment by pdinnissen** [comment]
I really haven't had the time I though I would.  Go ahead and close.  If I
ever get the chance I put in a pull request.

**Comment by RehanSaeed** [comment]
I'm interested in finding out if there are any concurrent statemachines in the C# space.

**Comment by HenningNT** [comment]
@RehanSaeed It is expected that you put the state machine in class, and make it more thread safe that way.
I have an example here:
https://github.com/HenningNT/ThreadSafeStateless

I haven't really tested it yet in anger, but I think it should work.
