### ISSUE TITLE
Visualization API is not extensible

### ISSUE THREAD

**Issue by smartcaveman** [dotnet-state-machine/stateless#210]
Even though Stateless has a built-in diagram generator, I never get to use it.  Instead, I end up having to write a custom implementation to generate DOT syntax for graphviz from the `Stateless.Reflection` objects (or call Stateless internals with reflection).  

Here's why:

1.  `StateGraph` is internal, so the only way to generate the DOT syntax from the current implementation is to call  `UmlDotGraph.Format`.

2.  `UmlDotGraph.Format` does not provide any way to customize the structure or style of the DOT output.  Even though `IGraphStyle` is public, there is no public API that parameterizes the graph style.  A new `UmlDotGraphStyle` instance is created within the method, and there is no way to customize it before it is passed to the `ToGraph` method of the internal `StateGraph`.   

There are multiple ways to fix this.  The simplest and most liberal way would be to make `StateGraph` and its components public so that clients can extend the visualization as they see fit.  A more restrictive option would allow delegates and/or `IGraphStyle` instances to be passed into the `Format` method.  The downside to the second, more restrictive option is that clients would only be able to extend the style but not the structure of the DOT graph.  I would be happy to help implement either option.

**Comment by smartcaveman** [comment]
@HenningNT @nblumhardt

**Comment by JeremyCade** [comment]
@smartcaveman I'll take a look at this over the next, week time permitting.

**Comment by psibernetic** [comment]
Looking at it, i'm not sure why StateGraph became internal. It should be made using only what is in StateMachineInfo, which is intentionally public. There should be an interface on building graphs, like what I originally proposed with ICartographer, so that it can use a strategy pattern, similar to IFormatter.

**Comment by HenningNT** [comment]
How are things going with this one? It seems sensible to do something about it.

**Comment by smartcaveman** [comment]
@HenningNT I did some work on this about a year ago.  If it won't step on anyone's toes I can dig that up and make a PR.  @JeremyCade ?

**Comment by LoloActemium** [comment]
Hi,
+1
I would like to be able to "Customize" DOT Graphs.

**Comment by frankhommers** [comment]
The suggested solution is basically what I'm asking here: https://github.com/dotnet-state-machine/stateless/issues/290

**Comment by frankhommers** [comment]
@smartcaveman Please do so. Make it a pull request!

**Comment by mclift** [comment]
@smartcaveman I think this issue was resolved some time ago. Let me know if this should be reopened.
