### ISSUE TITLE
Transition object holds parent state as source state instead of child

### ISSUE THREAD

**Issue by xpleria** [dotnet-state-machine/stateless#214]
Stateless.StateMachine<State, Trigger> sm = new Stateless.StateMachine<State, Trigger>(State.GrandParent);

            Stateless.StateMachine<State, Trigger>.Transition t = null;

            sm.Configure(State.GrandParent)
                .OnEntry(transition => { t = transition; })
                .Permit(Trigger.GtoP, State.Parent);

            sm.Configure(State.Parent)
                .SubstateOf(State.GrandParent)
                .OnEntry(transition => { t = transition; })
                .Permit(Trigger.PtoA, State.Aunt)
                .Permit(Trigger.PtoCA, State.ChildA);

            sm.Configure(State.ChildA)
                .SubstateOf(State.Parent)
                .OnEntry(transition => { t = transition; })
                .Permit(Trigger.CAtoCB, State.ChildB);

            sm.Configure(State.ChildB)
                .SubstateOf(State.Parent)
                .OnEntry(transition => { t = transition; })
                .Permit(Trigger.CBtoCA, State.ChildA);

            sm.Configure(State.Aunt)
                .SubstateOf(State.GrandParent)
                .OnEntry(transition => { t = transition; })
                .Permit(Trigger.AtoP, State.Parent);

            sm.Fire(Trigger.GtoP);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

            sm.Fire(Trigger.PtoCA);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

            sm.Fire(Trigger.PtoA);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

            sm.Fire(Trigger.AtoP);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

            sm.Fire(Trigger.PtoCA);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

            sm.Fire(Trigger.CAtoCB);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

            sm.Fire(Trigger.PtoA);
            Console.WriteLine("From: {0} To: {1} Trigger: {2}", t.Source, t.Destination, t.Trigger);

Output when using 4.0.1-dev-00260 - Incorrect

	From: GrandParent To: Parent Trigger: GtoP
	From: Parent To: ChildA Trigger: PtoCA
	From: GrandParent To: Aunt Trigger: PtoA
	From: GrandParent To: Parent Trigger: AtoP
	From: Parent To: ChildA Trigger: PtoCA
	From: Parent To: ChildB Trigger: CAtoCB
	From: GrandParent To: Aunt Trigger: PtoA

Output when using 4.0.0 - Correct

	From: GrandParent To: Parent Trigger: GtoP
	From: Parent To: ChildA Trigger: PtoCA
	From: ChildA To: Aunt Trigger: PtoA
	From: Aunt To: Parent Trigger: AtoP
	From: Parent To: ChildA Trigger: PtoCA
	From: ChildA To: ChildB Trigger: CAtoCB
	From: ChildB To: Aunt Trigger: PtoA

**Comment by HenningNT** [comment]
Thanks for pointing this out! I have a PR for it.

**Comment by HenningNT** [comment]
PR merged, closing this.
