### ISSUE TITLE
[Question] Return to the caller state.

### ISSUE THREAD

**Issue by p-groarke** [dotnet-state-machine/stateless#215]
I have a situation which I am quite unsure how to solve. Lets say you have 2 states (walk and run), and they both can transition to a 3rd state (jump). Once the 3rd state is done, I wish to go back to the caller state.

Using EntryFrom doesn't seem to work, because there is no way to influence the "jump" state itself, only the OnEntry function.
Using PermitDynamic doesn't seem to work either, because once in the "jump" state, I have no idea where I came from.

I could have 2 jump states (jumpfromrun, jumpfromwalk) with a single OnEntry function, to minimize some duplicate code. This is what I currently use.
I could save the previous state in an external variable and pass that to my state update. I do not wish to do this (at all).

Is there a known technique or way to deal with this sort of problem? Having a shared state, that should transition back to the caller. Thank you!

**Comment by HenningNT** [comment]
If you don't want to store a flag, maybe you can do something like this:

            StateMachine<string, string> stateMachine = new StateMachine<string, string>("Walking");

            stateMachine.Configure("Walking")
                .Permit("Run", "Running")
                .Permit("Jump", "WalkingJump")
                .OnEntry(() => Debug.WriteLine("Walking OnEntry"))
                .OnExit(() => Debug.WriteLine("Walking OnExit"));

            stateMachine.Configure("WalkingJump")
                .SubstateOf("Walking")
                .Permit("Landed", "Walking")
                .OnEntry(() => Debug.WriteLine("WalkingJump OnEntry"))
                .OnExit(() => Debug.WriteLine("WalkingJump OnExit"));

            stateMachine.Configure("Running")
                .Permit("Walk", "Walking")
                .Permit("Jump", "RunningJump")
                .OnEntry(() => Debug.WriteLine("Running OnEntry"))
                .OnExit(() => Debug.WriteLine("Running OnExit"));

            stateMachine.Configure("RunningJump")
                .SubstateOf("Running")
                .Permit("Landed", "Running")
                .OnEntry(() => Debug.WriteLine("RunningJump OnEntry"))
                .OnExit(() => Debug.WriteLine("RunningJump OnExit"));

            stateMachine.OnTransitioned(transition => Debug.WriteLine($"{transition.Source} -[{transition.Trigger}]-> {transition.Destination}"));

            Debug.WriteLine("Firing Run");
            stateMachine.Fire("Run");
            Debug.WriteLine("Firing Jump");
            stateMachine.Fire("Jump");
            Debug.WriteLine("Firing Landed");
            stateMachine.Fire("Landed");
            Debug.WriteLine("Firing Walk");
            stateMachine.Fire("Walk");
            Debug.WriteLine("Firing Jump");
            stateMachine.Fire("Jump");
            Debug.WriteLine("Firing Landed");
            stateMachine.Fire("Landed");

**Comment by scottctr** [comment]
Here's a preview from the next release of [NStateManager](https://github.com/scottctr/NStateManager) that includes "automatic transitions" to solve this type of problem. See the 2 calls to AddAutoFallbackTransition below.
```C#
public void RunWalkJumpTest()
{
    var stopWatch = new Stopwatch();
    var stateMachine = new StateMachine<GameMan, GameManState, GameManEvent>(
        stateAccessor: man => man.State
        , stateMutator: (man, updatedState) => man.State = updatedState);

    stateMachine.ConfigureState(GameManState.Walking)
        .AddTransition(GameManEvent.Run, GameManState.Running)
        .AddAutoFallbackTransition(GameManEvent.SeePuddle, GameManState.Jumping, _ => true)
        .AddEntryAction(man => Console.WriteLine($"[{stopWatch.Elapsed}] Start Walking"))
        .AddExitAction(man => Console.WriteLine($"[{stopWatch.Elapsed}] Exiting walking"))
        .AddReentryAction(man => Console.WriteLine($"[{stopWatch.Elapsed}] Continuing to walk"));

    stateMachine.ConfigureState(GameManState.Running)
        .AddAutoFallbackTransition(GameManEvent.SeePuddle, GameManState.Jumping, _ => true)
        .AddEntryAction(man => Console.WriteLine($"[{stopWatch.Elapsed}] Start Running"))
        .AddExitAction(man => Console.WriteLine($"[{stopWatch.Elapsed}] Exiting running"))
        .AddReentryAction(man => Console.WriteLine($"[{stopWatch.Elapsed}] Continuing to run"));

    stateMachine.ConfigureState(GameManState.Jumping)
        .AddEntryAction(man =>
        {
            Console.WriteLine($"[{stopWatch.Elapsed}] starting jump...");
            Task.Delay(3000).Wait();
        })
    .AddExitAction(man => { Console.WriteLine($"[{stopWatch.Elapsed}] jump done."); });

========

stopWatch.Start();
var gameMan = new GameMan { State = GameManState.Walking };

stateMachine.FireTrigger(gameMan, GameManEvent.Walk);
-> [00:00:00.0098768] Continuing to walk

stateMachine.FireTrigger(gameMan, GameManEvent.SeePuddle);
-> [00:00:07.4301137] Exiting walking
-> [00:00:07.4312218] starting jump...
-> [00:00:10.4357909] jump done.
-> [00:00:10.4360137] Start Walking

stateMachine.FireTrigger(gameMan, GameManEvent.Run);
-> [00:00:10.4363021] Exiting walking
-> [00:00:10.4365828] Start Running

stateMachine.FireTrigger(gameMan, GameManEvent.SeePuddle);
-> [00:00:10.4370116] Exiting running
-> [00:00:10.4370355] starting jump...
-> [00:00:13.4382558] jump done.
-> [00:00:13.4400439] Start Running
```

**Comment by p-groarke** [comment]
Very nice! Thank you 👍

**Comment by HenningNT** [comment]
Here's another example using PermitDynamic to transition to history:

    class Program
    {
        static void Main(string[] args) {
            var example = new RunWalkJump();

            example.Run();
            example.Jump();
            example.Land();
            example.Walk();
            example.Jump();
            example.Land();

            Console.ReadKey();
        }
    }

    public class RunWalkJump
    {
        private readonly StateMachine<string, string> _stateMachine = new StateMachine<string, string>("Walking");
        private string _history;
        public RunWalkJump() {
            _stateMachine.Configure("Walking")
                .Permit("Run", "Running")
                .Permit("Jump", "Jumping")
                .OnEntry(() => Console.WriteLine("Walking OnEntry"))
                .OnExit(() => { Console.WriteLine("Walking OnExit"); _history = "Walking"; });

            _stateMachine.Configure("Jumping")
                .PermitDynamic("Land", stateSelector)
                .OnEntry(() => Console.WriteLine("Jumping OnEntry"))
                .OnExit(() => Console.WriteLine("Jumping OnExit"));

            _stateMachine.Configure("Running")
                .Permit("Walk", "Walking")
                .Permit("Jump", "Jumping")
                .OnEntry(() => Console.WriteLine("Running OnEntry"))
                .OnExit(() => { Console.WriteLine("Running OnExit"); _history = "Running"; });

            _stateMachine.OnTransitioned(transition => Console.WriteLine($"{transition.Source} -[{transition.Trigger}]-> {transition.Destination}"));
        }

        private string stateSelector()
        {
            return _history;
        }
        public void Run()
        {
            _stateMachine.Fire("Run");
        }
        public void Walk()
        {
            _stateMachine.Fire("Walk");
        }
        public void Jump()
        {
            _stateMachine.Fire("Jump");
        }
        public void Land()
        {
            _stateMachine.Fire("Land");
        }
    }

**Comment by scottctr** [comment]
@p-groarke just curious - can you provide any insight to the scenario that led to this question?

**Comment by p-groarke** [comment]
@scottctr It was quite close to the example I gave. This comes up all the time when using hierarchical state machines for character controllers in games. If my memory serves me well, it was an issue with triggering an attack state and going back to running vs. horseback riding vs. walking.

Same can be said for UI menus. You may have a UI panel, triggered from different base states. You'd like to "fallback" to the previous state without affecting the panel state itself. Hierarchical FSMs kind of fix this, but in an unintuitive way.
