### ISSUE TITLE
GetInfo() is too elaborate - configure output

### ISSUE THREAD

**Issue by utillity** [dotnet-state-machine/stateless#218]
It would be great to be able to reduce the amount of infos being rendered, and also alter the text and layout (line-type, color, etc.). 

Currently my Statemachine generates the code below. Here are my suggestions:

- don't render ignores, or in a smaller text/lighter color/dotted lines
- make initial state larger/centered/different color
- sub-states (.SubstateOf()) are not rendered correctly (Faulted is actually SubState of Connecting AND Connected) (bug, or not supported?)
- OnEntry info is usually not required and should be smaller and "Entry: <Method>" - it's unclear, what the / means
- forward in flow: solid lines, backward in flow: dotted lines

The Machine's main flow is Disabled > Scanning > Connecting > Connected > Closing > Disabled

		digraph {
		compound=true;
		node [shape=Mrecord]
		rankdir="LR"

		subgraph clusterConnecting
			{
			label = "Connecting\n----------\nentry / OnConnecting"
		Faulted [label="Faulted|entry / OnFaulted"];
		}

		subgraph clusterConnected
			{
			label = "Connected\n----------\nentry / OnConnected"
		}
		Disabled [label="Disabled|entry / OnDisabled"];
		Scanning [label="Scanning|entry / OnScanning"];
		Closing [label="Closing|entry / OnClosing"];

		Disabled -> Scanning [style="solid", label="Enabled"];
		Disabled -> Disabled [style="solid", label="CameraFound"];
		Disabled -> Disabled [style="solid", label="Connected"];
		Disabled -> Disabled [style="solid", label="ConnectionLost"];
		Disabled -> Disabled [style="solid", label="Reconnect"];
		Disabled -> Disabled [style="solid", label="Disabled"];
		Scanning -> Connecting [style="solid", label="CameraFound"];
		Scanning -> Closing [style="solid", label="Disabled"];
		Scanning -> Scanning [style="solid", label="Enabled"];
		Scanning -> Scanning [style="solid", label="Connected"];
		Scanning -> Scanning [style="solid", label="ConnectionLost"];
		Scanning -> Scanning [style="solid", label="Reconnect"];
		Connecting -> Closing [style="solid", label="CameraFound"];
		Connecting -> Connected [style="solid", label="Connected"];
		Connecting -> Faulted [style="solid", label="ConnectionLost"];
		Connecting -> Closing [style="solid", label="Reconnect"];
		Connecting -> Closing [style="solid", label="Disabled"];
		Connecting -> Connecting [style="solid", label="Enabled"];
		Connected -> Closing [style="solid", label="CameraFound"];
		Connected -> Faulted [style="solid", label="ConnectionLost"];
		Connected -> Closing [style="solid", label="Reconnect"];
		Connected -> Closing [style="solid", label="Disabled"];
		Connected -> Connected [style="solid", label="Enabled"];
		Connected -> Connected [style="solid", label="Connected"];
		Closing -> Scanning [style="solid", label="Enabled"];
		Closing -> Connecting [style="solid", label="Reconnect"];
		Closing -> Disabled [style="solid", label="Disabled"];
		Closing -> Closing [style="solid", label="CameraFound"];
		Closing -> Closing [style="solid", label="Connected"];
		Closing -> Closing [style="solid", label="ConnectionLost"];
		Faulted -> Scanning [style="solid", label="Enabled"];
		Faulted -> Connecting [style="solid", label="CameraFound"];
		Faulted -> Connected [style="solid", label="Connected"];
		Faulted -> Faulted [style="solid", label="ConnectionLost / OnFaulted"];
		Faulted -> Connecting [style="solid", label="Reconnect"];
		Faulted -> Disabled [style="solid", label="Disabled"];
		}

**Comment by HenningNT** [comment]
At the moment I'm afraid this will not be prioritized.
If you really need this please feel free to add another formatter to the codebase, it's designed to be easy to add new formatters.
