### ISSUE TITLE
Loading the entire work flow from JSon or XML

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet-state-machine/stateless#219]
Is it possible to load the triggers and states from a flat file format like JSON or XML. I'm looking at feature where by end users can use some designer and upload the same and work with those definition using this engine.

**Comment by HenningNT** [comment]
I think that should be doable, you can define the state machine as <string, string>.
It would also be possible to read DOT formatted diagrams.

**Comment by VenkateshSrini** [comment]
@HenningNT ,
I super impressed by even hearing the option as doable. Can you please share me some code sample or blog or some guidance on the same.

**Comment by HenningNT** [comment]
It depends a bit on how much of the workflow you want to define in a config file, and how complex the workflow is. I've made a solution at work that loads XML and creates stages to do a linear workflow. All stages was of the same base class/interface.  It was easy because the the state transitions was one way only, so I could use the stage name and an index for the states:

This is how I create a stage:
        private void AddStage(IGenericProfileStage stage, int index)
        {
            var stageName = "Stage_" + index;
            var nextStageName = "Stage_" + (index + 1);

            StateMachine.Configure(stageName)
                        .OnEntry(stage.OnEntry)
                        .InternalTransition(WarmUpEvent.onAction, () =>
                        {
                            if (stage.OnAction())
                                Post(new AOEvent<string, WarmUpEvent>(WarmUpEvent.NextStage));
                        })
                        .Permit(WarmUpEvent.NextStage, nextStageName);
        }

I think the challenge (or design decision) is how to hook up actions. However, I think it's probably not too complicated to turn something like this into a working state machine:
<StateMachine>
  <State Name="A">
    <Transition Trigger="X" Target="B"></Transition>
  </State>
  <State Name="B">
    <Transition Trigger="Y" Target="A"></Transition>
  </State>
</StateMachine>

**Comment by VenkateshSrini** [comment]
@HenningNT 

Yes I'm also stuck up with the same issue. Moreover I'm looking at a possibility of using the above for a microservice orchestration like Netflix conductor. So I need to capture the inputs to the for each stage and sent the input of one stage to another. 

That is why I asked is there a way where a we can just de-serialize the workflow definition and the workflow engine takes care of everything else?

Also do you have a sample where the workflow is read from a textual format like DOT, XML or JSON. That could be a good starting point for me. The sample could be an end to end which will run. I would then look into the code and learn
,

**Comment by VenkateshSrini** [comment]
@HenningNT 
 Is it possible to DE serialize a State machine from a DOT Graph. I see a method to only create a DOT graph but not read from DOT graph. DO we have a method to do that. That would also solve my problem

**Comment by HenningNT** [comment]
Hello again!
I don't have that sort of code, but I would like to see if you create it :-)

**Comment by inforexperience** [comment]
Also curious to learn more about parsing XML or JSon to build a state machine. Did you find a way to do this @VenkateshSrini ?

**Comment by NicoJuicy** [comment]
This is quite interesting. I'm looking into creating a node-red alternative in c#. But if it's possible to bind this with Stateless ( and adjusting some code). I might contribute it and use it as the orchestration engine.

Loading and exporting json would be a requirement.
But binding "services" aka nodes and storing some sort of State ( in json format), would be awesome. I'm digging into the code now.

Some pointers would be helpfull though

**Comment by HenningNT** [comment]
Storing state to json is easy, there's an example demonstrating saving and loading an initial state.

Hooking everything up from a configuration file is possible, I did it with a "linear" workflow. More complex workflows should be possible, but it might be a bit fiddly. I imagine one can use reflection, if necessary, to hook up trigger handlers.
