### ISSUE TITLE
InternalTransitionIf guard enters both States

### ISSUE THREAD

**Issue by b-khan** [dotnet-state-machine/stateless#227]
Hi,
I am running into an issue which feels like a bug to me. Here is my code:

        [Fact]
        public void TestInternalIf()
        {
            var curState = 1;
            var machine = new StateMachine<int, int>(() => curState, s => curState = s);

            Func<bool, bool> guard = isTrue => isTrue;

            machine.Configure(curState)
                .InternalTransitionIf(
                    1,
                    () => guard(true),
                    () =>
                    {
                        Console.WriteLine("Should be here");
                    })
                .InternalTransitionIf(
                    1,
                    () => guard(false),
                    () =>
                    {
                        throw new Exception("Should not be here");
                    });
            
            machine.Fire(1);
        }

My understanding is that the guard here should protect the action on the second InternalTransitionIf from going through. Is my assumption right, or am I using this incorrectly? Also, I noticed the guard is being evaluated about six times here for these statements. Is that correct as well?

**Comment by HenningNT** [comment]
Yes, that's a bug!

**Comment by HenningNT** [comment]
Please have a look at PR #231 , I think it solves the problem.

**Comment by HenningNT** [comment]
Sorted in PR #231.
