### ISSUE TITLE
Cycle detected when trying to install the Nuget package

### ISSUE THREAD

**Issue by MagnusJohansson** [dotnet-state-machine/stateless#237]
Is it just me?

Can't install the Nuget package (v4.0.0), getting:
```
NU1108: Cycle detected. 
  StateLess -> Stateless (>= 4.0.0).
```

**Comment by HenningNT** [comment]
It worked for me... what is "StateLess"? (with capital L)

**Comment by MagnusJohansson** [comment]
I don't know, this is a copy/paste from the Package Manager console...

However, this was in a .NET Core console app. When I tried in a .NET Standard library it  worked fine.

**Comment by HenningNT** [comment]
It seems to work for me in a .NET Core class library, did you install anything else from nuget?

**Comment by MagnusJohansson** [comment]
Yes, however on another PC it seems fine.. I'll guess the stars and the moon didn't properly align...
So, never mind.

**Comment by MagnusJohansson** [comment]
BTW, the issue was that I had my project name "StateLess" (that's where the capital L came from), and you can't have project names that equals a Nuget package name (case insensitive):
https://github.com/NuGet/Home/issues/936

**Comment by Bernoulli-IT** [comment]
> 
> 
> BTW, the issue was that I had my project name "StateLess" (that's where the capital L came from), and you can't have project names that equals a Nuget package name (case insensitive):
> [NuGet/Home#936](https://github.com/NuGet/Home/issues/936)

This is exactly it. Phew....
