### ISSUE TITLE
Is it possible to persist the state of a Machine?

### ISSUE THREAD

**Issue by MagnusJohansson** [dotnet-state-machine/stateless#238]
I would like to persist the whole state of a machine to a stream/json/file , i.e. in the BugTracker example , persist the Bug instance including the underlying _machine.

Then I would like to re-instantiate the whole lot at a later stage.

Is this possible?

**Comment by HenningNT** [comment]
If stateless was marked With the [Serializable] attribute, then maybe. Presently it isn't, so no it's not possible. Storing the current state and the object data is the only option at the moment.
