### ISSUE TITLE
Be able to provide external configuration

### ISSUE THREAD

**Issue by ronnyek** [dotnet-state-machine/stateless#24]
First of all forgive me, this isnt an issue but rather a general question. (and if its been asked, apologize about that as well)

I'd like to provide a bit of external config... eg, let users define states etc. Does stateless support definition and/or states from something other than an enum?

I dont mind writing something that initializes the container the proper way etc, but I cant really easily generate enums on the fly.

**Comment by nblumhardt** [comment]
No problem at all - good question. The trick here is that states don't have to be enums, you can declare a `StateMachine` that uses strings (or integers, or any other comparable type) for triggers and/or states.

Hope this helps!
