### ISSUE TITLE
how can i do this scenario one trigger go to two states (Parallel)/(Fork)

### ISSUE THREAD

**Issue by AWasseem** [dotnet-state-machine/stateless#241]

**Comment by HenningNT** [comment]
Unless you use substates then ut is impossible.

**Comment by scottctr** [comment]
@AWasseem can you provide more details about your scenario?

**Comment by HenningNT** [comment]
Here's a proof of consept:

´´´
using System;
using Stateless;

namespace ForkJoin
{
    enum Trigger { Fork, A, B, End }
    enum SubState { Initial, Done }
    static class Program
    {
        private static StateMachine<State, Trigger> _stateMachine;
        static void Main(string[] args)
        {
            var initialState = new State("initialState");
            var forkState = new ForkState("forkState");
            var endState = new State("endState");

            _stateMachine = new StateMachine<State, Trigger>(initialState);

            _stateMachine.Configure(initialState)
                .OnActivate(initialState.OnEntry)
                .Permit(Trigger.Fork, forkState)
                .OnExit(initialState.OnExit);

            _stateMachine.Configure(forkState)
                .OnEntry(forkState.OnEntry)
                .InternalTransition(Trigger.A, t => forkState.Fire(t.Trigger))
                .InternalTransition(Trigger.B, t => forkState.Fire(t.Trigger))
                .PermitIf(Trigger.End, endState, forkState.EndGuard)
                .OnExit(forkState.OnExit);

            _stateMachine.Configure(endState)
                .OnEntry(endState.OnEntry);

            _stateMachine.Activate();
            Fire(Trigger.Fork);
            Fire(Trigger.A);
            Fire(Trigger.B);
            Fire(Trigger.End);

            Console.ReadLine();
        }
        private static void Fire(Trigger trigger)
        {
            Console.WriteLine($"Firing trigger {trigger}");
            _stateMachine.Fire(trigger);
        }
    }
    public class State
    {
        public virtual string Name { get; protected set;}
        public State(string name)
        {
            Name = name;
        }
        protected State()
        { }
        internal void OnEntry()
        {
            Console.WriteLine($"Entering state {Name}");
        }
        public virtual void OnExit()
        {
            Console.WriteLine($"Exiting state {Name}");
        }
    }

    public class ForkState : State
    {
        private readonly StateMachine<SubState, Trigger> _subStateMachineOne;
        private readonly StateMachine<SubState, Trigger> _subStateMachineTwo;
        public override string Name { get { return $"{_subStateMachineOne.State} + {_subStateMachineTwo.State}"; } }
        public new void OnEntry()
        {
            Console.WriteLine($"ForkState entering {Name}");
        }
        public ForkState(string name)
        {
            Name = name;

            _subStateMachineOne = new StateMachine<SubState, Trigger>(SubState.Initial);
            _subStateMachineOne.Configure(SubState.Initial)
                .Permit(Trigger.A, SubState.Done);

            _subStateMachineTwo = new StateMachine<SubState, Trigger>(SubState.Initial);
            _subStateMachineTwo.Configure(SubState.Initial)
                .Permit(Trigger.B, SubState.Done);

            // Ignore unhandled triggers
            _subStateMachineOne.OnUnhandledTrigger((s, t ) => { });
            _subStateMachineTwo.OnUnhandledTrigger((s, t) => { });

            _subStateMachineOne.OnTransitioned(DisplayProgressOne);
            _subStateMachineTwo.OnTransitioned(DisplayProgressTwo);
        }

        private void DisplayProgressOne(StateMachine<SubState, Trigger>.Transition obj)
        {
            Console.WriteLine($"Internal state machine ONE transitioned from {obj.Source} to {obj.Destination}");
        }
        private void DisplayProgressTwo(StateMachine<SubState, Trigger>.Transition obj)
        {
            Console.WriteLine($"Internal state machine TWO transitioned from {obj.Source} to {obj.Destination}");
        }

        internal void Fire(Trigger trigger)
        {
            Console.WriteLine($"ForkState firing internally trigger {trigger}");
            _subStateMachineOne.Fire(trigger);
            _subStateMachineTwo.Fire(trigger);
        }

        internal bool EndGuard()
        {
            return (_subStateMachineOne.State == SubState.Done && _subStateMachineTwo.State == SubState.Done);
        }
    }
}

´´´

**Comment by HenningNT** [comment]
Can we close this?
