### ISSUE TITLE
The reference 'system' could not be added to the project

### ISSUE THREAD

**Issue by geedsen** [dotnet-state-machine/stateless#243]
Just installed the latest VSIX in VS 2017 and VS2017 preview. When I add a stateless item to a project (.NET Standard), I get a message: "The reference 'system' could not be added to the project, this wizard will continue to run, but the resulting project may not build properly." the .stateless file is there, the designer looks ok, but I don't see any c# being generated when building.

**Comment by HenningNT** [comment]
Maybe you have to do a nuget restore to get the system packages?

**Comment by geedsen** [comment]
If I start a new .NET Standard project, this happens. So it is the first package, nothing to restore. If I start a .NET framework project, it works just fine.

**Comment by HenningNT** [comment]
Which VSIX would that be?
I've created a new .NET standard Project and added stateless (latest stable) on two computers and it builds on both. I suspect it might be a configuration issue with your computer.

**Comment by geedsen** [comment]
I used the stateless designer from the .NET framework project, generated the code. And as I am now modifying that code anyway, I can no longer use the designer). So no need for it to get it to work. Thanks.
