### ISSUE TITLE
Need to get CI working again!

### ISSUE THREAD

**Issue by HenningNT** [dotnet-state-machine/stateless#247]
I signed up for an account at AppVeyor, and added the stateless Project. stateless builds, but the deployment to nuget fails. AppVeyor set the build number to Stateless.4.0.1-dev-00001 since this was the first build. I don't know if I can build from my Appveyor account and publish to nuget.

I think it fails because the api_key in the YAML file is not associated with my account, but someone elses.

@nblumhardt you were involved earlier, could you please comment on this and suggest a solution if you have one ;-)

**Comment by nblumhardt** [comment]
Hi @HenningNT -

I think there are a couple of considerations; first off, it's better to use an organisation account than a personal one for CI - we've already got one called "dotnetstatemachine" with the Stateless project under it - if you let me know your AppVeyor username, I can add you as an administrator.

Second, I think we'll need a new NuGet.org API key to publish packages; I've converted the "stateless" account on NuGet to an organization, if you let me know your NuGet.org login, I'll add you as an administrator there, too :-)

Sound like a plan?

**Comment by HenningNT** [comment]
Yes, that sounds like a plan!

My Appveyor usename is Henningnt. (Yes, I have no imagination )

**Comment by nblumhardt** [comment]
:+1: .. I went to set this up and found out I need to add you via email; hope I used the correct address, you should have an invitation now :-)

**Comment by nblumhardt** [comment]
Same username/email for NuGet.org?

**Comment by HenningNT** [comment]
My nuget account is HenningNT at Outlook dot com.
I can log on to the dotnetstatemachine account. 👍 

Now I'll have alook at this api key thingie:

> Error fetching YAML configuration file from the repository. Make sure AppVeyor is authorized to access your gitHub account: GitHub authorization required.

**Comment by HenningNT** [comment]
I authorized AppVeyor to access GitHub, but I'm not sure if it goes to my own stateless fork, or the proper one.

**Comment by nblumhardt** [comment]
All looking good! Just trying to get a dev build published now, using a  new API key from our stateless NuGet org.

**Comment by nblumhardt** [comment]
Working! https://www.nuget.org/packages/stateless

**Comment by HenningNT** [comment]
yay!
Thanks a lot!
