### ISSUE TITLE
Can Stateless be used for a "Wizard" on a website?

### ISSUE THREAD

**Issue by meatballcoder** [dotnet-state-machine/stateless#257]
Is Stateless appropriate for a "Wizard" or whatever it is called, where you have to fill out certain information to go to the next page or tab on a webpage?

**Comment by HenningNT** [comment]
Maybe some time in the future WebAssembly could run .net code in the browser. At the moment you'd have to run stateless on the server.
At this time there are probably better solutions for that sort of task.

**Comment by dave-mcn** [comment]
> Maybe some time in the future WebAssembly could run .net code in the browser. 

In case you haven't heard of this new Microsoft project:
[Microsoft Blazor](https://github.com/aspnet/Blazor)
_"An experimental .NET web framework using C#/Razor and HTML that runs in the browser via WebAssembly"_
