### ISSUE TITLE
Having problems with SetTriggerParameters

### ISSUE THREAD

**Issue by gokulm** [dotnet-state-machine/stateless#258]
cannot convert from 'Stateless.StateMachine<Stateless.Tests.State, Stateless.Tests.Trigger>.TriggerWithParameters<int>' to 'Stateless.Tests.Trigger'

To reproduce this problem: modify the test project's Stateless project reference to NuGet reference, and try to run this test in StateMachineFixture

[Fact]
        public void TransitionWhenParameterizedGuardTrue()
        {
            var sm = new StateMachine<State, Trigger>(State.A);
            var x = sm.SetTriggerParameters<int>(Trigger.X);
            sm.Configure(State.A).PermitIf(x, State.B, i => i == 2);
            sm.Fire(x, 2);

            Assert.Equal(sm.State, State.B);
        }

**Comment by HenningNT** [comment]
Which revision of the nuget package are you using?

**Comment by gokulm** [comment]
Version 4.0.0

**Comment by HenningNT** [comment]
I see, at the moment v4 doesn't support TriggerWithParameters, because Permit doesn't have action associated with it. You'll have to use something else, OnEntryFrom or InternalTransition. PermitDynamic also supports TriggerWithParameters to decide which state to transition to.
