### ISSUE TITLE
Reentry causes OnExit to fire twice

### ISSUE THREAD

**Issue by msaposs** [dotnet-state-machine/stateless#264]
When I use Reentry to transition from a state back into itself, then the OnExit event fires twice. The two calls are identical – you can’t tell that 2 calls happened (even if you use the optional Transition argument to the OnExit action.

Example:

Code:
        enum State { Open, InProgress, Closed, Done, Ignored }
        enum Trigger { BeginWork, FinishWork, SetDone, Ignore, ResumeWork, KeepWorking, KeepOpen }

        static void Main(string[] args)
        {
            //BigTest();
            ReentryTest();
        }

        static void ReentryTest()
        {
            var stateMachine = new StateMachine<State, Trigger>(State.Open);

            stateMachine.Configure(State.Open)
                .PermitReentry(Trigger.KeepOpen)
                //.Permit(Trigger.KeepOpen, State.Open)                     // Throws runtime exception: Permit() (and PermitIf()) require that the destination state is not equal to the source state. To accept a trigger without changing state, use either Ignore() or PermitReentry().
                .OnEntry(() => Debug.WriteLine("Enter Open"))
                .OnExit(() => Debug.WriteLine("Exit Open"));

            Debug.WriteLine($"Initial state: {stateMachine.State}");

            Debug.WriteLine("Fire KeepOpen");
            stateMachine.Fire(Trigger.KeepOpen);

            Debug.WriteLine($"Final state: {stateMachine.State}");
        }

Output:
Initial state: Open
Fire KeepOpen
Exit Open
Exit Open
Enter Open
Final state: Open

**Comment by HenningNT** [comment]
Same as #261 .

Should be fixed in v4.2

**Comment by HenningNT** [comment]
Fixed in v4.2
