### ISSUE TITLE
Exception from OnEntry action should not result in queued trigger being executed after next trigger

### ISSUE THREAD

**Issue by Snaaio** [dotnet-state-machine/stateless#267]
I would like to design a state machine in which an exception thrown from an OnEntry action can propagate to the caller firing the trigger. Unfortunately I saw some weird behavior regarding the queuing of triggers.

As a workaround I upgraded to Stateless v4.2.0 and configured my statemachine to use FiringMode.Immediate, but it would be nice to see the default FiringMode.Queued play a bit nicer with exceptions being thrown.

Possible options to better handle this:
1. Catch exception and execute queued triggers before rethrowing
1. Catch exception and clear queued triggers before rethrowing
1. Do not catch exception and retain queued triggers (current behavior)
   Add new method(s) on StateMachine to:
   A. Fire queued triggers
   B. Clear queued triggers

```
enum State { Idle, Initializing, Ready, Error }
enum Trigger { Init, Ready, Error }

[Test]
public void NUnitTestStateless_FireErrorTriggerFromOnEntryActionAndThenThrow_ShouldNotExecuteQueuedErrorTriggerAfterNextTrigger()
{
    var stm = new StateMachine<State, Trigger>(State.Idle);
    stm.Configure(State.Idle)
        .Permit(Trigger.Init, State.Initializing);
    stm.Configure(State.Initializing)
        .Permit(Trigger.Ready, State.Ready)
        .Permit(Trigger.Error, State.Error)
        .OnEntry(() =>
        {
            try
            {
                throw new InvalidOperationException("Test exception.");
            }
            catch
            {
                stm.Fire(Trigger.Error);
                throw;
            }
        });
    try
    {
        stm.Fire(Trigger.Init);
    }
    catch
    {
        // Normally the exception would be handled here
    }

    stm.Fire(Trigger.Ready); // Fails with System.InvalidOperationException : No valid leaving transitions are permitted from state 'Ready' for trigger 'Error'. Consider ignoring the trigger.

    Assert.That(stm.State, Is.EqualTo(State.Ready));
}
```

**Comment by Snaaio** [comment]
@HenningNT The weird behaviour was:
1. Initially a caller fires a first trigger A (from externally), which results in a state transition and execution of the corresponding OnEntry action
1. From that OnEntry action a trigger is fired, which is queued internally by stateless
1. Later in that same OnEntry action, an exception is thrown which is unhandled inside the OnEntry action and propagates through stateless to the caller of the initial trigger
1. **The weird behaviour:** When the caller handles the exception and fires a second trigger B (from externally), the **old leftover queued triggers get executed after this second trigger**.

While the current behaviour does not seem right, I am struggling with what the expected behaviour should be. After an unhandled exception I think any remaining queued triggers should either:
1. be fired on the next trigger, with all triggers being executed in their original order
1. not be fired at all
Or maybe there is no universally correct choice here and the developer must be able to decide what happens?

**Comment by Snaaio** [comment]
@gerardog You mentioned you stopped using OnEntry actions in your comment here:
https://github.com/dotnet-state-machine/stateless/pull/190#issuecomment-395883795

May I ask how you would design a stateless state machine when you have the following requirements:
1. Need to execute an action on entry of a state (or on activate, what is the difference?);
1. That action can throw an exception;
1. When that action throws an exception, the state machine should transition into an error state;
1. The original exception needs to be rethrown to the caller of the trigger on which the action was executed.

**Comment by gerardog** [comment]
@Snaaio, in your case I would wrap all stm.Fire() method calls inside a wrapper function, lets call it FireTrigger(). Inside it I would: (pseudocode)

```
public void FireTrigger(Trigger trigger)
{
    try { stm.Fire(trigger); } 
    catch (Exception ex) 
    {
        stm.Fire(Trigger.Error); 
        throw;
    }
}
```

**Comment by HenningNT** [comment]
I'm fixing the out-of-order trigger execution, but leaving the error handling untouched.
