### ISSUE TITLE
InvalidOperationException when executing async OnTransitioned callback from FireAsync

### ISSUE THREAD

**Issue by jpnoir** [dotnet-state-machine/stateless#268]
This is in v4.2.0 from last night.

The error message says:

> System.InvalidOperationException: Cannot execute asynchronous action specified as OnTransitioned callback. Use asynchronous version of Fire [FireAsync]

And, I am using the FireAsync method. This seems to happen only if we're in a Reentry path.

Perhaps line 197 in StateMachine.Async.cs should have been:

   _onTransitionedEvent.InvokeAsync(new Transition(source, handler.Destination, trigger));

instead of 

   _onTransitionedEvent.Invoke(new Transition(source, handler.Destination, trigger));

I've attached a repro
[StatelessOnTransitionedBug.zip](https://github.com/dotnet-state-machine/stateless/files/2063424/StatelessOnTransitionedBug.zip)

**Comment by HenningNT** [comment]
Thanks for reporting this!
I think you are right, let me take a quick look...

**Comment by HenningNT** [comment]
Fixed in v4.2.1
