### ISSUE TITLE
OnEntryFrom - action depends on last state

### ISSUE THREAD

**Issue by sonnichjensen** [dotnet-state-machine/stateless#271]
Hi all

The question is to enter a state from another state, but have no action.
This can be done by looking at LastState (missing).
Say:
Start -> End. Both have proper actions. Start -> Fail. Both have actions. Start -> End -> Fail - the last one is a result of "end" failing, but should not execute any code.
This can be done by flags, specific triggers,  "LastState", or a new version OnEntryFrom... 
My suggestion is the 2 last options.

**Comment by HenningNT** [comment]
Maybe you could make the entry action take a Transition parameter, and decide to execute the action based on the information in the Transition object? Something like this:

...
            sm.Configure(Fail)
                .OnEntry(OnEntryFail);
...

        private void OnEntryFail(StateMachine<State, Trigger>.Transition obj)
        {
            // Do not execute if source is 'End' state
            if (obj.Source == End) return;

            // Execute normally...
        }

I haven't tried this, but I think it should work.

**Comment by sonnichjensen** [comment]
Thanks. That works perfectly. For some reason I did not find this in the documentation
