### ISSUE TITLE
OnEntryAsync Not Available

### ISSUE THREAD

**Issue by itsmemittal** [dotnet-state-machine/stateless#274]
Hi i am trying to using Stateless with async await but async methods are not present. Would you please help me out to configure stateless asynchronous.

**Comment by HenningNT** [comment]
This late reply probably seems like an insult, sorry about that. There is two async versions of OnEntry:

```            
    sm.Configure(State.A)
            .OnEntryAsync(async () => await Jalla())
            .OnEntryAsync(() => Balla())
```
