### ISSUE TITLE
Nullable enum as state - transition from null state

### ISSUE THREAD

**Issue by m-demydiuk** [dotnet-state-machine/stateless#283]
Hi, is it possible to configure state machine to allow null as initial value. I am trying to add next configuration
```
_machine
    .Configure((PaymentStatus?) null)
    .Permit(PaymentStatusTrigger.Incompleted, PaymentStatus.INCOMPLETE);
```

but it gives me next error
```
Message: System.ArgumentNullException : Value cannot be null.
Parameter name: key
```

Please advice, thank you!

**Comment by HenningNT** [comment]
Please do not use null ;-)

Stateless needs 'something' to work with as a state.

**Comment by Vitegor** [comment]
Maybe you need some new status like `Payment.INITIALIZED` :)
