### ISSUE TITLE
Querying StateMachine for current State

### ISSUE THREAD

**Issue by arun02139** [dotnet-state-machine/stateless#29]
Hello all, long time user of Stateless and first time poster!

Disclaimer: I am not very experienced with C# and taught myself programing through a _lot_ of trial and error, apologies in advance for disturbing you f^^;)...

My states are classes deriving from a simple BaseState I made:
https://gist.github.com/arun02139/d34e70e3b4ac9441a8af

Sometimes I want to check the state of a machine but I have to do so by checking the state type against the type of the current State using a custom function I added .  Is there a more elegant way to do this when I don't want the state classes themselves to be exposed outside of the 'Battle' class that maintains the state-machine?

Thanks for your time and thoughts, everyone!

**Comment by nblumhardt** [comment]
Howdy! Thanks for getting in touch. I am not sure if there's a pre-baked solution for what you're doing, but states based on `enum`s rather than subclasses seem to come the closest to what you're looking for.

As a hybrid approach, perhaps your `BaseState` could expose a property of an enumeration type like `StateDescription` and the subclasses could each return a different value? Thus the check for the current state could be:

```csharp
var current = sm.State.Description; // an enum value
```

? Hope this helps!

Nick

**Comment by arun02139** [comment]
Thanks for your prompt suggestion, Nick!

The major appeal of Stateless for me was a chance to cleanly separate lots of ugly UI logic into separate files, i.e. the entry / exit functions of states.

If I understand correctly, if I use enums to represent states then I will need another place to write logical entry / exit functions to contain my UI logic code, correct?  Making the states into classes with these functions built-in seemed appropriate for my purposes...  

I'll try your hybrid suggestion and report back, thanks!

**Comment by psibernetic** [comment]
You should be able to use classes that implement IEquatable<BaseState> and the normal C# equality, hashcode, and == / != operators. BaseState can have abstract or virtual methods for the actions that way. I use am immutable class design with a StateName string property to identify my states.

https://github.com/psibernetic/REstate/blob/master/src/REstate/State.cs
