### ISSUE TITLE
InitialTransition not called on reentry

### ISSUE THREAD

**Issue by p-hu** [dotnet-state-machine/stateless#299]
[Test] //NUnit
        public void Transition_with_reentry_Test()
        {
            // ------------      -------------------------
            // |          |--X-->|            A          |---\
            // |    C     |      |        ---------      |    X (PermitReentry)
            // |          |      |   o--->|   B   |      |<--/         
            // ------------      |        ---------      |          
            //                   |            |          |
            //                   |            Y          |
            //                   |<----------/           |
            //                   |                       |
            //                   -------------------------          
            //                 
            // X: C => A initT => B  OK
            // Y: B => A initT => B  OK
            // X: B => A => reentry A , ... missing initT => B

            var sm = new StateMachine<TestStates, TestTriggers>(TestStates.C); //never triggers any action!

            int order = 0;

            int onEntryStateAfired = 0;
            int onEntryStateBfired = 0;
            int onExitStateAfired = 0;
            int onExitStateBfired = 0;
            int onTransitionActionXfromA = 0;
            int onTransitionActionXfromC = 0;
            int onTransitionActionYfromB = 0;

            sm.Configure(TestStates.C)
                .PermitDynamic(TestTriggers.X, () =>
                {
                    onTransitionActionXfromC = ++order;
                    return TestStates.A;
                })
                ;

            sm.Configure(TestStates.A)
                .InitialTransition(TestStates.B)
                .OnEntry(t => onEntryStateAfired = ++order)
                .OnExit(t => onExitStateAfired = ++order)
                .PermitReentry(TestTriggers.X)
                ;

            sm.Configure(TestStates.B)
                .SubstateOf(TestStates.A)
                .OnEntry(t => onEntryStateBfired = ++order)
                .OnExit(t => onExitStateBfired = ++order)
                .PermitDynamic(TestTriggers.Y, () =>
                {
                    onTransitionActionYfromB = ++order;
                    return TestStates.A;
                })
                ;

            Assert.AreEqual(TestStates.C, sm.State); // Ok

            sm.Fire(TestTriggers.X); // X: C=>A initT=>B

            Assert.AreEqual(TestStates.B, sm.State); // Ok
            Assert.AreEqual(1, onTransitionActionXfromC);           // Ok
            Assert.AreEqual(2, onEntryStateAfired);             // Ok 
            Assert.AreEqual(3, onEntryStateBfired);             // OK
            Assert.AreEqual(0, onTransitionActionYfromB);           // Ok
            Assert.AreEqual(0, onExitStateAfired);              // Ok
            Assert.AreEqual(0, onExitStateBfired);              // Ok

            onEntryStateAfired = 0;
            onEntryStateBfired = 0;
            onExitStateAfired = 0;
            onExitStateBfired = 0;
            onTransitionActionXfromA = 0;
            onTransitionActionXfromC = 0;
            onTransitionActionYfromB = 0;
            order = 0;

            sm.Fire(TestTriggers.Y); // B=>A initT=>B

            Assert.AreEqual(TestStates.B, sm.State); // Ok

            Assert.AreEqual(1, onTransitionActionYfromB);           // Ok
            Assert.AreEqual(2, onExitStateBfired);              // Ok
            Assert.AreEqual(3, onEntryStateBfired);             // OK
            Assert.AreEqual(0, onExitStateAfired);              // Ok
            Assert.AreEqual(0, onEntryStateAfired);             // Ok
            Assert.AreEqual(0, onTransitionActionXfromC);           // Ok

            onEntryStateAfired = 0;
            onEntryStateBfired = 0;
            onExitStateAfired = 0;
            onExitStateBfired = 0;
            onTransitionActionXfromA = 0;
            onTransitionActionXfromC = 0;
            onTransitionActionYfromB = 0;
            order = 0;

            sm.Fire(TestTriggers.X); // B=>A=>A initT=>B

            //Assert.AreEqual(TestStates.B, sm.State); // fails, it's A
            Assert.AreEqual(TestStates.A, sm.State); // Should be B

            Assert.AreEqual(1, onExitStateBfired);              // Ok
            Assert.AreEqual(2, onExitStateAfired);              // Ok
            Assert.AreEqual(3, onEntryStateAfired);             // Ok
            //Assert.AreEqual(4, onEntryStateBfired);             // fails
            Assert.AreEqual(0, onTransitionActionXfromA);       // Ok
            Assert.AreEqual(0, onTransitionActionXfromC);       // Ok
            Assert.AreEqual(0, onTransitionActionYfromB);       // Ok
        }

**Comment by HenningNT** [comment]
Thanks for the bug report! (Nice ASCII art)

I've updated the code to fix this bug, please take a look at the latest changes in dev.

**Comment by p-hu** [comment]
Thank you, that was quick!

**Comment by HenningNT** [comment]
Have you had a chance to try the code, I might try to release it if it works.

**Comment by HenningNT** [comment]
Seems to be working better now, Onentry is called only once, and in the right order.
