### ISSUE TITLE
Unity Visual Inspector

### ISSUE THREAD

**Issue by arun02139** [dotnet-state-machine/stateless#30]
Ok so, this is totally a feature request and not an "issue" -- Nick just tell me if this post is in the wrong place and I'll take it down / move it :)

So, I was wondering if there is anyone who wants to try and build a visual inspector for Unity that works with Stateless together with me. This work probably doesn't belong as part of the 'Stateless' repo itself, but could be another Github project (and possibly released in the Unity Asset Store too).

Phase 1 would be a pure visualization of state hierarchy and flow during runtime.

Phase 2 would be to allow the machine to be setup through the inspector itself (would require converting a Unity editor-made diagram / meta-data into auto-generated C# code...? lol not sure)

Just a thought, would like to hear feedback on this idea from anyone who's used Stateless and Unity together ^^

**Comment by psibernetic** [comment]
I have started looking into this using D3.js for creating a JSON document that can then be consumed from a Stateless factory. 

I may be building off a coworkers previous work: https://github.com/psibernetic/process-editor

Here is my example factory, the IStateMachineConfiguration is deserialized from tables OR json.

https://github.com/psibernetic/REstate/blob/master/src/REstate.Stateless/StatelessStateMachineFactory.cs

**Comment by nblumhardt** [comment]
I think the DOT graph support we now have is a step in this direction. It would be interesting to hear where you ended up, but I think we'll close this ticket for now. Cheers!
