### ISSUE TITLE
Reentry not done with self PermitDynamic

### ISSUE THREAD

**Issue by p-hu** [dotnet-state-machine/stateless#300]
[Test] //NUnit
        public void Transition_with_constructed_reentry_Test()
        {
            // ------------      -------------------------
            // |          |--X-->|            A          |---\
            // |    C     |      |        ---------      |    X (constructed reentry)
            // |          |      |   o--->|   B   |      |<--/         
            // ------------      |        ---------      |          
            //                   |            |          |
            //                   |            Y          |
            //                   |<----------/           |
            //                   |                       |
            //                   -------------------------          
            //                 
            // X: C => A initT => B  OK
            // Y: B => A initT => B  OK
            // X: B => ... missing this actions A=>A ... initT =>B 

            var sm = new StateMachine<TestStates, TestTriggers>(TestStates.C); //never triggers any action!

            int order = 0;

            int onEntryStateAfired = 0;
            int onEntryStateBfired = 0;
            int onExitStateAfired = 0;
            int onExitStateBfired = 0;
            int onTransitionActionXfromA = 0;
            int onTransitionActionXfromC = 0;
            int onTransitionActionYfromB = 0;

            sm.Configure(TestStates.C)
                .PermitDynamic(TestTriggers.X, () =>
                {
                    onTransitionActionXfromC = ++order;
                    return TestStates.A;
                })
                ;

            sm.Configure(TestStates.A)
                .InitialTransition(TestStates.B)
                .OnEntry(t => onEntryStateAfired = ++order)
                .OnExit(t => onExitStateAfired = ++order)
                //.Permit(TestTriggers.X, TestStates.A) //not allowed. anyway there should be an action possible on a trigger here, not only once I am in the new state with OnEntryFrom.
                .PermitDynamic(TestTriggers.X, () => //constructed reentry
                {
                    onTransitionActionXfromA = ++order;
                    return TestStates.A;
                })
                ;

            sm.Configure(TestStates.B)
                .SubstateOf(TestStates.A)
                .OnEntry(t => onEntryStateBfired = ++order)
                .OnExit(t => onExitStateBfired = ++order)
                .PermitDynamic(TestTriggers.Y, () =>
                {
                    onTransitionActionYfromB = ++order;
                    return TestStates.A;
                })
                ;

            Assert.AreEqual(TestStates.C, sm.State); // Ok

            sm.Fire(TestTriggers.X); // X: C=>A initT=>B

            Assert.AreEqual(TestStates.B, sm.State); // Ok
            Assert.AreEqual(1, onTransitionActionXfromC);           // Ok
            Assert.AreEqual(2, onEntryStateAfired);             // Ok 
            Assert.AreEqual(3, onEntryStateBfired);             // OK
            Assert.AreEqual(0, onTransitionActionYfromB);           // Ok
            Assert.AreEqual(0, onExitStateAfired);              // Ok
            Assert.AreEqual(0, onExitStateBfired);              // Ok

            onEntryStateAfired = 0;
            onEntryStateBfired = 0;
            onExitStateAfired = 0;
            onExitStateBfired = 0;
            onTransitionActionXfromA = 0;
            onTransitionActionXfromC = 0;
            onTransitionActionYfromB = 0;
            order = 0;

            sm.Fire(TestTriggers.Y); // B=>A initT=>B

            Assert.AreEqual(TestStates.B, sm.State); // Ok

            Assert.AreEqual(1, onTransitionActionYfromB);           // Ok
            Assert.AreEqual(2, onExitStateBfired);              // Ok
            Assert.AreEqual(3, onEntryStateBfired);             // OK
            Assert.AreEqual(0, onExitStateAfired);              // Ok
            Assert.AreEqual(0, onEntryStateAfired);             // Ok
            Assert.AreEqual(0, onTransitionActionXfromC);           // Ok

            onEntryStateAfired = 0;
            onEntryStateBfired = 0;
            onExitStateAfired = 0;
            onExitStateBfired = 0;
            onTransitionActionXfromA = 0;
            onTransitionActionXfromC = 0;
            onTransitionActionYfromB = 0;
            order = 0;

            sm.Fire(TestTriggers.X); // B=>A=>A initT =>B

            Assert.AreEqual(TestStates.B, sm.State); // OK

            Assert.AreEqual(1, onTransitionActionXfromA);       // Ok
            Assert.AreEqual(2, onExitStateBfired);              // Ok
            //Assert.AreEqual(3, onExitStateAfired);            // fails
            Assert.AreEqual(0, onExitStateAfired);              // should be 3
            //Assert.AreEqual(4, onEntryStateAfired);           // fails
            Assert.AreEqual(0, onEntryStateAfired);             // should be 4
            //Assert.AreEqual(5, onEntryStateBfired);           // fails
            Assert.AreEqual(3, onEntryStateBfired);             // should be 5
            Assert.AreEqual(0, onTransitionActionXfromC);       // Ok
            Assert.AreEqual(0, onTransitionActionYfromB);       // Ok
        }

**Comment by HenningNT** [comment]
This unit test is a bit too big. And there isn't a good description of what the expected outcome should be. Could you create a smaller test with a single call to Fire that demonstrates the problem?

**Comment by p-hu** [comment]
OK, thankt you for watching at it! the short form is following:

`        [Test] //NUnit
        public void Transition_with_constructed_reentry_not_working_Test_short()
        {
            //  Issue: there is no exit A and entry A when firing X from B
            //
            //   -------------------------
            //   |            A          |---\
            //   |        ---------      |    X (constructed reentry)
            //   |   o--->|   B   |      |<--/         
            //   |        ---------      |          
            //   |                       |
            //   -------------------------          
            //                 
            // X: B => ... missing this actions A=>A ... initT =>B 

            var sm = new StateMachine<TestStates, TestTriggers>(TestStates.B);

            int order = 0;

            int onEntryStateA = 0;
            int onEntryStateB = 0;
            int onExitStateA = 0;
            int onExitStateB = 0;
            int onTransitionActionXfromA = 0;


            sm.Configure(TestStates.A)
                .InitialTransition(TestStates.B)
                .OnEntry(t => onEntryStateA = ++order)
                .OnExit(t => onExitStateA = ++order)
                .PermitDynamic(TestTriggers.X, () => //constructed reentry (to have an action with the trigger!)
                {
                    onTransitionActionXfromA = ++order;
                    return TestStates.A;
                })
                ;

            sm.Configure(TestStates.B)
                .SubstateOf(TestStates.A)
                .OnEntry(t => onEntryStateB = ++order)
                .OnExit(t => onExitStateB = ++order)
                ;


            onEntryStateA = 0;
            onEntryStateB = 0;
            onExitStateA = 0;
            onExitStateB = 0;
            onTransitionActionXfromA = 0;
            order = 0;

            sm.Fire(TestTriggers.X); // B=>A=>A initT =>B

            Assert.AreEqual(TestStates.B, sm.State); // OK

            Assert.AreEqual(1, onTransitionActionXfromA);       // Ok
            Assert.AreEqual(2, onExitStateB);              // Ok
            //Assert.AreEqual(3, onExitStateA);            // fails
            Assert.AreEqual(0, onExitStateA);              // should be 3
            //Assert.AreEqual(4, onEntryStateA);           // fails
            Assert.AreEqual(0, onEntryStateA);             // should be 4
            //Assert.AreEqual(5, onEntryStateB);           // fails
            Assert.AreEqual(3, onEntryStateB);             // should be 5
        }
`

**Comment by p-hu** [comment]
[Test] //NUnit
        public void Transition_with_constructed_reentry_not_working_Test_short()
        {
            //  Issue: there is no exit A and entry A when firing X from B
            //
            //   -------------------------
            //   |            A          |---\
            //   |        ---------      |    X (constructed reentry)
            //   |   o--->|   B   |      |<--/         
            //   |        ---------      |          
            //   |                       |
            //   -------------------------          
            //                 
            // X: B => ... missing this actions A=>A ... initT =>B 

            var sm = new StateMachine<TestStates, TestTriggers>(TestStates.B);

            int order = 0;

            int onEntryStateA = 0;
            int onEntryStateB = 0;
            int onExitStateA = 0;
            int onExitStateB = 0;
            int onTransitionActionXfromA = 0;


            sm.Configure(TestStates.A)
                .InitialTransition(TestStates.B)
                .OnEntry(t => onEntryStateA = ++order)
                .OnExit(t => onExitStateA = ++order)
                .PermitDynamic(TestTriggers.X, () => //constructed reentry (to have an action with the trigger!)
                {
                    onTransitionActionXfromA = ++order;
                    return TestStates.A;
                })
                ;

            sm.Configure(TestStates.B)
                .SubstateOf(TestStates.A)
                .OnEntry(t => onEntryStateB = ++order)
                .OnExit(t => onExitStateB = ++order)
                ;


            onEntryStateA = 0;
            onEntryStateB = 0;
            onExitStateA = 0;
            onExitStateB = 0;
            onTransitionActionXfromA = 0;
            order = 0;

            sm.Fire(TestTriggers.X); // B=>A=>A initT =>B

            Assert.AreEqual(TestStates.B, sm.State); // OK

            Assert.AreEqual(1, onTransitionActionXfromA);       // Ok
            Assert.AreEqual(2, onExitStateB);              // Ok
            //Assert.AreEqual(3, onExitStateA);            // fails
            Assert.AreEqual(0, onExitStateA);              // should be 3
            //Assert.AreEqual(4, onEntryStateA);           // fails
            Assert.AreEqual(0, onEntryStateA);             // should be 4
            //Assert.AreEqual(5, onEntryStateB);           // fails
            Assert.AreEqual(3, onEntryStateB);             // should be 5
        }

**Comment by HenningNT** [comment]
Thank you!

I think this will have to be on of the limitations of Stateless.
At the moment there is no way of specifying if a dynamic trigger should be processed as a re-entrant transition or not. Since the library does not know if the user wants to have a re-entrant transition, or not.

If you have time (sadly I do not) to look into it to find a workable solution, then please do so :-)

**Comment by p-hu** [comment]
I see. Thank you for support anyway!

My personal requirements would already be satisfied if I could pass an optional action to PermitReentry().

That said, I am not sure whether I am fitting into the common stateless user profile. I am working with it because I took over code which (successfully) uses it.

But I am used to state machines with actions on triggers (usualy before transition) in contrary to actions on entry from a trigger (or as I call it 'action during transition').

So don't mind too much, I try to find a way around the issue. Thanks
