### ISSUE TITLE
DynamicTransitionInfo does not contains all possible states when using PermitDynamicIf configuration

### ISSUE THREAD

**Issue by audricpod** [dotnet-state-machine/stateless#305]
Hi there,

I have been using for a few weeks Stateless and it is working great !
But the default `UmlDotGraph.Format` method is not enough for me and I'm a creating a new one (for isolating sub graphe) using the Reflection API.

And I am facing a problem for generating my statemachine graph, when using `PermitDynamicIf `state configuration, the `PossibleDestinationStates` property is not accessible in the `DynamicTransitionInfo` and also is null

Is it a bug ? or volontary restriction ?
Is there another way to get all the available dynamic state ?

thanks in advance for helping

Audric

**Comment by audricpod** [comment]
With a sample it is always better

Here is my state configuration :

```
           Configure(StateAA)
                .SubstateOf(StateA)
                .OnExit(() => anything())
            .PermitDynamicIf(Triggers.ValidateState,
                               () => IsFInished ? StateFinished : StateX ,
                               () => State.IsStateValid);
```


and here my graph function :

        public string GetSubgraph(string superStateStr)
        {
            States? SuperState = Enum.Parse(typeof(States), superStateStr) as States?;			
            if (!SuperState.HasValue)
            {
                return "";
            }

            StringBuilder graphSb = new StringBuilder();
            graphSb.AppendLine(@"digraph G {");
            graphSb.AppendLine();
			
			[...]


			var allSubstates = GetInfo().States.Where(x => x.Superstate != null &&
                                                      (x.Superstate.UnderlyingState is MyState myState) &&
                                                      myState.CurrentState == SuperState);
            // Transitions
            foreach (var s in allSubstates)
            {
                var myState = (s.UnderlyingState as MyState);

                foreach (var t in s.Transitions)
                {
                    if (t is FixedTransitionInfo fixedTr)
                    {
                        graphSb.AppendLine($"{myState.CurrentState} -> {fixedTr.DestinationState};");
                    }
                    else if (t is DynamicTransitionInfo dynamicTr)
                    {
                        // KO - github issue 
                        // https://github.com/dotnet-state-machine/stateless/issues/305
                        //foreach (var possibleState in dynamicTr.PossibleDestinationStates)
                        //{
                        //    graphSb.AppendLine($"{myState.CurrentState} -> {possibleState.ToString()};");
                        //}

                    }
                }                
            }
            graphSb.Append("}");

            return graphSb.ToString();
        }

**Comment by mclift** [comment]
Hi Audric,

I raised PR #295 as I ran into this a few weeks back, and an issue had already been raised asking to make the reflection API public. I suspect there's some reluctance to merge it because "just make it public" isn't a great approach to API design :) But if you have time, it might be helpful if you could try your project out with #295 to see if you run into any other issues.

**Comment by audricpod** [comment]
Thanks for this version, it helps, but still needs to add `Reflection.DynamicStateInfos possibleDestinationStates = null` as a new optional parameter for the PermitDynamicIf function in `StateConfiguration`

Looking forward an approbation of your PR and maybe also the modification of the PermitDynamicIf function.

**Comment by vlm---** [comment]
I just came across a need to validate some transitions and still there is no way to set possibleDestinationStates during configuration with PermitDynamicIf method, only with PermitDynamic one.

**Comment by HenningNT** [comment]
@vlm--- I've added possibleDestinationStates to the PermitDynamicIf methods, there should be a new dev package (Stateless.5.0.0-dev-00476) available on nuget shortly,

**Comment by vlm---** [comment]
I have tested the dev package and it is working as expected. I can set possibleDestinationStates and it's reflected in generated graph. Thanks.
