### ISSUE TITLE
TelephoneCallExample is broken

### ISSUE THREAD

**Issue by Deilan** [dotnet-state-machine/stateless#309]
System.ArgumentException
  HResult=0x80070057
  Message=An argument of type System.Int32 is required in position 0.
  Source=Stateless
  StackTrace:
>	Stateless.dll!Stateless.ParameterConversion.Unpack(object[] args, System.Type argType, int index) Line 12	C#
 	Stateless.dll!Stateless.ParameterConversion.Unpack<int>(object[] args, int index) Line 26	C#
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.TransitionGuard.ToPackedGuard.AnonymousMethod__0(object[] args) Line 19	C#
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.TransitionGuard.UnmetGuardConditions.AnonymousMethod__0(Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.GuardCondition c) Line 111	C#
 	[External Code]	
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.TransitionGuard.UnmetGuardConditions(object[] args) Line 110	C#
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.TriggerBehaviour.UnmetGuardConditions(object[] args) Line 49	C#
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.StateRepresentation.GetPermittedTriggers.AnonymousMethod__2(Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.TriggerBehaviour a) Line 290	C#
 	[External Code]	
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.StateRepresentation.GetPermittedTriggers.AnonymousMethod__0(System.Collections.Generic.KeyValuePair<TelephoneCallExample.PhoneCall.Trigger, System.Collections.Generic.ICollection<Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.TriggerBehaviour>> t) Line 290	C#
 	[External Code]	
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.StateRepresentation.GetPermittedTriggers(object[] args) Line 296	C#
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.GetPermittedTriggers(object[] args) Line 129	C#
 	Stateless.dll!Stateless.StateMachine<TelephoneCallExample.PhoneCall.State, TelephoneCallExample.PhoneCall.Trigger>.ToString() Line 503	C#
 	[External Code]	
 	TelephoneCallExample.dll!TelephoneCallExample.PhoneCall.Print() Line 120	C#
 	TelephoneCallExample.dll!TelephoneCallExample.Program.Main(string[] args) Line 15	C#

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {System.ArgumentException: An argument of type System.Int32 is required in position 0.    at Stateless.ParameterConversion.Unpack(Object[] args, Type argType, Int32 index) in c:\Dev-learn\stateless\src\Stateless\ParameterConversion.cs:line 15} | System.ArgumentException

**Comment by iam-black** [comment]
You can find fix in a duplicate issue https://github.com/dotnet-state-machine/stateless/issues/288#issuecomment-435600613

**Comment by HenningNT** [comment]
Should be fixed in 5.1
