### ISSUE TITLE
Clarification: why use parameterized triggers?

### ISSUE THREAD

**Issue by spaasis** [dotnet-state-machine/stateless#310]
Hi, and thanks for a great library!

I had a quick question about the purpose of parameterized triggers. Why would I want to do this (from the Bug example):
```
        public void Assign(string assignee)
        {
            _machine.Fire(_assignTrigger, assignee);
        }
        ...
        private void OnAssigned(string assignee)
        {
            if (_assignee != null && assignee != _assignee)
                SendEmailToAssignee("Don't forget to help the new employee!");

            _assignee = assignee;
            SendEmailToAssignee("You own it.");
        }
```
instead of this:
```
        public void Assign(string assignee)
        {
            _machine.Fire(Triggers.Assign);
           if (_assignee != null && assignee != _assignee)
                SendEmailToAssignee("Don't forget to help the new employee!");

            _assignee = assignee;
            SendEmailToAssignee("You own it.");
        }
```

Seems to me the below is a lot cleaner and requires less hassle, but maybe I'm missing something?

**Comment by HenningNT** [comment]
I think your question is really about "where should I put code that does this/that/or the other?"

We use the parameterized trigger to pass information that goes with the trigger, that are needed by the object to do its job. You can also use structs or classes as triggers, and include the extra information in these.

Keep in mind that the Bug example is rather simple. In a real bug application there could be other conditionals that triggered new transitions, based on the supplied trigger parameters. What would happen if there were a condition on Triggers.Assign that prevented the state to transition to Assigned? 
My preference would be to move the code that make those decisions into the state machine trigger handlers.  

If you can make it work in another way then you are free to do so, just make sure you have good code coverage ;-)

**Comment by spaasis** [comment]
Right, so it's mostly a matter of reference rather than having serious technical implications. I did my implementation using the method described in the OP and it seems to work well for now, but I guess using the parameterized triggers could come in handy in more complicated cases.

I'll close this now so it doesn't crowd the issue list
