### ISSUE TITLE
What's the story on testing classes that use Stateless?

### ISSUE THREAD

**Issue by akamud** [dotnet-state-machine/stateless#313]
I'm using Stateless like this:

```csharp
// a class that is used for easier DI and for encapsulating extra behaviors
public class Something
{
    StateMachine<MyState, MyTrigger> _stateMachine;

   public Something()
   {
       // all my configurations and transitions here
   }

   void AnAction()
   {
       // an action that fires a trigger
   }
}
```

It is pretty much the same scenario as the `PhoneCaller` example.

Now, I want to unit test a few scenarios:
* My `AnAction` method fires the correct trigger
* If my trigger has parameters, that they were correctly passed
* When in State X, a trigger changes the state to Y. That way I can unit test that my machine is correctly configured with all the transitions, and if someone incorrectly changes it, my unit test breaks.
    * I wish to test this with a "shortcut". For example, if I have a state machine with A-B-C-D-E, I want to create a unit test that sets the state machine to D so I can validate that it goes to E without having to come all the way from A-B-C. Just so I can have cleaner tests.
* Test all the side-effects that my "Entries" cause when entering/exiting a State, to validate that my State is correctly configured with the entries necessary

I'm having a hard time writing these tests because I couldn't find a way to observe what is happening inside the machine, or forcing a desired state just for testing purposes. I understand that forcing a state breaks the concept of a state machine, but maybe having a test helper that could be used only on test projects would provide a way of doing that.
Even looking on the tests this project has didn't give me any insights on what I could do to achieve these scenarios easier...

I would like to know what are your thoughts on these scenarios... am I missing something that is already implemented? Is there an easier way to write these kind of tests? Do you think these tests even make sense at all? Do you think it would be possible to have a test helper?

Thanks for providing this great lib ;)

**Comment by HenningNT** [comment]
I understand the frustration, as unit testing can be hard to get right. But it's worth it!

Take a look at the JsonExample, I think you should be able to use a somewhat similar pattern.
When the StateMachine<> is instantiated you can supply any state, and you can start testing from that state. After you've executed the method that should cause a state change, you can Assert to verify that it has.
You can use a mocking framework like NSubstitute to verify that the correct methods were executed by the trigger handler.

**Comment by akamud** [comment]
Thanks for the heads-up about the initial state parameter. That helped.

I was thinking of having something like this to help validate my state machine configuration:

```csharp
stateMachine
    .InState(stateA)
    .CanTransitionTo(stateB)
    .Through(triggerX)
```

Inspecting stateless code, the only place that had all this information was the `StateConfiguration` field, that is private, so I'm not able to achieve that as an extension method without heavy use of reflection.

This "test helper" approach is similar to what `FluentValidation` provide, so it is easier to validate certain aspects of my configuration in a more clean and isolated way. Do you think it makes sense providing something similar to Stateless??

**Comment by spaasis** [comment]
Just a sideline; I found that for validating the state machine, the [DOT graph](https://github.com/dotnet-state-machine/stateless#export-to-dot-graph) is priceless. The generated image can also be shown to non-technical people and confirmed by product owners and other stakeholders

**Comment by HenningNT** [comment]
Maybe you could export the state machine configuration, in much the same way that DOT graph is created, and run the validation on that? That would separate the configuration and executing apart from the validation.
