### ISSUE TITLE
Please add .netstandard2.0 target support

### ISSUE THREAD

**Issue by WeihanLi** [dotnet-state-machine/stateless#314]
accounting to microsoft dotnet open source library guide [here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#net-standard)

✔️ DO start with including a netstandard2.0 target.

Most general-purpose libraries should not need APIs outside of .NET Standard 2.0. .NET Standard 2.0 is supported by all modern platforms and is the recommended way to support multiple platforms with one target.

❌ AVOID including a netstandard1.x target.

.NET Standard 1.x is distributed as a granular set of NuGet packages, which creates a large package dependency graph and results in developers downloading a lot of packages when building. Modern .NET platforms, including .NET Framework 4.6.1, UWP and Xamarin, all support .NET Standard 2.0. You should only target .NET Standard 1.x if you specifically need to target an older platform.

✔️ DO include a netstandard2.0 target if you require a netstandard1.x target.

All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.

**Comment by iancooper** [comment]
@HenningNT It should be fairly easy to convert across to netstandard20 as it would be a superset of the .NET APIs you have used. Whilst I understand the original proposition that low was better i.e. more widely supported  the team made a mess of how they packaged dependencies, so the advice is as above

**Comment by vip32** [comment]
@HenningNT  here's a proper netstandard 2.0 only PR #334

**Comment by HenningNT** [comment]
Closing this, it has been added.
