### ISSUE TITLE
Delay execution of guards until necessary

### ISSUE THREAD

**Issue by myrup** [dotnet-state-machine/stateless#315]
A quick idea for an optimization: Let `GetPermittedTriggers()` only execute guards when iterated over. 

It would allow expressions like the following
```c#
stateMachine.GetPermittedTriggers().FirstOrDefault()?.Fire();
```
without executing all guards involved.

**Comment by myrup** [comment]
Looking at the code, I think the `ToArray` actually is the only thing causing the premature execution. The question then is if it's better to not call it?
https://github.com/dotnet-state-machine/stateless/blob/d50a87ee1e3d8600bbabfb761c3447c14a71604a/src/Stateless/StateRepresentation.cs#L296

**Comment by HenningNT** [comment]
Intriguing!
Have you done any performance evaluation?

**Comment by myrup** [comment]
> Intriguing!
> Have you done any performance evaluation?

None whatsoever, this is completely untested, so there might be other `.ToArray()`s in the way.  It could really be nice to make use of the wonderful delayed execution nature of LINQ. It should be noted that code that previously made assumptions about the full evaluation of the enumerator would need to add `.ToArray()` itself to avoid throwing `InvalidOperation` exception (a la. _collection was modified_).

**Comment by HenningNT** [comment]
This issue is merged, so closing it.
