### ISSUE TITLE
Bouncing to a transitional state and back to original state

### ISSUE THREAD

**Issue by aughey** [dotnet-state-machine/stateless#318]
So this might skirt the line between clever or stupid.  I'm using Stateless to govern character movement.  I have a Jump state that sets an impulse velocity, then needs to immediately go back to whatever the previous state is.

```
 stateMachine.Configure(State.Jump)
            .OnEntry(() => ImpulseVelocity = 1000.0f);
```

To accomplish this need, I store the previous state in a local variable, then bounce back to the previous state immediately after entering the jump state....

 ```
State previousState = State.Init;
stateMachine.OnTransitioned((trans) =>
        {
            previousState = trans.Source;
       });

stateMachine.Configure(State.Jump)
            .OnEntry(() => stateMachine.Fire(Trigger.None))
            .OnEntry(() => ImpulseVelocity = 1000.0f)
            .PermitDynamic(Trigger.None, () => previousState);
```

I use this trick of firing a null trigger OnEntry and transitioning immediately to another state quite often.  This allows for the Entry/Exit behaviors to be run in a transitional state.

The benefit of transitioning back to the previous state in this example is it lets me govern which states can transition to jump, while always knowing which state to go back to.  

I wanted to share this stateful stateless pattern.  However, one possible issue or feature request would be to add a PermitAlways method that would allow for transitional behavior states like this to be made without having to define a null trigger and forcefully fire that trigger into the state machine on OnEntry.  PermitAlways would be like Permit, but wouldn't have a Trigger parameter as a conditional.

**Comment by HenningNT** [comment]
Could you achieve the same using InternalTransition?
Assuming that the jump state doesn't do anything else, I think it would.

**Comment by aughey** [comment]
@HenningNT This helps.  I was not aware of this method.
