### ISSUE TITLE
Queued trigger runs in a separate thread

### ISSUE THREAD

**Issue by all-iver** [dotnet-state-machine/stateless#321]
I'm using Stateless with Unity, and it seems that when I call Fire() from an async OnEntry() handler, the queued trigger runs in a separate thread.  In Unity, UI can only be accessed from the main thread, so this was causing crashes for me.  Changing to FiringMode.Immediate fixes the problem, but is this behavior documented somewhere?  Why does a queued trigger run in a separate thread?  Are there other situations where Stateless will spawn new threads instead of running on the existing thread?

If it matters, I am using a TriggerWithParameters to trigger the async initial state...

```
async Task OnState1Entry() {
    // here we are in the main thread and UI operations succeed
    stateMachine.Fire(State.State2);
}

void OnEnterState2() {
    // this seems to run in a new thread and UI operations fail
}
```

**Comment by oising** [comment]
I don't see how this is an issue in Stateless. Your OnEntry handler is async, so firing may also be async. I think you should be looking at this from the other angle, and instead using a dispatcher to queue operations to be run on the main Unity UI thread. This is how windows forms, wpf etc work. See https://answers.unity.com/questions/305882/how-do-i-invoke-functions-on-the-main-thread.html

**Comment by all-iver** [comment]
I'm pretty sure that in Unity, async/await does not create new threads, although I'm having trouble finding the documentation now.  Something about UnitySynchronizationContext that enforces it...  I was not expecting to be in a different thread, which is why I was confused when this happened with Stateless.  I had written my code assuming I was always in the main thread, and then had to rework it later using FiringMode.Immediate.  I'm not an expert on this stuff though so I'll leave it up to others if they want to just close this issue.

**Comment by uygary** [comment]
> I'm pretty sure that in Unity, async/await does not create new threads, or at least always resumes on the main thread, although I'm having trouble finding the documentation now.

The thing is, there is no guarantee that the task will be running on the same thread. It's up to the scheduler, or even the implementation of the async method itself.
That means, @oising is right in saying that we should handle that possibility while dealing with UI threads.

**Comment by all-iver** [comment]
> The thing is, there is no guarantee that the task will be running on the same thread. It's up to the scheduler, or even the implementation of the async method itself.

I'm confused then.  Why is there no guarantee the task will be running on the same thread?  In Unity I don't have to handle the possibility of being in a new thread just by using async/await, as far as I know.  When you await some code, that code runs synchronously.  Even if you explicitly await a new thread, UnitySynchronizationContext ensures that it should resume in the same thread it started, so you don't have to worry about not being able to make UI calls.  So to me it seems like Stateless must be the cause of the new thread, and that isn't expected (by me) because in general multi-threaded code is more complicated and I'd prefer to avoid it if I can.  However I'd understand if there's a good reason Stateless is doing that, I just was surprised by it and had to rewrite my code.

In the documentation all I can find is:

> Note: while StateMachine may be used asynchronously, it remains single-threaded and may not be used concurrently by multiple threads.

**Comment by all-iver** [comment]
Looking into it more, I guess the reason might be that internally Stateless uses ConfigureAwait(false), which could be causing tasks to resume on a non-main thread?  I only use .NET in Unity and I haven't had to really understand ConfigureAwait(), but it seems like people use ConfigureAwait(false) to prevent users from accidentally forgetting to use await, and therefore calling async library code in a blocking way when they didn't mean to?  But then it leaves the caller in the wrong thread which is unfortunate.  I don't know if what I'm expecting is reasonable or not, or if there's a workaround to get back into the desired context (assuming this is actually the issue).  Feel free to close this issue if this is a won't-fix situation.

**Comment by HenningNT** [comment]
Yes, stateless uses ConfigureAwait(false) internally, which tells the runtime to continue on any available thread.  ConfigureAwait has very little to do with preventing people from forgetting to await Tasks.

As I see it you have a few options
1) Clone stateless, and replace all calls to ConfigureAwait(false) with ConfigureAwait(true).
2) Use the sync flavour of stateless, but wrap Fire with a Task.Run (whatever).ConfigureAwait(true). This allows you to run the state machine async, but you have control of the context.
3) Only use the sync version of stateless.

Please note that I'm not an expert on async programming, and I might get things wrong.

**Comment by nick4fake** [comment]
Looks like it was implemented:
https://github.com/dotnet-state-machine/stateless/blob/95096e57a0601e81e14138da51f79c35cd126206/src/Stateless/StateMachine.cs#L95
