### ISSUE TITLE
Is this intended behavior (and usage) of TriggerWithParameters?

### ISSUE THREAD

**Issue by OmnipresentObserver** [dotnet-state-machine/stateless#323]
So I have been experimenting with Stateless for the past week.  I was curious if there were a way to either share the ```TriggerWithParameter``` triggers between multiple classes that represented the objects which implement a specific state's behavior (e.g. in the JIRA example, each state would be its own object) or create the same ```TriggerWithParameter``` object in multiple places.  The shared behavior between the states became rather ugly with multiple implementations of the constructor that took varying amounts of ```TriggerWithParameter``` objects.  I then attempted to create the ```TriggerWithParameter``` objects in multiple places and ran in to the error stating that the ```TriggerWithParameter``` object had already been instantiated.

```
public class InitState : BaseState
{
   public virtual void Configure(StateMachine<State, Trigger> stateMachine)
   {
      var completed = stateMachine.SetTriggerWithParameters<StateData>(Trigger.Complete);
      stateMachine.Configure(State.Init)
         .Permit(Trigger.Complete, State.Running)
         .OnEnter(() = > 
         {
            // Initialization logic
            stateMachine.Fire(completed, new StateData(...));
         });
   }
}

public class RunningState : BaseState
{
   public virtual void Configure(StateMachine<State, Trigger> stateMachine)
   {
      var completed = StateMachine.SetTriggerWithParameters<StateData>(Trigger.Complete); // Fails :(
      // ...
   }
}
```

All hope was lost...or so I thought.  Then I tried manually creating TriggerWithParameter objects and using them to transition between states.

```
public static class StateMachineExtensions
{
   // Implemented for all TArg0... implementations of TriggerWithParameters
   public static StateMachine<TState, TTrigger>.TriggerWithParameters<TData> GenerateTriggerParameters<TState, TTrigger, TData>(this StateMachine<TState, TTrigger> machine, TTrigger trigger)
   {
      return new StateMachine<TState, TTrigger>.TriggerWithParameters<TData>(trigger);
   }
}

public class InitState : BaseState
{
   public virtual void Configure(StateMachine<State, Trigger> stateMachine)
   {
      var completed = stateMachine.GenerateTriggerParameters<State, Trigger, StateData>(Trigger.Complete);
      stateMachine.Configure(State.Init)
         .Permit(Trigger.Complete, State.Running)
         .OnEnter(() = > 
         {
            // Initialization logic
            stateMachine.Fire(completed, new StateData(...));
         });
   }
}

public class RunningState : BaseState
{
   public virtual void Configure(StateMachine<State, Trigger> stateMachine)
   {
      var completed = StateMachine.GenerateTriggerParameters<State, Trigger, StateData>(Trigger.Complete); // Now it's happy and I have a trigger that takes a StateData object
      
      stateMachine.Configure(State.Running)
         .Permit(Trigger.Stop, State.Closing)
         .OnEntryFrom(completed, (state) =>
         {
            // Called when InitState transitions
         }); 
   }
}
```

From this, I was able to transition from the ```State.Init``` to ```State.Running``` by using two separate TriggerWithParameter objects.  As you can see from the second example above, I was able to create two TriggerWithParameter objects with the same arguments and trigger and use them in separate classes, one for the firing of the trigger and the other to be used within the ```OnEntry``` of another state.

As the title asks, is this intended behavior?  Is this acceptable behavior that allows me to create the same TriggerWithParameter object in separate files, but use it as if it were one?

**Comment by HenningNT** [comment]
"As the title asks, is this intended behavior?"
I'd say that it is accidentally intended behaviour ;-) It's a bit like you are bending the rules, and found a soft spot were you made a loophole.

Is it acceptable?
I'd say that if it works for you, then it's acceptable.
However, it might not work with future revisions of the library…
