### ISSUE TITLE
.net core 3 support

### ISSUE THREAD

**Issue by j209** [dotnet-state-machine/stateless#324]
Hi
Is there any plan for .net core 3.0 and above support?

**Comment by dodyg** [comment]
I think stateless should just work for .NET Core 3.0 since it supports .NET Standard 1.0.

**Comment by dodyg** [comment]
Related https://github.com/dotnet-state-machine/stateless/issues/314

**Comment by HenningNT** [comment]
Do you mean specific .net-3-core-only features?

**Comment by vip32** [comment]
here's a proper netstandard 2.0 only PR #334

**Comment by thompcd** [comment]
examples confirmed to work using 3.1 as of 627304ec65fa6f546ec6c93a5299a5e20422bbf2

**Comment by HenningNT** [comment]
Closing this, as I think it is covered in latest release.
