### ISSUE TITLE
Using objects as states or trigger

### ISSUE THREAD

**Issue by Sunslash** [dotnet-state-machine/stateless#326]
Hello,

So, I would like to use class instances for the states and transitions of the state machine. I really have a hard time imagining how it would work and what the code would look like.
I know there have been multiple questions on this subject ( #234, #317 ), but I have yet to find a comprehensive example. 

What would be a minimal working code?

**Comment by HenningNT** [comment]
How about this:
https://github.com/HenningNT/ObjectsAsStates/blob/master/ObjectsAsStates/ObjectsAsStates/Program.cs

I think it has enough to get you going. HTH!

**Comment by Sunslash** [comment]
Thanks, this is exactly what I needed, and it is actually much simpler than I thought it would be.

Would it be a good idea to add a minimal example in the stateless example folder ?
