### ISSUE TITLE
Trigger as state mutator parameter

### ISSUE THREAD

**Issue by maiorfi** [dotnet-state-machine/stateless#327]
Hi.

Would it be possible to have trigger reference as a parameter of state mutator delegate in state machine ctor?

This way I could for example persist previous states as well as related fired triggers into a state machine entity.

Thanks!

**Comment by HenningNT** [comment]
Yes, I believe that is possible. In fact, I think the examples used to have that, until I simplified them...

**Comment by maiorfi** [comment]
Examples? Isn't mutator delegate defined in core code? Anyway, could you please help me in finding the commit where trigger parameter was removed?

**Comment by HenningNT** [comment]
The old version of the BugExample called the constructor like this:
_machine = new StateMachine<State, Trigger>(() => _state, s => _state = s);

The old vs new:
https://github.com/dotnet-state-machine/stateless/commit/a68abcac0af2f9b7b6c898331ffe1ff12e66dada?diff=split


Was that what you were looking for?

**Comment by HenningNT** [comment]
I had look, and not it's not available without rewriting.
I suggest storing the trigger in a variable, and look it up when running the state mutator.
