### ISSUE TITLE
[Question] Can this library be used in multi-level approval?

### ISSUE THREAD

**Issue by whizkidwwe1217** [dotnet-state-machine/stateless#329]
Use Case:

I need a library that can be used for multi-level approval process. For example, an employee can file and submit a time-off request and it will go to different level of approvals of some managers of different hierarchy.

Employee time-off request states can be:
**Draft, Submitted, Approved, Pending or Rejected**

Initially the state is **Draft** and the employee can submit it to approvers. Then the state will transition to **Submitted**.

The request will go through some approvers of different levels:
Example:

1st level approver - John
2nd level approvers - Peter OR Joseph
3rd level approvers - Kyla AND Josh
Final approver - Jack the boss

John first approve the request then either Peter or Joseph can approve next. Then both Kyla and Josh must approve the request before it gets to Jack, the final approver. After all the approver approves the request, then the state of the request becomes **Approved**. The state of the request remains **Pending** when not all of the approvers has approved the request yet. If one of them rejects the request, the state becomes **Rejected**.

**Comment by HenningNT** [comment]
A state machine can help with those flows, but it's only a small part of the business logic that will make something like this happen. stateless can do the state transitions, and call any code that needs to be called.
