### ISSUE TITLE
Error invoking method within .OnExit

### ISSUE THREAD

**Issue by MartyBJones** [dotnet-state-machine/stateless#331]
I need to invoke a service method within the .OnExit() method.  The service call I am making is an async method so I need to wait on it to complete.

.OnExit(async s =>
{
    // if we are transitioning to Survey then save the changes.
    if (s.Destination == Step.Survey)
       {
           request.OnboardingRequestId = await onboardingService.CreateOnboarding(request);
        }
});

I get the following error: "An asynchronous module or handler completed while an asynchronous operation was still pending.".   I had to make the lambda expression async so that I could await the service result but that seems to be causing the error.

**Comment by gjlubbertsen** [comment]
It seems that there is a .OnExitAsync(() => Task.Run(() => test = "foo"))

[AsyncActionsFixture.cs](https://github.com/dotnet-state-machine/stateless/blob/2632bd4e535b8acc9e9b8269ef546037c824db71/test/Stateless.Tests/AsyncActionsFixture.cs)

**Comment by HenningNT** [comment]
@MartyBJones Is this a bug, or does the suggestion from @gjlubbertsen help?
