### ISSUE TITLE
.NetStandard 2.1 support

### ISSUE THREAD

**Issue by abuassar** [dotnet-state-machine/stateless#332]
I have a .netstandar2.1 project, and although stateless package has no dependencies yet it asks for a huge number of packages to be installed:

`
Installing:
Microsoft.NETCore.Platforms.1.1.0

Microsoft.NETCore.Targets.1.1.0

Microsoft.Win32.Primitives.4.3.0

NETStandard.Library.1.6.1

runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.native.System.4.3.0

runtime.native.System.IO.Compression.4.3.0

runtime.native.System.Net.Http.4.3.0

runtime.native.System.Security.Cryptography.Apple.4.3.0

runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple.4.3.0

runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0

Stateless.4.2.1

System.AppContext.4.3.0

System.Buffers.4.3.0

System.Collections.4.3.0

System.Collections.Concurrent.4.3.0

System.Console.4.3.0

System.Diagnostics.Debug.4.3.0

System.Diagnostics.DiagnosticSource.4.3.0

System.Diagnostics.Tools.4.3.0

System.Diagnostics.Tracing.4.3.0

System.Globalization.4.3.0

System.Globalization.Calendars.4.3.0

System.Globalization.Extensions.4.3.0

System.IO.4.3.0

System.IO.Compression.4.3.0

System.IO.Compression.ZipFile.4.3.0

System.IO.FileSystem.4.3.0

System.IO.FileSystem.Primitives.4.3.0

System.Linq.4.3.0

System.Linq.Expressions.4.3.0

System.Net.Http.4.3.0

System.Net.Primitives.4.3.0

System.Net.Sockets.4.3.0

System.ObjectModel.4.3.0

System.Reflection.4.3.0

System.Reflection.Emit.4.3.0

System.Reflection.Emit.ILGeneration.4.3.0

System.Reflection.Emit.Lightweight.4.3.0

System.Reflection.Extensions.4.3.0

System.Reflection.Primitives.4.3.0

System.Reflection.TypeExtensions.4.3.0

System.Resources.ResourceManager.4.3.0

System.Runtime.4.3.0

System.Runtime.Extensions.4.3.0

System.Runtime.Handles.4.3.0

System.Runtime.InteropServices.4.3.0

System.Runtime.InteropServices.RuntimeInformation.4.3.0

System.Runtime.Numerics.4.3.0

System.Security.Cryptography.Algorithms.4.3.0

System.Security.Cryptography.Cng.4.3.0

System.Security.Cryptography.Csp.4.3.0

System.Security.Cryptography.Encoding.4.3.0

System.Security.Cryptography.OpenSsl.4.3.0

System.Security.Cryptography.Primitives.4.3.0

System.Security.Cryptography.X509Certificates.4.3.0

System.Text.Encoding.4.3.0

System.Text.Encoding.Extensions.4.3.0

System.Text.RegularExpressions.4.3.0

System.Threading.4.3.0

System.Threading.Tasks.4.3.0

System.Threading.Tasks.Extensions.4.3.0

System.Threading.Timer.4.3.0

System.Xml.ReaderWriter.4.3.0

System.Xml.XDocument.4.3.0
`
please support .netstandrard 2.1 so I don't need to install all these packages

**Comment by abuassar** [comment]
I submitted a pull-request:
https://github.com/dotnet-state-machine/stateless/pull/333

**Comment by vip32** [comment]
Netstandard 2.0 should suffice. 2.1 not needed as this lib does not use any of its features.

**Comment by vip32** [comment]
here's a proper netstandard 2.0 only PR #334

**Comment by HenningNT** [comment]
Closing this, thanks for the contributions!
