### ISSUE TITLE
Cannot observe whether a transition is in progress

### ISSUE THREAD

**Issue by bitbonk** [dotnet-state-machine/stateless#336]
With the current desgin of the APIs it does not seem to be possible to observe, what state transition is currently in progress. In a somewhat generic UI that is supposed to work for many different state machine configurations I would like to display that a certain trigger has been fired (and a `OnExitAsync` action has not yet completed) unit the target state has been reached.

I suppose that was a deliberate design decision? If, so could you explain why?

**Comment by HenningNT** [comment]
While a state machine is transitioning from one state to the other, the state machine might be in a indeterminate / unfinished / incoherent state. For this reason the state transition must be atomically executed, and the state machine library cannot present the state machine as "somewhere in between". If it could, then that would be another state. Only the designer / designer of the state machine defines the states, not the state machine library.

If you want this functionality I suggest you wrap the state machine in a class that allow debug info to be captured before executing the Fire method.
