### ISSUE TITLE
Release concerns

### ISSUE THREAD

**Issue by acoats2** [dotnet-state-machine/stateless#337]
I really love this amazing library and appreciate all of the contributors hard work.

I noticed the 4.3.0 release was published to nuget.  I went to see what changed and found no release notes.  No biggie, so, I checked the repo to see what changes were made.

I'll admit, I was surprised to find it appears the release was created from the dev branch (it's the only branch that has recently changed), but even more so there's no way to coordinate the code from 4.3.0 to the repo as the commit isn't tagged.  

The build indicator in the readme links to appveyor that shows a lot of builds, but no new releases.  If I switch to the appveyor dev builds, I can see multiple builds create a Stateless.4.3.0.nupkg.

Perhaps I've missed something, but right now I'm hesitant to upgrade.  Any thoughts would be appreciated.

**Comment by vip32** [comment]
#334 is what changed, netstandard 2.0 support.

**Comment by HenningNT** [comment]
I understand your concerns, I think it's important to have traceability. I think I forgot to tag the latest release :-(
I believe the latest version should be OK to use, it's 4.4.0. The change.log has been updated, and contains a list of the changes done.

**Comment by acoats2** [comment]
Thank you very much!
