### ISSUE TITLE
List Triggers and their Next States from current State

### ISSUE THREAD

**Issue by Korayem** [dotnet-state-machine/stateless#34]
I want to generate list of Triggers and their Next States from current state.

Just like you exposed StateMachine.PermittedTriggers which returns list of allowed Triggers from current State, why don't you return IEnumerable NextStates.

Or there is a method that I can convert a Start State and Trigger to Next States cause I am still new :)

**Comment by HenningNT** [comment]
I would like to know why you ask. You yourself generate the state machine, and therefore already know which triggers are permitted and what state they transition to.

If you put all your Triggers in a list then you can compare the result of PermittedTriggers to the List, and generate a list of possible "Next" States. However, the same trigger can have a different destination State for different source States, so you might want to use each Trigger for a single transition only.

**Comment by HenningNT** [comment]
You could also store the destination State inside the Trigger class, so when you get the list of permitted triggers you can easily make list of possible destination States.

**Comment by nblumhardt** [comment]
@Korayem dynamic triggers (that use a function to compute the next state) make this difficult; there's a recent change adding a `ToDotGraph()` method that provides some introspection.

**Comment by Korayem** [comment]
What I am trying to achieve is to render buttons based on current state showing Trigger name with associated target State

@HenningNT ah nice! Using generics is the beauty of stateless. That will probably solve my issue :)

@nblumhardt after posting I looked up ToDotGraph() indeed and discovered that what I need is to access internal private _stateConfiguration dictionary for what I am looking for. I understand the predicament that rises once you think of it from Dynamic Triggers perspective too.

**Comment by rustybox** [comment]
> internal private _stateConfiguration ...
> But the lack of it is quite hindering ...

Related to #54, protected would allow sub classing to achieve bespoke goals

**Comment by nblumhardt** [comment]
I think this one might be a bit outside of what we're aiming to do with Stateless, but thanks for all of the information. Cheers!
