### ISSUE TITLE
StateMutator is called multiple times with the same state

### ISSUE THREAD

**Issue by MiroslavMikus** [dotnet-state-machine/stateless#342]
Hi, I was doing some prototyping for my work and come across this unexpected behaviour. Since it's working in the version 4.2.1 just fine and occurs since version 4.3.0 I assume it's a bug.

![image](https://user-images.githubusercontent.com/29312172/70603935-ec16a300-1bf7-11ea-934a-b0ab9a9893fd.png)

I have the full example as well, you can get it [here](https://github.com/MiroslavMikus/Exercies.Stateless/blob/master/Exercise.Stateless.Car/Car.cs)

Great lib and thanks in advice

**Comment by WilkoSki** [comment]
+1 on that, we are seeing the same behaviour

**Comment by amphasis** [comment]
+1 the same issue on our project, it appeared after updating to 4.3.0

**Comment by HenningNT** [comment]
Will be fixed in 4.4.
Fixed now in dev-branch.
