### ISSUE TITLE
[Feature] Make OnTransitionedAsync and OnUnhandledTriggerAsync return a task

### ISSUE THREAD

**Issue by velocitysystems** [dotnet-state-machine/stateless#344]
**Feature Request**
When using methods such as `OnTransitionedAsync` and `OnUnhandledTriggerAsync`, it would be useful if these returned a `Task` to make them awaitable.

This would greatly help when unit testing an asynchronous state machine.
Note: All other async methods in [StateMachine.Async.cs](https://github.com/dotnet-state-machine/stateless/blob/master/src/Stateless/StateMachine.Async.cs) already return a `Task`.

**Comment by uygary** [comment]
The OnTransitionedAsync method isn't actually an async method, and I don't think it should be.
That being said, I believe it should've been named OnTransitioned as an overload of the existing OnTransitioned method since it's not an async method itself.

**Comment by 1Cor125** [comment]
I get what @uygary is saying. It is just setting a callback so there is no real return value needed. Even if the callback returns a Task it wouldn't make sense to return only the first one. I also agree that the naming is misleading. It could/should have been kept as an overload for `OnTransitioned`. The use case however remains for having something that you can await to determine when transitions have taken place but it would probably need to return an `IObservable<T>` for N number of transitions. Since I don't know that Stateless is ever going to take a dependency on `System.Reactive` perhaps the user of the API could write a helper method using `System.Reactive` to pipe the transitions back out through an observable.

Something like this:
```
 public static IObservable<(MyState destinationState, MyTrigger trigger)> ObserveTransitionsAsync(this StateMachine<MyState, MyTrigger> stateMachine)
        {
            var transitions = new Subject<(MyState destinationState, MyTrigger trigger)>();

            // This could be synchronous too.
            stateMachine.OnTransitionedAsync(async transition =>
            {
                await Task.Yield();
                transitions.OnNext((transition.Destination, transition.Trigger));
            });

            return transitions.AsObservable();
        }
```
Then you could subscribe to it as per your requirements:
```
await stateMachine.ObserveTransitionsAsync().Take(3);
await stateMachine.ObserveTransitionsAsync().FirstOrDefaultAsync();
```

**Comment by uygary** [comment]
Now I see what exactly you're after, and I also see the value in having such a feature. It would definitely be useful in certain cases.

I have a concern regarding this though:
I'd be extremely wary about adding new dependencies to Stateless. From my perspective, a state machine is such a core dependency in an application, it should ideally have as few as possible dependencies. So many components in so many applications end up being depending on the state machine, every single dependency being added would become a source of headache and possibly create a maintenance hell in the long run.
It's my humble opinion that each and every dependency to be added to Stateless should be carefully considered and weighed for its actual benefit vs the dependency tree it pulls in.

We could, however, expose this feature by building our own service that would subscribe to state changes on Stateless (via `OnTransitioned`) and expose an observable collection. That shouldn't be too difficult, unless I'm being too naive.
In fact, this could be an extension package for Stateless, kept on par with the latest versions of both Stateless and Reactive. That way, it would be an optional dependency consumable by folks who actually need the functionality.

**Comment by juliusl** [comment]
I've been using this pattern recently with Rx.NET/Stateless, to create a base class "ObservableStateMachine<TState, TTrigger>". It works pretty nice however one thing that would be kind of great was if there was a way to expose internal transitions as well. 

The justification being that you can use the Rx.NET streams, to drive the Fire/FireAsync of the StateMachine, so exposing internal transitions in the state just gives you that much more power in the observable stream to filter on. I'll probably tinker with this and offer up a PR for the configuration part at least.

**Comment by amullins** [comment]
> I've been using this pattern recently with Rx.NET/Stateless, to create a base class "ObservableStateMachine<TState, TTrigger>". It works pretty nice however one thing that would be kind of great was if there was a way to expose internal transitions as well.
> 
> The justification being that you can use the Rx.NET streams, to drive the Fire/FireAsync of the StateMachine, so exposing internal transitions in the state just gives you that much more power in the observable stream to filter on. I'll probably tinker with this and offer up a PR for the configuration part at least.

@juliusl I am going down the same route of using Rx.NET with Stateless and am curious whether you have a working example of your `ObservableStateMachine<TState, TTrigger>` class that could be shared?

**Comment by juliusl** [comment]
@amullins Just got back from vacation, I can definitely share a working example if you still need

**Comment by mpinkus** [comment]
@amullins, I would live to see a working observable state machine example, anything to share? I'm implementing a state machine in a reactiveui viewmodel and could use the help/mentoring, i'm new to reactive programming.

**Comment by HenningNT** [comment]
If there is a way to publish this in an "extension" package to Stateless, then I'd very much like to do so.
This way we keep the main functionality without dependencies, and we can add functionality (and dependencies) that are only interesting to some users.
