### ISSUE TITLE
[Feature] `.BeforeTransition()` and `.AfterTransition()`

### ISSUE THREAD

**Issue by Brondahl** [dotnet-state-machine/stateless#347]
As far as I can tell, the `.OnTransition()` "event" fires _after_ `.OnExit()` methods have been called, and _before_ `.OnEntry()` methods have been called.

It would be really useful (esp. for debugging logging, for example) to be able to track "I'm about to start calling `OnExit` methods for this transition", and "I'm about to start calling `OnEntry` methods for this transition.

It also feels like it ought to be quite easy to add to the API?

Is this something you'd be willing to add? (and/or would accept a PR for?)

**Comment by HenningNT** [comment]
I understand that this feature would be useful to some. But you can accomplish the same by adding logging to OnExit and OnEntry event handler. You also control access to the Fire method(s), so you can add logging before those calls.

Anything that is added will have to be maintained, so I suggest only adding new functionality that is completely missing.
