### ISSUE TITLE
[Feature] Shortest Path to targetState

### ISSUE THREAD

**Issue by earthlion** [dotnet-state-machine/stateless#349]
Hi there

Would it be possible to implement a bfs shortest path algorithm that gives out a list of triggers to get to a target state? Spit out null if already on the state and spit out an exception theres no possible path?

**Comment by HenningNT** [comment]
Yes, I think that it would be possible to do this. You can get state information from the state machine, which it can output as a graph. This information could be parsed, and a path can be found.

However, I do not consider it a job that the state machine necessarily should be doing. Maybe someone would like to do an extension?

**Comment by uygary** [comment]
I personally agree that this isn't a job for the state machine.

**Comment by earthlion** [comment]
Decided to release my solution from a year back.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Stateless.Graph;

namespace Stateless
{
    public static class StatelessExtension
    {
        /// <summary>
        /// Returns all destination states (w/o internal transitions)
        /// </summary>
        /// <typeparam name="TState">Current machine</typeparam>
        /// <param name="target">Target State</param>
        /// <returns></returns>
        public static IEnumerable<TState> GetAdjecencies<TState, TTrigger>(this StateMachine<TState, TTrigger> machine, TState target)
        {
            return machine.GetInfo().States.Where(t => t.UnderlyingState.Equals(target)).SelectMany(x => x.FixedTransitions).Select(s => (TState)s.DestinationState.UnderlyingState).Where(a => !a.Equals(target));
        }

        /// <summary>
        /// Find a trigger to transition from A to B (without being on it)
        /// </summary>
        /// <typeparam name="TState"></typeparam>
        /// <typeparam name="TTrigger"></typeparam>
        /// <param name="machine">Current machine</param>
        /// <param name="current">Current state</param>
        /// <param name="target">Target state</param>
        /// <returns>A trigger</returns>
        public static object GetTrigger<TState, TTrigger>(this StateMachine<TState, TTrigger> machine, TState current, TState target)
        {
            var currentState = machine.GetInfo().States.Where(t => t.UnderlyingState.Equals(current)).FirstOrDefault();

            if (currentState == null)
                return null;

            var targetState = currentState.FixedTransitions.Where(x => x.DestinationState.UnderlyingState.Equals(target)).FirstOrDefault();

            if (targetState == null)
                return null;

            return targetState.Trigger.UnderlyingTrigger;
        }

        /// <summary>
        /// Find a path defined by triggers to the target state
        /// </summary> 
        /// <typeparam name="TState"></typeparam>
        /// <typeparam name="TTrigger"></typeparam>
        /// <param name="machine"></param>
        /// <param name="target"></param>
        /// <returns>A list of triggers</returns>
        public static IEnumerable<TTrigger> ShortestPath<TState, TTrigger>(this StateMachine<TState, TTrigger> machine, TState start, TState destination)
        {
            // Return null if either node is null or if they're the same node
            if (start == null || destination == null)
                return null;

            // Already on it
            if (destination.Equals(start))
                return null;

            // Using a queue for our BFS
            LinkedList<TState> toVisit = new LinkedList<TState>();

            // Track the parents so that we can reconstruct our path
            Dictionary<object, object> parents = new Dictionary<object, object>();

            // Initialize the BFS (Start here)
            toVisit.AddFirst(start);
            parents[start] = null;

            // Keep going until we run out of nodes or reach our destination
            while (toVisit.Count > 0)
            {
                TState curr = toVisit.First();
                toVisit.RemoveFirst();

                // If we find the node we're looking for then we're done
                if (curr.Equals(destination))
                {
                    break;
                }

                // Load all children
                var children = machine.GetAdjecencies(curr);

                // If the current node doesn't have children, skip it
                if (children == null)
                {
                    continue;
                }

                // Add all the children to the queue
                foreach (TState state in children)
                {
                    if (!parents.ContainsKey(state))
                    {
                        toVisit.AddLast(state);
                        parents[state] = curr;
                    }
                }
            }

            // If we couldn't find a path, the destination node won't have been
            // added to our parents set
            if (!parents.ContainsKey(destination))
                return null;

            // Create the output list and add the path to the list (Nodes)
            List<object> stateList = new List<object>();
            object n = destination;
            while (n != null)
            {
                stateList.Insert(0, n);

                n = parents[n];

            }

            // Convert stateList to actionable triggerList
            List<TTrigger> triggerList = new List<TTrigger>();
            TState currentState = start;

            foreach (TState targetState in stateList)
            {
                if (targetState.Equals(start))
                    continue;

                // Get trigger to targetState
                var trigger = machine.GetTrigger(currentState, targetState);

                if (trigger != null)
                {
                    triggerList.Add((TTrigger)trigger); // Add to triggerList
                    currentState = targetState; // Virtually switch current states
                }
                else
                    return null; // Path does not exist
            }

            return triggerList;
        }
    }
}
`
