### ISSUE TITLE
PermitIfElse

### ISSUE THREAD

**Issue by rbdb** [dotnet-state-machine/stateless#35]
Given PermitIf takes a Boolean guard clause, it would be useful to have a PermitIfElse function:

PermitIfElse(trigger, stateIfTrue, stateIfFalse, Func<bool> guard)

**Comment by rabbal** [comment]
+ 1

**Comment by SirRufo** [comment]
You are looking for `PermitDynamic`

**Comment by rabbal** [comment]
@SirRufo  Thank you.
