### ISSUE TITLE
PermitIf guard with desired transition

### ISSUE THREAD

**Issue by gnimor** [dotnet-state-machine/stateless#350]
Perhaps I missed something, but I am looking for a way to provide the trigger for the desired transition to the guard method:

.PermitIf(PlayerTrigger.PlayBackward, PlayerState.Playing, () => CanPlay())

The idea behind is to share a guard function for multiple "PermitIf" calls.

**Comment by HenningNT** [comment]
I'm afraid that's not supported, but there is a workaround, I think. I think you could use the parameterized trigger, and pass the trigger as the parameter :-D

But I strongly suggest making one guard for each trigger, Even if the code is more or less the same.

I'm sure you've heard about the Single Responsibility Principle?
