### ISSUE TITLE
[Question] OnEntryAsync and ChangeState

### ISSUE THREAD

**Issue by dazinator** [dotnet-state-machine/stateless#352]
I'm trying to configure a state, such that when this state is entered, some logic runs, and then automatically transitions on to another state.

The problem I am having is that when this state is entered, and when OnEntry() runs, the state machine still reports it's current state as the previous state. During OnEntry() when I then fire the trigger (which is permitted for the state being entered) to transition to the next state, this causes an exception because it says the trigger I am firing is not valid for the current state.

Am I doing something wrong, is this behaviour expected? What's the best way to configure a state that can run some logic and then increment to another state?

Here is roughly my state machine configuration to demonstrate what I am trying to do:

```

 stateMachine.Configure(States.Down_CreateQueues)
                    .SubstateOf(States.Down)                    
                    .Permit(Triggers.QueuesCreated, States.Up)
                    .Permit(Triggers.QueuesFailed, States.Down_FailedQueues)
                    .OnEntryAsync(async () =>
                    {
                        try
                        {
                               // run some logic to create queues and then:
                                stateMachine.Fire(Triggers.QueuesCreated);
                        }
                        catch (Exception ex)
                        {                           
                            // oh dear there was a problem go to failed state so user can retry.
                            stateMachine.Fire(Triggers.QueuesFailed);
                            throw;
                        }
                    });

 stateMachine.Configure(States.Down_FailedQueues)
                    .SubstateOf(States.Down)                   
                    .Permit(Triggers.CreateQueues, States.Down_CreateQueues);

```

Problem comes when state machine is in `Down_FailedQueues` state, and I do:

```
           await stateMachine.ChangeStatusAsync(Triggers.CreateQueues);
```

**Comment by dazinator** [comment]
This was me being stupid. I was using a custom function for state persistence, and that had a problem that was returning an outdated value. This is why OnEntry and OnActivate things were thrown off.

**Comment by HenningNT** [comment]
Good to see you figured it out!
