### ISSUE TITLE
[Question] - Confused over Activate() and ActivateAsync()

### ISSUE THREAD

**Issue by dazinator** [dotnet-state-machine/stateless#354]
I have a fairly simple state machine with 3 states - Up, Down, and Down_Disabled.
Down_Disabled is a substate of Down.

I have included the full definition below.
I am seeing some odd behaviour. When I transition from Up to Down_Disabled, the `OnActivateAsync()` handler for Down_Disabled state doesn't fire. When I transition from `Down_Disabled` back to `Up` the `OnActivate() handler always fires. 

What is the deal here - is OnActivate() and OnActivateAsync meant to fire on every state transition or not? I kind of though that the OnActivate() methods would only run for the initial state, when calling `await _stateMachine.ActivateAsync()` but it seems like they also run during ordinary state transitions, but I can't find a consistent pattern for when they fire as per the above.

Here is how my state machine is built:
```
    protected override Func<Task<StateMachine<Statuses, Triggers>>> InitialiseStateMachineAsync()
        {
            return new Func<Task<StateMachine<Statuses, Triggers>>>(async () =>
            {
                var stateMachine = new StateMachine<Statuses, Triggers>(Statuses.Down);

                stateMachine.Configure(Statuses.Down)
                    .Permit(Triggers.Enable, Statuses.Up)
                    .Permit(Triggers.Disable, Statuses.Down_Disabled)
                    .OnActivateAsync(async () =>
                     {
                        // using on activate here because when Down is our initial state, and we ActivateAsync the state machine, we want this to roll forward to an appropriate state based on current configured value - IsEnabled. I expect this to run when await _stateMachine.ActviateAsync() is called?
                         if (IsEnabled())
                         {
                             await stateMachine.FireAsync(Triggers.Enable);
                         }
                         else
                         {
                             await stateMachine.FireAsync(Triggers.Disable);
                         }
                     })
                    .OnEntry(() => {
                        _logger.LogInformation("down.");                    
                    });

                stateMachine.Configure(Statuses.Down_Disabled)
                    .SubstateOf(Statuses.Down)
                    .Permit(Triggers.Enable, Statuses.Up)
                    .OnActivateAsync(async () =>
                    {
                       // this method is only ever fired once even if we transition from Up into this.
                        if (IsEnabled())
                        {
                            await stateMachine.FireAsync(Triggers.Enable);
                        }
                        else
                        {
                            _logger.LogWarning("Not enabled");
                        }
                    });

                stateMachine.Configure(Statuses.Up)
                    .Permit(Triggers.Disable, Statuses.Down_Disabled)
                    .OnActivate(() =>
                    {
                        _logger.LogInformation("This seems to always run on every transition from Down_Disabled unlike the other  way - when we go from here to Down_Disabled that one doesn't run again..");
                    })
                    .OnEntry(() =>
                    {
                        _logger.LogInformation("runs as i'd expect.");
                    });


                await stateMachine.ActivateAsync(); // expecting OnActivate handler to run for the initial state..
                return stateMachine;
            });
        }

        private bool IsEnabled() => _options.CurrentValue.Enabled; // this value can be changed at runtime from outside

```

**Comment by HenningNT** [comment]
I'm afraid that OnActivate/OnActivateAsync is broken. Or at least it's not implemented in a way that makes sense to me.
I think that Activate should only be called by the user, when activation is required. The way it is implented now, it's supposed called on every state transition. Just like OnEntry... Which makes it another entry action, which I feel is redundant.

To work around this problem I suggest adding a state that is only used as an initial state, and use Activate to trigger a state change to Down.

There was a bit of discussion about Activation in issue #177.

**Comment by dazinator** [comment]
@HenningNT - I agree with your conclusion, having OnActivate() fire on every state transition seems redundant given that's what OnEntry is for. If OnActivate was meant to solve the problem of being able to run some logic when the state machine was restored / initialised into a given state, then the current implementation does seem broken as we can longer actually use it for that purpose. 

It seems like perhaps we can fix this?

**Comment by HenningNT** [comment]
I agree with your Activation expectations, that is the behaviour I'd like to see. I would like to fix it... It would be a breaking change, so we'd need to go to 5.0.

It there are no objections from the rest of the @dotnet-state-machine/reviewers , I could update and merge in the branch I made some time ago. 
https://github.com/dotnet-state-machine/stateless/commit/90cce62966012b8703ffdce34a55784e45d57fe2

**Comment by HenningNT** [comment]
I've created a PR: #356
