### ISSUE TITLE
[Question] Queued FireMode Behavior

### ISSUE THREAD

**Issue by OmnipresentObserver** [dotnet-state-machine/stateless#357]
I have been running into issues with Stateless where my state machine will reach the 'FireAsync' call, but the state will forever be stuck and no transition occurs.  I'm curious how the Queue FireMode is supposed to work.  From my cursory glance through the source code, the only place I see handling queued transitions is within the 'InternalFireQueuedAsync' method.  In the following hypothetical, how is the state machine supposed to resolve the flow?

* State Machine is currently firing some transition (we'll call this FirstFire)
* Another FireAsync is called before the first transition is complete (we'll call this SecondFire)
* The SecondFire transition is then enqueued to the '_eventQueue' as expected

What will process that event queue if no further FireAsync methods are called?  As mentioned, the only place I see the event queue dequeuing any queued events is from within the InternalFireQueuedAsync method.  Does the completion of one transition cause another FireAsync method to be called, which will then execute the while loop that exhausts the event queue?

**Comment by OmnipresentObserver** [comment]
For more specifics into my own implementation, I have multiple classes that each represent a separate state of my overall state machine.  My state machine simply handles the connection to a server; from ensuring the X.509 certificate is present (for initial connection) all the way to handling a sudden disconnect.

Each State class will execute some logic for its associated behavior and the last thing that happens is a call to FireAsync.  The execution logic is all handled within a call stack that originates from the 'OnEntryFromAsync' actions.  For a state like 'Running', my state machine will initially pull all data from the server (because we may have just recovered from a disconnect and need to refresh stale data) in the form of ~6 separate server calls.  During this time, if a disconnection happens, the disconnection callback is executed which inevitably triggers a 'FireAsync' call to the 'Recovering' State.  Since the other server calls are still happening (and the 'OnEntryFromAsync' method hasn't fully completed), the state machine queues the Recovery trigger.  The problem is, the 'Running' State does not have any call to 'FireAsync' in any of its code.  My state machine, from all that I can tell, is now stuck in 'Running' even though there is an enqueued transition waiting to be processed, but nothing will process it.

**Comment by HenningNT** [comment]
If you have code that you can share that demonstrate the problem, or a unit test, that would enormously.

**Comment by HenningNT** [comment]
Inside 'InternalFireQueuedAsync' the queue is supposed to be emptied of triggers, and executed, sequencially:

                while (_eventQueue.Count != 0)
                {
                    var queuedEvent = _eventQueue.Dequeue();
                    await InternalFireOneAsync(queuedEvent.Trigger, queuedEvent.Args).ConfigureAwait(false);
                }

Any trigger that is fired while processing a trigger should end up in the queue, and be acted upon later.

As for the other stuff, I'll have to think about it for a bit...

**Comment by OmnipresentObserver** [comment]
I'll do my best to provide pseudo code that highlights the problem.  Just to provide a high level of the state machine:

![BtmClient_StateMachineDiagram](https://user-images.githubusercontent.com/6266211/75577458-db1b4800-5a16-11ea-9b46-e81d2f99b1f6.jpg)

- Idle: This state sits doing nothing waiting for the 'Ready' trigger.

**Comment by OmnipresentObserver** [comment]
For a typical transition the setup looks as such:

```
class Recovering : BaseState
{
    internal override void Configure(MyStateMachine stateMachine)
    {
        stateMachine.Configure(MyState.Recovering)
            .Permit(MyTrigger.Reconnected, MyState.Running)
            .Permit(MyTrigger.FailedReconnect, MyState.Disconnected)
            .Permit(MyTrigger.InvalidPackage, MyState.Discovering)
            .OnEntryFromAsync(stateMachine.FailedCommunication, async(stateData) =>
            {
                // Log State entrance
                await ReconnectToServer(stateData);
            })
            .OnExit(() => { // Log leaving the state });
    }

    private async Task ReconnectToServer(StateData data)
    {
        // Logic to attempt reconnecting (Attempts 10 times unless a definitive failure is determined)
        // ...
        switch(MyFailureCaseEnum)
        {
            case MyFailureCaseEnum.Failed:
                await stateMachine.FireAsync(MyTrigger.FailedReconnect, stateData);
            // a few other failure cases all FireAsync(SomeTrigger, stateData);
        }
        
    }
}
````

Except for this one transition that is triggered from a SignalR callback:
```
public class MyStateMachine
{
    private StateMachine<MyState, MyTrigger> stateMachine;

    // Constructor sets up all the TriggerWithParameters and configures all State implementations

    public async Task HandleServerConnectionClosed(Exception arg)
    {
        // Log connection is closed
        if(!cancellationToken.IsCancellationRequested)
        {
            TriggerInterrupt(); // Cancels the token if it hasn't already been cancelled
            await CommunicationFailed();
        }
    }

    // This is the method that I believe is causing the problem.  Due to the callback being triggered on another thread
    public async Task CommunicationFailed()
    {
        if (stateMachine.IsInState(MyState.Connecting) ||
            stateMachine.IsInState(MyState.Running) ||
            stateMachine.IsInState(MyState.Recovering))
        {
            await stateMachine.FireAsync(FailedCommunication, stateData);
        }
    }
}
````

The supposed deadlock happens in more than one state, but it always seems to revolve around having the SignalR's Closed callback triggering which in turn causes the FailedCommunication trigger to be fired.  When that happens, the current state will complete it's work and fire off it's own trigger, but I'll never see the `OnExit` log the "EXITING STATE" message appear nor will the process react to anything.

**Comment by HenningNT** [comment]
Thank you for posting!

I'm sorry that I haven't really found out what is wrong. I do not have that much time available for fun stuff.

All I can say is that the async part of stateless haven't received as much attention as the sync part. My async skills are a bit lacking, so I'm not that confident that everything is running as it should internally.

Also, I feel that a state machine  should execute it's state management in sync manner, to ensure atomic and in-order execution. So overall I have a "bad feeling about this".

If you are willing to do to some investigation of the async code, then please feel free to do so.

If you want to run the sync version of stateless, then I can recommend something like RX extension to do so. 


I made this to test RX and stateless:

```
using Stateless;
using System;
using System.Reactive.Concurrency;
using System.Reactive.Linq;
using System.Reactive.Subjects;
using System.Threading;
using System.Threading.Tasks;

namespace testRx
{
    class Program
    {
        static void Main(string[] args)
        {
            RxStateMachine stateMachine = new RxStateMachine();

            stateMachine.Fire(Trigger.X);
            stateMachine.Fire(Trigger.Y);
            stateMachine.Fire(Trigger.X);
            Console.WriteLine("All triggers queued " + Environment.NewLine);
            Console.ReadLine();
        }
    }
    public enum Trigger { X, Y }
    enum State { A, B }

    public class RxStateMachine
    {
        private readonly StateMachine<State, Trigger> _stateMachine;
        private readonly Subject<Trigger> subject = new Subject<Trigger>();

        public RxStateMachine()
        {
            _stateMachine = new StateMachine<State, Trigger>(State.A);

            _stateMachine.Configure(State.A)
                .OnEntry(() =>
               {
                   Console.WriteLine("State is now A");
                   Console.WriteLine("Starting long-running 'task'");
                    Thread.Sleep(5000);
                   Console.WriteLine("Done!");
               })
                .Permit(Trigger.X, State.B)
                .OnExit(() => Console.WriteLine("Exiting State A"));

            _stateMachine.Configure(State.B)
                .OnEntry(() => Console.WriteLine("State is now B"))
                .Permit(Trigger.Y, State.A)
                .OnExit(() => Console.WriteLine("Exiting State B"));

            subject.ObserveOn(TaskPoolScheduler.Default)
                 .Subscribe(HandleTrigger);
        }

        private   void HandleTrigger(Trigger trigger)
        {
            Console.WriteLine("Handling trigger " + trigger);
              _stateMachine.Fire(trigger);
            Console.WriteLine("Handled trigger " + trigger + Environment.NewLine);
        }

        public void Fire(Trigger trigger)
        {
            Console.WriteLine("Queueing trigger " + trigger);
            subject.OnNext(trigger);
        }
    }
}
```

I see that if I use the Async version of OnEntry to State A (and await a Task.Delay) then the triggers appears to be processed somewhat out-of-order. I suspect that by using await the OnEntry returns, and sets _fireing to false. Then the next trigger is executed.
ref https://stackoverflow.com/questions/36211142/c-sharp-async-function-returning-prematurely

**Comment by HenningNT** [comment]
If I understand async/await properly… When the code gets to an await a new task (and state machine) is created, and control flow continues while the task is running on a different thread (more or less). Since the method awaited returns void (or the result is not used), the stateless library exits the OnEntry / OnExit while the async task is still running. 
I was able to produce this behaviour, where the last half of the OnEntry method "disappeared".

At the moment I think I recommend using the sync part of stateless, and use RX extensions to add async capabilities while maintaining serialized execution of triggers. Also be careful if you call Fire directly in state machine transitions / actions, or post the trigger to the observable.

**Comment by OmnipresentObserver** [comment]
Given your example, what is the recommended way to handle transitions within a state, then?  As I wrote above, I'm typically handling all the logic for the state within the `OnEntryFrom` or some resultant execution from the `OnEntryFrom` method.  Is your approach using an observable handling the actual trigger the Stateless recommended approach?

**Comment by HenningNT** [comment]
There's nothing wrong in using the OnEntryFrom to drive the state machine through its states. This is very useful when running an arbitrary sequence, or doing some processing sequentially.
All transitions can't be handled with just OnEntry(From), some triggers have to be posted from "the outside", like the Disconnect trigger.
When you said "handle transitions within a state" do you mean triggers that has to be acted on, but should not change the state? In that case the "InternalTransition" trigger handler can be used.

It is only my recommendation, I'm afraid. You must make sure that your code is behaving the way it needs to be. I have some experience working with state machines, but I do not know everything. I found this article to be helpful:
https://www.drdobbs.com/parallel/prefer-using-active-objects-instead-of-n/225700095
I believe that using an observable should make your state machine execution async, even if you only use the Sync versions of the available stateless methods.
