### ISSUE TITLE
OnActivate not working with update to ver 5.0.0

### ISSUE THREAD

**Issue by FilipNemec** [dotnet-state-machine/stateless#361]
Here is the example of the code.

    enum State
    {
        Start,
        End
    }
    enum Trigger
    {
        MoveToEnd,
        MoveToStart
    }
    class Example
    {
        private readonly StateMachine<State, Trigger> machine;

        public Example()
        {
            machine = new StateMachine<State, Trigger>(State.Start);

            machine.Configure(State.Start)
                .OnActivate(Start)
                .Permit(Trigger.MoveToEnd,State.End);
            machine.Configure(State.End).OnActivate(End);

            machine.Activate();

            machine.Fire(Trigger.MoveToEnd);
        }

        private void Start()=>Console.WriteLine("Start");
        private void End() => Console.WriteLine("End");

    }
}

I only get Method Start invoked but not method End. In version 4.4.0. both methods were invoked.

**Comment by HenningNT** [comment]
I apologize for the inconvenience.

Yes, this is a breaking change, done on purpose.
The implementation of Activate was broken in 4.4. It is fixed now.
Activate was supposed to be only called when needed (usually once), not on every transition.
Same with DeActivate.
