### ISSUE TITLE
OnEntry action of the next state is called before routine of the current state is exited

### ISSUE THREAD

**Issue by Ed-ward** [dotnet-state-machine/stateless#363]
public class StateMachineTest
  {
    private const string InitialState = "InitialState";
    private const string WorkState = "WorkState";
    private const string StartWorkTrigger = "StartWorkTrigger";
    private const string TerminatedState = "Terminated";
    private const string TerminateTrigger = "Terminate";

    [Test]
    public void Test()
    {
      var stateMachine = new StateMachine<string, string>(InitialState);

      stateMachine
        .Configure(InitialState)
        .Permit(StartWorkTrigger, WorkState);
        

      stateMachine
        .Configure(WorkState)
        .Permit(TerminateTrigger, TerminatedState)
        .OnEntry(() => Work(() => stateMachine.IsInState(WorkState)));

      stateMachine
        .Configure(TerminatedState)
        .OnEntry(() => Console.WriteLine("Terminated"));
      
      stateMachine.Fire(StartWorkTrigger);
      
      Thread.Sleep(2597);
      stateMachine.Fire(TerminateTrigger);
      
    }
 
    private static async void Work(Func<bool> inWorkingState)
    {
      Console.WriteLine("Start working");
      while (inWorkingState())
      {
        Console.WriteLine("working...");
        await Task.Delay(1000);
      }
      Console.WriteLine("Stop working"); // not called
    }
 }   
}

Test output:
Start working
working...
working...
working...
Terminated

OnEntry of terminated was called before method Work exited.
It prevents implementing correct shutting down of the application

**Comment by HenningNT** [comment]
See #363

**Comment by Ed-ward** [comment]
It's valid point that async void method can't be handled properly
