### ISSUE TITLE
Build warning MSB3277 due to reference to System.Core, Version=2.0.5.0

### ISSUE THREAD

**Issue by matt-richardson** [dotnet-state-machine/stateless#37]
(this was originally mentioned in https://github.com/nblumhardt/stateless/issues/14#issuecomment-158979430, but I thought i'd raise a proper issue)

We are using Stateless, version 2.5.29.0 in one of our projects, which is compiled targeting .net 4.5.

During build we get a warning `Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.`.

The detailed log shows:
```
...
5>  There was a conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
5>      "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
5>      References which depend on "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll].
5>          C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll
5>            Project file item includes which caused reference "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll".
... (25 lines ommitted) ...
5>          D:\XXX\Payments\Dev\Source\packages\NServiceBus.NHibernate.4.5.5\lib\net40\NServiceBus.NHibernate.dll
5>            Project file item includes which caused reference "D:\XXX\Payments\Dev\Source\packages\NServiceBus.NHibernate.4.5.5\lib\net40\NServiceBus.NHibernate.dll".
5>              NServiceBus.NHibernate, Version=4.5.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c, processorArchitecture=MSIL
... (94 lines ommitted) ...
5>      References which depend on "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
5>          D:\XXX\Payments\Dev\Source\XXX\bin\Debug\Stateless.dll
5>            Project file item includes which caused reference "D:\XXX\Payments\Dev\Source\XXX.Payments.Domain\bin\Debug\Stateless.dll".
5>              D:\XXX\Payments\Dev\Source\XXX\bin\Debug\XXX.Payments.Domain.dll
5>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
...
```
I've attempted to use a bindingRedirect to fix this issue, but it had no effect.

I've also attempted using the [Stateless-4.0](https://www.nuget.org/packages/stateless-4.0/) package, but that seems to have fallen behind, and does not have the OnTransitioned functionality from https://github.com/nblumhardt/stateless/commit/f63abbe1bdeb2ee6f87535114e2541424f8717cb, so it appears quite old.

Now, I know very little about PCL (but a lot more now than I knew an hour ago), but it seems that the root cause is the change to use PCL (https://github.com/nblumhardt/stateless/commit/828d097070ddcffb206c7b16729a52d17150c6c4).

I wonder if its a good idea to create a nuget package that supports .net 3.5 (which was requested in https://github.com/nblumhardt/stateless/issues/14#issuecomment-137317963), .net 4.0, .net 4.5 as well as the PCL profile 136.

What are your thoughts?

If you're of the opinion that this is a good idea, I'll take a look at the implementation, most likely using build configurations, and see if I can put together a PR.

**Comment by nblumhardt** [comment]
Hi Matt - thanks for the note. I'd love to see Stateless move to VS2015's `project.json` system that has good support for multi-targeting of this kind. I have limited time to contribute help, but would be happy to accept a PR that achieves this. Cheers!

**Comment by matt-richardson** [comment]
Hi @nblumhardt.

What sounded pretty simple turned out to be a bit of a challenge. I've pushed a commit to my fork -  https://github.com/matt-richardson/stateless - would you like to review before I make it a PR?

There seems to be [some issues](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/) around using nunit with project.json projects with the VS test runner at the moment, so not sure how that will play out (convert to xunit? deal with the lack of vs unit test runner? other?). It might just work fine in the CI pipeline - not sure.

Let me know your thoughts.

**Comment by nblumhardt** [comment]
I've seen some test runner issues recently in pretty much all projects. Not sure about CI, creating a PR is probably the best way to find out :-)

**Comment by matt-richardson** [comment]
The project has moved on substantially since this was an issue, and now has the dotnet core port sorted. 

The original issue is no longer affecting me (I've moved on to a new job), so I'm gonna close this issue.

Sorry I let this languish - ran out of time.
