### ISSUE TITLE
OnEntryFrom Action is not called after firing the trigger

### ISSUE THREAD

**Issue by binyamina** [dotnet-state-machine/stateless#374]
I have this code:

```
private StateMachine<AppState, AppEvent> _stateMachine;
        private StateMachine<AppState, AppEvent>.TriggerWithParameters<string> _requestToMoveToState1Trigger;

_requestToMoveToState1Trigger= _stateMachine.SetTriggerParameters<string>(AppEvent.RequestToMoveToState1);
```

and also:
            `_stateMachine.Configure(AppState.AppInit)
                .Permit(AppEvent.RequestToMoveToState1, AppState.InitToState1)
                .OnEntryFrom(_requestToMoveToState1Trigger, WriteStateToLog);`

I have this code and a method:
`        private void WriteStateToLog(string state)
        {
            Console.WriteLine(state);
            _logger.Info($"Moving to state: {state}");
        }`
Then I fire:
`_stateMachine.Fire(_requestToMoveToState1Trigger, GetState().ToString());`

The problem is that even the state is changed - the WriteToStateLog method is not called, and I can't figure out why.
Any clue?

**Comment by juliusl** [comment]
The OnEntryFrom config belongs on the Configure for AppState.InitToState1, because you're leaving AppState.AppInit -> AppState.InitToState1. 

So add this:
```
_stateMachine.Configure(AppState.InitToState1).OnEntryFrom(_requestToMoveToState1Trigger, WriteStateToLog);
```

**Comment by HenningNT** [comment]
You might also want to use the OnTransitioned callback:

    stateMachine.OnTransitioned((t) => Console.WriteLine($"State is now {t.Destination}"));

This gets called at every transition, and is great for debugging.

**Comment by binyamina** [comment]
Thank you two.
HenningNT - good to know!
