### ISSUE TITLE
Find a way to avoid calling "onEntry" method if there was Reentry

### ISSUE THREAD

**Issue by binyamina** [dotnet-state-machine/stateless#378]
I have this configuration:
`            _stateMachine.Configure(AtoB)
                .Permit(ReadyToMoveToB, B)
                .OnEntry(() => DoSomething())
                .PermitReentry(RequestToMoveToB);`
I want to configure somehow that when I get RequestToMoveToB - DoSomething() will not be called.
Is there any way to do it?

**Comment by HenningNT** [comment]
Would an InternalTransition would?
________________________________

**Comment by HenningNT** [comment]
Maybe a PermitIf could be used?

**Comment by binyamina** [comment]
How does PermitIf can help..?

**Comment by HenningNT** [comment]
Sorry, I missed your reply.
Is there still something that I can help you with?

PermitIf is used when the transition to a new state depends on something else. You could put some logic in the guard function to evaluate something.

**Comment by thejonan** [comment]
Isn't `IgnoreXX` concept exactly for that - have the _Reentry_ behavior, but without the entry/exit code executed.
