### ISSUE TITLE
What is the propper way for OnEntry error handling

### ISSUE THREAD

**Issue by dmitry-lp** [dotnet-state-machine/stateless#381]
Hi,

I am wondering what would be a propper way of handling errors that may occur inside OnEntry statments. Is there a way to properly rollback to previous state when an error occurs? 
Some scenarios:
 - If in my state "MailSent" the mail is supposed to be already sent but the SMTP server was down when OnEntry is called.
 - If in my stateI book a product for a client but meantime it was booked by another one.
 - ...
The problem is that OnEntry is called after the state is actually set. So eventually all associated actions are not yet set.

Thanks

**Comment by dmitry-lp** [comment]
Actually putting OnEntry code inside the gard of a PermitIf would do the job. But I don't suppose that it is the way it was intended to work. I would basically call OnEntry before setting the state of the state machine.

**Comment by mclift** [comment]
What you're describing sounds like additional, distinct states, even though they may only be very short-lived in most cases. To run over the scenarios you mentioned:

- When a user sends a email, it transitions to `SendingMail`
-- If the SMTP server is down, transition from SendingMail to `SmtpError`
-- If the SMTP server accepted the message, transition to `MailSent`
- When a salesperson books a product for a client, it transitions to `AllocatingProduct`
-- If the product can't be allocated, transition to `ProductUnavailable`
-- If the product was allocated, transition to `BookingComplete`

Is there anything that prevents you from expanding your state model in this way?

**Comment by HenningNT** [comment]
I think @mclift has the solution; introduce error state(s) to handle error condition(s).

**Comment by dmitry-lp** [comment]
Yes it is a solution if only I had to manage in this way just a couple of states. But in my case it will almost double the state count and make it difficult to use. By the way this technique means that the OnEntry function is calling itself the workflow Fire that seems a bit wired but why not.

For instance I will make my database context save in OnEntry function so that state change is not saved if there is an exception. But it would be interesting to be able to specify a function to be called on the transition arrow before the state actually changes. 
Especialy for cases that should not persist. Something like when you click on Order button on amazon you don't permanently transition in error state if something goes wrong. You just get an UI error message and stay in the cart state. Handling an ecxeption is easier in this scenario then temporarily transitionning to error state.

Something like this would be interesting:

Guard() -> OnTransition() -> StateMutator() -> OnTransitioned() -> OnEntry()

By the way the OnTransitioned() call before OnEntry() is a bit misleading. First I wanted to put dbContext.SaveChanges() in there thinking it would be the last to be called...
