### ISSUE TITLE
Some space problem in digraph generated

### ISSUE THREAD

**Issue by franckleveque** [dotnet-state-machine/stateless#382]
PackageReference Include="stateless" Version="5.1.2"
Using string states in place of enum if one of the state contains space digrpah is not properly rendered. double quotes are missing around the node name in the whole file.

Example :
digraph {
compound=true;
node [shape=Mrecord]
rankdir="LR"
Inscrit [label="Inscrit"];
Prévu [label="Prévu"];
En cours [label="En cours"];
Terminé [label="Terminé"];
Clos [label="Clos"];

Inscrit -> Prévu [style="solid", label="Planifier"];
Prévu -> En cours [style="solid", label="Compte-rendu"];
En cours -> En cours [style="solid", label="Compte-rendu"];
En cours -> Terminé [style="solid", label="Terminer"];
Terminé -> En cours [style="solid", label="Refuser"];
Terminé -> Clos [style="solid", label="Clôturer"];
 init [label="", shape=point];
 init -> Prévu[style = "solid"]
}

En cours is not interpreted correctly as it is not protected by double quotes.

**Comment by HenningNT** [comment]
Should be fixed in v5.11.0
