### ISSUE TITLE
Transition / state history + DOT rendering

### ISSUE THREAD

**Issue by cdroulers** [dotnet-state-machine/stateless#388]
Hello!

I've found this issue (https://github.com/dotnet-state-machine/stateless/issues/46) which doesn't end up having any feedback from maintainers and I'm interested in knowing more!

Basically, I'll have transitions which might depend on previous states, and it would be useful to have it integrated in the framework and if possible, use that to render the DOT graph with something like step numbers when traversed using colors or different lines or something!

I've started looking at the source code and think I *could* build a little something on `StateMachine.cs` but not sure about the DOT graph! Any pointers would be helpful!

**Comment by HenningNT** [comment]
I would not recommend integrating state history into the framework.
I'd either use the OnTransition event to store the previous state, or use the state mutators (supplied in the constructor) to store the previous state.
You could maybe use the Event Sourcing pattern, both for tracking past states, and making a graph of the execution?

**Comment by cdroulers** [comment]
@HenningNT I'm already using Event Sourcing and that does allow me to replay my state and I'm already using that very well!

I was more hoping that it could be integrated somehow so the DOT graph could be used to represent a "history" of the different states and transitions to visualize the flow of data.

Thanks for the feedback, I will close this issue!
