### ISSUE TITLE
Trigger Parameter Types at Runtime

### ISSUE THREAD

**Issue by Mafus1** [dotnet-state-machine/stateless#389]
I would like to implement a state machine where I have a generic entry point to trigger the state machine. With a trigger I want to also send a set of parameters. What type those parameters are and how many there are, is only known at run time.

Would this be possible to implement at the moment?

The only way I see at the moment to get this working would be if I could access the internal method
```
// StateMachine.cs
void InternalFire(TTrigger trigger, params object[] args)
```
where I could pass the parameters as `object[]`.

So my proposal would be to either let the user access the above method or implement a `TriggerWithParameters` with a constructor similar to the one of the abstract class, like this
```
// TriggerWithParameters.cs
public TriggerWithParameters(TTrigger underlyingTrigger, params Type[] argumentTypes)
```
and let that `TriggerWithParameters` be passed as an argument to `Fire()`.

**Comment by HenningNT** [comment]
Are you sure c# is the right language for this problem?

**Comment by Mafus1** [comment]
Well yes, c# is certainly suited for this problem. 
I dont understand why trigger parameters are implemented in such a restrictive way. The way it is now, the developer is also arbitrarily restricted to just three parameters, which also would be no problem otherwise.

**Comment by HenningTorsteinsenBouvet** [comment]
I'm just joking.

I think you can overcome this by using classes or structs for the triggers, then you'd not need the parametrized trigger at all.

As to why TriggerWithParameters, I don't know, it was designed very long ago before I joined the project.

**Comment by Mafus1** [comment]
I tried to use classes as `TTrigger` but that didnt seem to work either. I ended up forking the project and enabling the developer to use an implementation of `TriggerWithParameters` that accepts `object[]` as parameters. Validation of the parameter types still works with this approach.
I can submit the changes as a pull request if you are interested.

**Comment by HenningTorsteinsenBouvet** [comment]
Interesting!

Yes, I'd like a PR.

**Comment by HenningNT** [comment]
Nice!

Just one more question, if you don't mind...
Could you have used a dynamic object, and kept using  stateless as it is today? You see, I'm a bit wary of opening up the library, and adding new public methods means more things that can go wrong, and more to maintain.

**Comment by HenningNT** [comment]
Hello again!

Would this work for you?

```        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            StateMachine<State, Trigger> stateMachine = new Stateless.StateMachine<State, Trigger>(State.A);

            stateMachine.Configure(State.A)
                .Permit(Trigger.One, State.B);

            stateMachine.Configure(State.B)
                .OnEntry(t => OnEntry(t));

            var dynamicTrigger = stateMachine.SetTriggerParameters<dynamic>(Trigger.One);

            dynamic dynamite = new ExpandoObject();
            dynamite.Hello = "World";
            dynamite.Number = 42;

            stateMachine.Fire<dynamic>(dynamicTrigger, dynamite);

        }

        private static void OnEntry(StateMachine<State, Trigger>.Transition transition)
        {
            dynamic parameter = transition.Parameters[0] as dynamic;

            var aString = parameter.Hello as string;
            var aNumber = (int)parameter.Number;

            Console.WriteLine($"Received a string: {aString}, and a number: {aNumber}");
        }
```

**Comment by Mafus1** [comment]
Thanks for having a look at my PR!

I absolutely understand that you are hesitant to add more public methods to the library. Even though it would definitely make my life easier 😅

About the example using `dynamic` you added. I think its not a bad solution to the problem with variable numbers of parameters, but it makes the internal parameter checks useless. The user would have to add checks to make sure `dynamic dynamite` has `dynamite.Number` of type `int` etc which is already built into the library.

**Comment by HenningNT** [comment]
It's merged!
I had to check a few things, and it looks good.
