### ISSUE TITLE
InternalTransition not mentioned in README

### ISSUE THREAD

**Issue by TonyWhitley** [dotnet-state-machine/stateless#391]
I stumbled over it in one of the examples.

Any other features not mentioned?  I've only been using **stateless** for a day and I like it so far.

**Comment by HenningNT** [comment]
Thank you!

I think you're right, I'm afraid the readme does not contain every feature available. 
I see that the initial transition and activate/deactivate features are also missing.

**Comment by HenningTorsteinsenBouvet** [comment]
Also the OnEntryFrom is only hinted at...

**Comment by HenningNT** [comment]
Updated readme in release 5.1.6.

**Comment by jmo-gelsight** [comment]
The readme now does mention it but gives no example.  I was hoping I could just replace my `OnEntryFrom `clauses with `InternalTransition `buit apparently that won't work.  Still trying to decipher how to use it.  An  example (even a very simple one) in the readme would be incredibly helpful.
