### ISSUE TITLE
PermitIf with parametrised trigger does not seem to work

### ISSUE THREAD

**Issue by marcinprusak** [dotnet-state-machine/stateless#396]
I use public `StateConfiguration PermitIf<TArg0>(TriggerWithParameters<TArg0> trigger, TState destinationState, Func<TArg0, bool> guard, string guardDescription = null)` after calling `public Task FireAsync<TArg0>(TriggerWithParameters<TArg0> trigger, TArg0 arg0)` and it seems I get null every time as a parameter to guard condition.

Anyone get the same problem?

**Comment by HenningTorsteinsenBouvet** [comment]
That's rather odd, would you mind creating a unit test, or a sample demonstrating the problem?

**Comment by HenningNT** [comment]
I'm unable to reproduce, I've tried this:

        [Fact]
        public void GenericArgumentToGuardShouldNotBeNullsync()
        {
            var sm = new StateMachine<State, Trigger>(State.A);
            sm.OnUnhandledTrigger((s,t) => { });

            var paramTrigger = sm.SetTriggerParameters<string>(Trigger.X);
            
            sm.Configure(State.B);

            sm.Configure(State.A)
              .PermitIf<string>(paramTrigger, State.B, (p) =>
              {
                  return string.IsNullOrEmpty(p);
              });

            sm.FireAsync<string>(paramTrigger, "hello!").GetAwaiter().GetResult();

            Assert.Equal(State.A, sm.State);
        }

**Comment by marcinprusak** [comment]
Sorry for confusion, I found the problem, I accidentally wanted to serialize trigger in `OnTransitionedEvent` and my lack of knowledge of library internals confused it with problem with `PermitIf`.

**Comment by HenningNT** [comment]
OK, good to know you've figured it out.
