### ISSUE TITLE
Why not CLS-compliant?

### ISSUE THREAD

**Issue by Kdot94** [dotnet-state-machine/stateless#401]
Could you explain why Stateless is not marked as CLSCompliant in AssemblyInfo anymore?

**Comment by HenningTorsteinsenBouvet** [comment]
No, I can't, actually...
So it was marked CLS compliant, and now it isn't?

**Comment by Kdot94** [comment]
Yes, That's what I see in the history

**Comment by HenningNT** [comment]
Fixed in 5.1.4
