### ISSUE TITLE
Resume State with ActivateAsync?

### ISSUE THREAD

**Issue by jbockle** [dotnet-state-machine/stateless#406]
if I have a state coming from a database, whats the best way to resume with the state machine in the event my application restarts?

i.e.
```csharp
public class Order {
  public int Id {get;set;}
  public OrderStatus Status {get;set;}
}
public enum OrderStatus {
  New,
  Processing,
  Fulfilling,
  Fulfilled
}
```

should I pass the current status as initial state?
```csharp
var order = await orderRepository.Get(1);
var machine = new StateMachine<OrderStatus,OrderTrigger>(order.Status);
```

should I use the state accessor constructor?
```csharp
var machine = new StateMachine<OrderStatus,OrderTrigger>(() => order.Status, newStatus => order.Status = newStatus);
```

I also saw `ActivateAsync`, and its use case was intended for Orleans, but the PR example does `machine.ActivateAsync(actualState)`, but that method doesn't accept parameters so I'm not sure how its intended to work without a parameter.

**Comment by HenningNT** [comment]
I'd prefer to use the initial state constructor.

```
var order = await orderRepository.Get(1);
var machine = new StateMachine<OrderStatus,OrderTrigger>(order.Status);
```

If you need that something happens when restoring from the database you can use the Activate method.

**Comment by jbockle** [comment]
ahh thats how activate works, that makes more sense thank you
