### ISSUE TITLE
How do you validate the next state

### ISSUE THREAD

**Issue by alejandro1990** [dotnet-state-machine/stateless#407]
This is the configuration
![Captura](https://user-images.githubusercontent.com/4300793/100922086-ba1fe000-34dd-11eb-824b-7924082f71d4.JPG)

How does it validate the next state? I would like to know how to validate a transition from one state to the other. For example, if I'm in A, which states I do have to submit to attain B?

In case the conditions are not achieve how do I can manage to make the program stay in the same state until all the conditions are being complete?

**Comment by HenningNT** [comment]
Maybe I'm misunderstanding you, but the "validation" is handled by the library. To go from A to B you need to set up a transition with Permit, just like you have done, and when you call Fire with Next as the trigger the library will figure out what to do next.

There are optional guard functions that you have to supply if you want to use conditions to decide if a transition should be possible or not. PermitIf is one of many methods you can use for this.

The examples include most of the possible configurations, and should be good starting point for further discussions.
