### ISSUE TITLE
First State not triggered

### ISSUE THREAD

**Issue by emulk** [dotnet-state-machine/stateless#408]
Hello,
i have the following example of code,
but when i run it the first state is not triggered, i need to call the method  to trigger the state .

_state = new StateMachine<FsmState, FsmTrigger>(FsmState.StartState);

            _state .Configure(FsmState.StartState)
                .OnEntry(() => OnStartStateEntry())
                .Permit(FsmTrigger.StartStateDone, FsmState.SecondState);

            _state .Configure(FsmState.SecondState)
                .OnEntry(() => OnSecondStateEntry())
                .Permit(FsmTrigger.SecondStateDone, FsmState.ThirdState);

            _state .Configure(FsmState.ThirdState)
                .OnEntry(() => OnThirdStateEntry());

how can i trigger the first state ?
Thank you

**Comment by alejandro1990** [comment]
Perhaps the solution would be to add a state FirstState.

And it will be as follows:
`enum FsmState {StartState, FirstState, SecondState, ThirdState}`


And the logic of the state "StartState" would pass to "FirstState".

**Comment by emulk** [comment]
Thank you for your answer.

I added a new state, and a new trigger, so when i call the fire on the startStateTrigger, then the FirstState is triggered, but i don't think this is the right way to do it.

I mean why i need to add a dummy state and trigger just to fire the first state ?

**Comment by HenningNT** [comment]
For the time being the state machine does not track if it has been "started" or not (hence the name).

Other state machine libraries are started, and support the concept of initial transition, which you find missing.
The work around is to create a dummy state, and set up a transition to the first state. Use either Fire or Activate to trigger it.

Or use Activate when in the first state to "start it".

**Comment by emulk** [comment]
Thank you for your answer,
i think is better to fully document this point.
