### ISSUE TITLE
Github actions, API keys and such

### ISSUE THREAD

**Issue by HenningNT** [dotnet-state-machine/stateless#411]
Hello @dotnet-state-machine/triage !

It's that time of the year when the API key expires, and @nblumhardt has to renew it :-)

Which got me thinking, maybe we should start using the Github actions? Github also allows for storing secrets, so login info for the stateless nuget account could be stored here as well as the API key. Any member with access to the secrets could then renew the API key, if that is something we want. I guess you'd have to be an owner to see the Settings tab?

Any thoughts?

**Comment by nblumhardt** [comment]
Sounds like a good call! 👍

**Comment by HenningNT** [comment]
I'll be migrating the build to Github actions, then :-)

**Comment by nblumhardt** [comment]
Awesome :-) -- good luck!
