### ISSUE TITLE
 When adding .PermitDynamicIf, call .PermitTriggers throw NullReferenceException

### ISSUE THREAD

**Issue by yuyixg** [dotnet-state-machine/stateless#416]
When adding .PermitDynamicIf, call .PermitTriggers throw System.NullReferenceException:“Object reference not set to an instance of an object.”
class  ParameterConversion    
 public static TArg Unpack<TArg>(object[] args, int index)
        {
            return (TArg)Unpack(args, typeof(TArg), index); // args=[] 
        }

**Comment by HenningNT** [comment]
Oh dear, that should probably not happen!

Would you mind demonstrating this bug in a unit test?

**Comment by yuyixg** [comment]
var sm = new StateMachine<State, Trigger>(State.A);
            var trigger = sm.SetTriggerParameters<int>(Trigger.X);
            sm.Configure(State.A)
                .PermitDynamicIf(trigger, (i) => i == 1 ? State.C : State.B,(i)=>i==1?true:false) ;

            foreach(var permittedTrigger in sm.GetPermittedTriggers())
            {
                
            }
            sm.Fire(trigger, 1);

But there is no error when modified as shown below

           sm.Configure(State.A)
                .PermitDynamicIf(trigger, (i) => i == 1 ? State.C : State.B,()=>true) ;

**Comment by HenningNT** [comment]
I see, those dynamic methods are a bit fiddly. Thanks for the bug report, I'll see if I can do something about it.

**Comment by HenningNT** [comment]
Fixed in 5.1.8
