### ISSUE TITLE
InternalTransitionAsyncIf guard clause called twice

### ISSUE THREAD

**Issue by mtnoztrk** [dotnet-state-machine/stateless#417]
Hello,

InternalTransitionAsyncIf method calls guard clause twice (3 times if I use CanFire() as well). I have tried with Stateless 5.1.5 and 5.1.7, both has the same behavior. 

```c#
        [Fact]
        public async Task Stateless_InternalTransitionAsyncIf_Guard()
        {
            var order = new Order
            {
                Status = OrderStatus.OrderPlaced,
                PaymentStatus = PaymentStatus.Pending,
            };
            var stateMachine = new StateMachine<OrderStatus, OrderStateTrigger>(order.Status);
            stateMachine.Configure(OrderStatus.OrderPlaced)
                 .InternalTransitionAsyncIf(OrderStateTrigger.PaymentCompleted, 
                       () => PreCondition(order), 
                       () => ChangePaymentState(order, PaymentStatus.Completed)); 

            await stateMachine.FireAsync(OrderStateTrigger.PaymentCompleted);
        }
        private bool PreCondition(Order order)
        {
            return true;
        }
        
        private async Task ChangePaymentState(Order order, PaymentStatus paymentStatus)
        {
            order.PaymentStatus = paymentStatus;
        }
```
My _PreCondition_ method is doing payment with external API, so If payment is not successful, _PaymentStatus_ does not change. At first, I didn't want to depend on exceptions so I've built like this, but I think I should re-write _PreCondition_ with just logical checks and throw exception in ChangePaymentState if external API fails.
However, I've seen #235 so this might need fixing for consistency.

**Comment by HenningNT** [comment]
That's unfortunate...
I believe guard functions should not change any state, so they could be run any number of times. In reality we'd not like that, since running a guard function might be very time-consuming.

I'll see what I can do, and try to get the guard to run only once.

**Comment by HenningNT** [comment]
I've made an attempt at fixing this, at least partially.
Would you mind running the code from source, from this branch:
https://github.com/dotnet-state-machine/stateless/tree/fix-bug-417

**Comment by mtnoztrk** [comment]
I tried to run it on source and guard clause called twice, once for _FireAsync()_ and once for _CanFire()_ as expected. Thanks!

By the way I already changed my implemetation because you are right, guard clauses should be fast.

**Comment by HenningNT** [comment]
This should be sorted out now, would you mind checking the pre-release of 5.2.0?

**Comment by mtnoztrk** [comment]
Couldn't find 5.2.0 branch or tag `Install-Package Stateless -Version 5.10.0-dev-542672901` is this the one?

**Comment by HenningNT** [comment]
Heh, yes, sorry I confused myself about the version number.
