### ISSUE TITLE
Support For Eventless Transitions?

### ISSUE THREAD

**Issue by CMihalcik** [dotnet-state-machine/stateless#435]
Does Stateless support anything like immediate eventless transitions with guards?

The JavaScript state machine library XState calls these [eventless transitions](https://xstate.js.org/docs/guides/transitions.html#eventless-always-transitions). They might look something like this in Stateless

```
gameMachine.Configure(State.Playing)
    .PermitIf(State.Win, () => PlayerDidWin())  
    .PermitIf(State.Lose, () => PlayerDidLoose())
    .PermitReentry(awardPointTrigger)
    .OnEntryFrom(awardPointTrigger, UpdatePoints);
```

**Comment by HenningNT** [comment]
Not quite...
There’s the OnEntry handler which happen on entry ( but not on Internal transitions).
And there is an OnTransitioned event that’s called when a transition has occurred.

So the same functionality is not quite there.

**Comment by CMihalcik** [comment]
Thanks!
