### ISSUE TITLE
StateInfo.Transitions generates exception if there are no Transistions

### ISSUE THREAD

**Issue by EraYaN** [dotnet-state-machine/stateless#440]
It's this line of code:
https://github.com/dotnet-state-machine/stateless/blob/dev/src/Stateless/Reflection/StateInfo.cs#L146

That line should IMO return an empty set if any of the child sets are empty (or null).

You get this exception for a state without any possible Transitions:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'first')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Stateless.Reflection.StateInfo.get_Transitions()
(...)
```

That state is defined as for example:
```
 _machine.Configure(State.Error)
```

So it's a final state.

One possible solution is to add some null check in the getter of have the most basic constructor always put a `Enumerable.Empty<Type>();` in every sub `IEnumerable` in the `StateInfo` class.

**Comment by HenningNT** [comment]
Hi, sorry about the delay...
Do you have a unit test that demonstrates this issue? I am unable to reproduce it...
