### ISSUE TITLE
Sibling/orthogonal states

### ISSUE THREAD

**Issue by klar-C** [dotnet-state-machine/stateless#442]
Hi,

Is it possible to have "sibling-sub-states"?

Meaning e.g. I have a superstate (A) which has the following substates:

- State1
- State2
- State3
- State4

Initially when entering (A) we are in State1/State3. And then with triggers I can switch in between State1/State2 and or in between State3/State4.

When reading through the documentation it seems that the statemachine can only be in one state at the same time (true also with respect to superstate vs substate). If that's true, how would you suggest implementing above statemachine? Should I just create 2 new state-machines (one for State1/2 and one for State3/4) each time I'm entering (A)?

The best comparison as to what I'm looking to achieve comes from the React world:
https://xstate.js.org/docs/guides/parallel.html
There you can define multiple orthogonal children.

**Comment by HenningNT** [comment]
The problem with orthogonal states are that they are completely independent, and the state machine can only be in one state at the time.
Depending on the state machine, and the behaviour it models I'd try one of these approaches:
- internal state variable(s)
- Splitting the state machine in two (or more) state machines.
- Use objects (classes) that encapsulate the orthogonal states.
- Use sub states

You could probably use sub states if the number of orthogonal states are low. If there are too many to comfortably handle I'd consider splitting up the state machine or use compound state objects if the internal state variable won't work.

**Comment by klar-C** [comment]
Okay thanks!
