### ISSUE TITLE
Change in name from Stateless.dll -> stateless.dll

### ISSUE THREAD

**Issue by dstahl-axion** [dotnet-state-machine/stateless#449]
Hi all.

I noticed when upgrading to version 5 that the filename changed from Stateless.dll to stateless.dll. This showed up on a Linux project which has a case-sensitive file system (it was running under Mono, not sure if that's a culprit?). Mono had problems resolving the dll until I changed the name back to a capital 'S'.

Anyhow, Mono isn't your problem :) But I wanted to ask if the name change was intentional and is planned to stay that way? If not, I'll keep my eyes out for that when I upgrade next.

Also, I'm not sure if the assembly resolution is a mono bug/problem or is something that could affect Stateless users on Linux using the `dotnet` runtime so I thought I'd include that info here in case it's helpful.

Thanks for all of your work on Stateless!

**Comment by HenningNT** [comment]
Thanks for the heads up!

The name change is unintentional. However, I can't find out why or where it is changed...
The nuget pack command uses the csproj-file, and stateless is written with a capital S in there.
When I run dotnet build on my windows computer it produces a dll with capital S.
When I run dotnet build on my windows computer in WSL it also produces a dll with capital S.

This is odd.

**Comment by dstahl-axion** [comment]
I tried to figure out what may have happened by doing exactly what you did and nothing stood out. After reading your thoughts above, I checked into my cached packages folder.

On my system (Windows 10), looking in my $HOME/.nuget/packages/stateless directory, I noticed that the change from 'S' to 's' happened between 5.1.3 and 5.10.1. I'm not sure about in-between versions, I didn't install them.

The only thing that stands out, is that the .nuspec file for < 5.10.1 has `<id>Stateless</id>` but from 5.10.1 onward it's `<id>stateless</id>`. 

Not sure if that's a cause or an effect?

**Comment by RTonnesen** [comment]
Hi.

We ran into build issues when using Stateless with Xamarin/Android.

It seems like the Xamarin build pipeline requires the dll to start with a capital 'S'.
This might be because the Assembly defines 'Original filename' as 'Stateless.dll'

I checked the package history and found that the 'Stateless.dll'->'stateless.dll' change came with the 5.2.0-dev... version.

**Comment by Jax89** [comment]
Hi,

I also ran into this Issue using Stateless in a C# Project running under Linux using Mono. 

Since we updated Stateless, it will not find the dll anymore due to the case-sensitivity of Linux.
We can work around this by renaming it in our build pipeline for now, but since it apparently wasn't an intended change, would also be happy do see that fixed :).

**Comment by markusr** [comment]
We have this problem using ```PublishSingleFile``` under linux.

I think the problems is in the github workflow yml file:

https://github.com/dotnet-state-machine/stateless/blob/7ad4f662ae3d3d6de05b9eb0d2dbbaba067a0338/.github/workflows/BuildAndTestOnPullRequests.yml#L28-L37

```stateless``` (instead of ```Stateless```) is used to ```pack``` the ```csproj``` which is then pushed to ```nuget.org```.
I don't understand how this worked in the first place because there no ```src/stateless/stateless.csproj``` path/file.

@HenningNT Can you have look?

**Comment by Simonl9l** [comment]
@HenningNT et al

I'm running into the same `PublishSingleFile` issue one published and attempting to stat the single exiecutable:

```log
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Stateless, Version=4.0.0.0, Culture=neutral, PublicKeyToken=93038f0927583c9a'. The system cannot find the file specified.
```

I notice in the IDE (Rider) the dependencies package reference it has the following 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/66816457/140621737-35b862ad-e93a-40a2-88b5-f1b111ec974c.png">

I using the `5.11.0` nugget package, under the DotNet 6 (RC2) runtime. We really need to be able to single file publish in short turn around so any fix here appreciated!

**Comment by markusr** [comment]
As a workaround: Remove the ```PackageReference``` and add a  ```ProjectReference``` to a local git copy.

```
  <ItemGroup>
    <!-- This is a workaroud for issue https://github.com/dotnet-state-machine/stateless/issues/449 -->
    <!-- You need to clone https://github.com/dotnet-state-machine/stateless to a local folder and point this path to it -->
    <ProjectReference Include="../../../../github/stateless/src/Stateless/Stateless.csproj" />
  </ItemGroup>
```

**Comment by nzbart** [comment]
I worked around this issue by using version 5.2.0. It'd be great if we could upgrade to the latest.

**Comment by crozone** [comment]
Can confirm that this is still causing me issues on Xamarin

```
System.TypeLoadException: 'Could not load type of field '[REDACTED]' (0) due to: Could not load file or assembly 'Stateless, Version=4.0.0.0, Culture=neutral, PublicKeyToken=93038f0927583c9a' or one of its dependencies.'
```

Currently workaround is to clone the package as a submodule, but it's a little ridiculous.

**Comment by crozone** [comment]
Bingo, located the issue. @markusr you were totally onto it with the `BuildAndTestOnPullRequests.yml` casing issue.

Spot the difference:

```
$ dotnet pack src/stateless/Stateless.csproj --configuration Release
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net472\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net40\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net45\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\netstandard1.0\Statele
  ss.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net50\Stateless.dll
  Stateless -> [Redacted]\stateless\src\stateless\bin\Release\netstandard2.0\Statele
  ss.dll

$ dotnet pack src/stateless/stateless.csproj --configuration Release
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net472\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\netstandard1.0\Statele
  ss.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net45\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net50\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net40\Stateless.dll
  stateless -> [Redacted]\stateless\src\stateless\bin\Release\netstandard2.0\statele
  ss.dll
  ```
  
Calling `dotnet pack` with the lowercase `stateless.csproj` (on a case insensitive filesystem where it doesn't just fail outright) causes `netstandard2.0\stateless.dll` to be lowercase. Unlike in the .nupkg file which has all of them incorrect, in this case it's just the netstandard2.0 build, which might be down to my environment (I'm on Win10 and have a few different .net versions installed). In any case, there is *definitely* some strangeness going on with how the build system chooses the assembly filename.

I have verified that manually forcing the `AssemblyName` in the .csproj with `<AssemblyName>Stateless</AssemblyName>` fixes the issue:

```
dotnet pack src/stateless/stateless.csproj --configuration Release
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  Restored [Redacted]\stateless\src\stateless\stateless.csproj (in 236 ms).
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net472\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net45\Stateless.dll
  stateless -> [Redacted]\stateless\src\stateless\bin\Release\net40\Stateless.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\netstandard1.0\Statele
  ss.dll
  Stateless -> [Redacted]\stateless\src\Stateless\bin\Release\net50\Stateless.dll
  stateless -> [Redacted]\stateless\src\stateless\bin\Release\netstandard2.0\Statele
  ss.dll
  Successfully created package '[Redacted]\stateless\src\stateless\bin\Release\State
  less.5.11.0.nupkg'.
  ```
  
  So PR https://github.com/dotnet-state-machine/stateless/pull/470 should be good to go.
