### ISSUE TITLE
Blazor Web Assembly .Net6

### ISSUE THREAD

**Issue by famda** [dotnet-state-machine/stateless#465]
Hi,

I'm trying to use the library on .net 6 on blazor web assembly project without success.

The project compiles without issues but can't load the page and presents this error:

![image](https://user-images.githubusercontent.com/26621392/139855253-b4b26fd2-efa9-4964-a0ed-a1f2b5c2106a.png)

Is there any issues with it?

**Comment by Blackclaws** [comment]
Rebuild the library yourself and the result should work. I've had similar issues with loading it in Unity.

**Comment by mclift** [comment]
Having tested this in a simple Blazor app, it looks like this was fixed by #480. @famda @danielmertens, please let us know if you're still seeing this issue!
