### ISSUE TITLE
Support for .net 6?

### ISSUE THREAD

**Issue by ericsleung** [dotnet-state-machine/stateless#473]
Will there be a new build to target .net 6 framework? Thanks

**Comment by auvansang** [comment]
I'm waiting it too!

**Comment by kerrpeter** [comment]
Can anyone confirm if the current version works in .Net 6 or not or what issues are expected?

**Comment by alexeyshockov** [comment]
It works for me on .NET 6 without any issues

**Comment by AlonAm** [comment]
Works great for me with NET MAUI on .NET 6, compiled together with my project. Waiting for the NuGet package 📦
