### ISSUE TITLE
Trouble with case sensitive files systems (Android)

### ISSUE THREAD

**Issue by jenscski** [dotnet-state-machine/stateless#482]
Hello, I have problem using this library with systems using case sensitive file systems, e.g. Android for my case.

Looks like its because the assembly name is Stateless, but the filename is stateless.dll in the nuget at nuget.org

I have checked out the code, and published the nuget for stateless to a local folder, the generated nuget now has capital s in the dll files, Stateless.dll.

When using this local generated nuget, my code works just fine on Android.

Why is the name lowercase in the nuget.org version, when a locally created nuget have capital file name?

Is it possible to publish a Android (and possibly Linux) compatible nuget?

**Comment by jenscski** [comment]
Looks like a change was introduced between version 5.1.8 and 5.2.0, in version 5.1.8 the dll is Stateless.dll, in 5.2.0 it's stateless.dll.

5.1.8 works on Android (.NET MAUI), but 5.2.0 (and later) does not work.

**Comment by HenningNT** [comment]
This is unfortunate, I apologize for the inconvenience.
I believe a fix is on the way.

**Comment by jenscski** [comment]
Looks like it's fixed in [5.12.0](https://www.nuget.org/packages/Stateless/5.12.0)

**Comment by crozone** [comment]
> Looks like it's fixed in [5.12.0](https://www.nuget.org/packages/Stateless/5.12.0)

Yep, it was fixed in https://github.com/dotnet-state-machine/stateless/pull/480
