### ISSUE TITLE
Can we export state machine defination from c# and import it into angular stateless library?

### ISSUE THREAD

**Issue by sayeduzzamancuet** [dotnet-state-machine/stateless#496]
Is it possible to export the state machine configuration and import it into angular stateless version?

**Comment by mclift** [comment]
Hi,

I'm not very familiar with Angular so I may be missing some context. I'd be interested to know more about your requirements.

If you need to export the state machine, your best bet at the moment is probably to write a class to iterate over the states in `StateMachineInfo`, which you can get Stateless to instantiate for you by calling `GetInfo()` on your `StateMachine` instance. You could use the `StateGraph` class as a reference.

A limitation that immediately comes to mind is that any custom logic you have `PermitIf` transitions or guard conditions won't be exportable.
