### ISSUE TITLE
Error handling during transition

### ISSUE THREAD

**Issue by prasannavl** [dotnet-state-machine/stateless#5]
How can errors be handled during state transition? Say, an error caused during OnEntry, or OnExit which shouldn't be causing the state change.

**Comment by NicolasDujacquier** [comment]
Hello,
Does anyone has any best practice about this ?
I would be interested!

**Comment by nblumhardt** [comment]
Thanks for opening this discussion; it's been a long while! :-)

I think currently `StateMachine`'s internal invariants can be violated when transition handlers throw. I would like to see what can be improved/suggested here, but we probably need to address this through specific scenarios. Closing for now. Thanks again!
