### ISSUE TITLE
Dependency injection support

### ISSUE THREAD

**Issue by omerfarukz** [dotnet-state-machine/stateless#50]
Hi,
We need a separate stateless and our domain objects. Created a new sample project for dependency injection. Can you please consider dependency injection support.

https://github.com/omerfarukz/statelessDependencyInjectionSample

Regards

**Comment by nblumhardt** [comment]
Thanks for posting the example Omer.

Currently I think supporting more complex architectural patterns can be external to Stateless, as you've done here. Let me know if there are any gaps in the Stateless API, though!

Best regards,
Nick
