### ISSUE TITLE
Shouldn't HandleTransitioningTrigger set the state *after* the transitioning took place?

### ISSUE THREAD

**Issue by adamstyl** [dotnet-state-machine/stateless#506]
I was wondering what could be the reason behind this design decision. For reference, I am quoting the relevant code from `HandleTransitioningTrigger`

https://github.com/dotnet-state-machine/stateless/blob/e0dd5c9ba8c316c8a2f5fbc315a9f8dc9a2836cc/src/Stateless/StateMachine.cs#L472-L477

## Purpose
As I see it, `EnterState` might (will?) execute code relevant to the new state. If that code doesn't execute successfully, one could assume that the transition didn't even happen. Finally, it's quite unexpected to have a state that is not actually _reflected_ yet to the system.

## Example
I am trying to implement a plain ol' Open - Save - Close of a file as a state machine. For the close action the configuration looks like that:

```
stateMachine.Configure(LoadableArtifactState.Empty)
   .OnEntryFrom(LoadableArtifactAction.Unload, Clear)
  //more here
```
`State` property looks like that:

```
public LoadableArtifactState State
{
	get => state;
	private set
	{
		if (state == value) return;
		state = value;
		EventLogger.Info($"Entering state {value}");
		OnStateChanged();
	}
}
```

Method `Clear`, which is responsible for the "artifact" cleanup chores, will be called **after** the `OnStateChanged()` is run. Unfortunately the peers rely on the event to make the refresh chores and while the value of state is `Empty`, the artifact has not been unloaded yet. I even tried the `stateMachine.OnTransitioned()` but to no avail -quite obviously from the code.

## Proposed solutions

I would suggest either of:

1. moving the `State = transition.Destination;` after the call to `EnterState`. Although I consider it the most suitable solution, I am not aware of the ramifications of such a decision.
2. a `TransitionEnded` event to be called, well, when the transition ends. But again this would be a half baked solution as the `State` will still not reflect the actual system status.

PS: I found a similar but not identical issue: #446

**Comment by mclift** [comment]
Hi @adamstyl

Thanks for taking the time to write up the description of the issue. Just to make sure we're on the same page, my understanding of the issue you've raised is that you're relying on the `Clear` logic to have completed successfully _before_ the state machine has actually entered the `Empty` state, and this is a problem because the artifact will still be unloading while the state machine is reporting its state as `Empty` when it should be `Loaded` or `Unloading` or something like that; in other words the ordering of events means that your `OnEntryFrom` logic is happening too late. Is this correct?

If I got that right, then you could consider attaching your cleanup logic to the `OnExit` handler on the previous state, as this executes before the transition has happened. But then you've shifted the problem into the `Loaded` state and there will always be a moment when the artifact has been unloaded. If that's also a problem, you could consider introducing a new intermediate state, say `Unloading`.

Going back to the question, I think the design intent is that `OnExit` gives you a chance to execute logic before the transition and `OnEntry` is for logic based on the transition having occurred.

**Comment by adamstyl** [comment]
Hello @mclift, thanks for getting back.

Please allow me one correction:
> because the artifact will still be unloading

Not exactly because the grammar choice imposes asynchrony while there is none. :) The artifact unloads synchronously, it will just do so _after_ the state is set to empty and after the `StateChanged` event is fired

> The ordering of events means that your `OnEntryFrom` logic is happening too late..

Yes the gist is right.

> you could consider attaching your cleanup logic to the `OnExit` handler on the previous state

I'm afraid that's more complicated than that.

![LoadEditSave StateMachine](https://user-images.githubusercontent.com/13643651/215200702-4891e797-673b-4600-b988-e24debf80736.png)

From the diagram we can see three problems:
1. There are *a lot* of transitions to `Empty`
2. Some of them are conditional (the `[Failed]` case is when the user says "nah" to the dialog box)
3. It is already too complex to add even more states

If it's not obvious, I decided to use a state machine out of pure frustration from the "traditional" methods. :)

> I think the design intent is that OnExit gives you a chance to execute logic before the transition and OnEntry is for logic based on the transition having occurred.

Granted, but this also has the weakness that you can only configure `OnExit` **from** but not to. So it get's us back to an `OnEntering`/`OnEntered` event pair. :(

**Comment by mclift** [comment]
Thanks for the clarification, the graph diagram really helps to give context to the issue.

I can definitely see a case for complimenting `OnEntry[From]` with equivalent `OnEntering[From]`/`BeforeEntry[From]` hooks. It would mean adding another 11 methods to `StateConfiguration`, but my feeling is it's probably worth it on balance.

This would also be useful for cases where you want to make sure any guard conditions have been met before executing the pre-transition action, as actions attached to `OnExit` are executed regardless of whether the guard conditions are met if you provided any. I'm unsure whether this should be considered a bug or not, and this case isn't covered by any of the unit tests.

An aspect that might need some thought is how to represent these behaviours in a DOT graph. Currently, exit actions are represented as part of the source state; entry actions, the destination state (example below). I guess the 'transitioning' action might be shown on the transition element itself, but those with a deeper knowledge of state machine theory than me might well disagree!

![image](https://user-images.githubusercontent.com/2707465/215276393-cace9929-56b1-4130-be84-9e7d94637d47.png)


What do you think?

**Comment by adamstyl** [comment]
@mclift Before commenting on the rest I should note that actually _there is_ an alternative: it seems that I missed the `OnTransitionCompleted()` method.

```
stateMachine.OnTransitionCompleted(t =>
{
	if (t.Source != t.Destination) OnStateChanged();
});
```
Although its API is a bit cumbersome to my taste (I prefer idiomatic C# events) and it results in moving the `OnStateChanged()` triggering away from the `State` property where it belongs, it is a viable alternative.

Anyway, regarding the rest, indeed adding another 11 methods to `StateConfiguration` could be a significant change -although I'm not familiar with the codebase. For the DOT graphs I wouldn't worry as Entering/Entered event pair would be part of the transition. It won't be necessary to be separated. I'm not a state machine expert though.

The answer I think is somehow simpler. `State` is mutated before `EnterState()` is called. So we haven't _entered_ the state yet, but we are eager to say that we are already there. To give an analogy, it's like drawing a strikethrough line on a task on the todo list when starting the task instead of when finishing it. :)

**Comment by adamstyl** [comment]
I take the liberty to close the issue as apparently there is an alternative. Feel free to reopen it if you must. 😊
