### ISSUE TITLE
Keep current state for X seconds, possible?

### ISSUE THREAD

**Issue by DenisIvanovIvanov** [dotnet-state-machine/stateless#507]
Is it possible to retain specific state for some time? 

`_appState.Configure(ApplicationState.TransferVideoCompleted)`

When this state is triggered I would like to keep it for e.g. 15 seconds before allowing any other state change. I know I can do it manually  by check if the current state is `X` before calling `.Fire()`, but I prefer doing it with built-in way if possible.

**Comment by mclift** [comment]
There are a couple of approaches I can think of:

If you can set a `ready` flag whenever the trigger is fired, you could combine `IgnoreIf` with `PermitIf` and start a stopwatch inside an `OnEntry` action. However, as the guard conditions must be mutually exclusive, the `ready` flag would need to be evaluated externally, which deviates from your design principle of handling the condition internally to the state machine.

Here's what that might look like if applied to the [OnOffExample](https://github.com/dotnet-state-machine/stateless/tree/dev/example/OnOffExample) project:

```csharp
using Stateless;
using System.Diagnostics;

const string on = "On";
const string off = "Off";
const char space = ' ';

var onOffSwitch = new StateMachine<string, char>(off);

var stopwatch = new Stopwatch();
var ready = false;

onOffSwitch.Configure(off).Permit(space, on);
onOffSwitch.Configure(on)
    .IgnoreIf(space, () => !ready)
    .PermitIf(space, off, () => ready)
    .OnEntry(stopwatch.Restart);

Console.WriteLine("Press <space> to toggle the switch. Any other key will exit the program.");

while (true)
{
    Console.WriteLine("Switch is in state: " + onOffSwitch.State);
    var pressed = Console.ReadKey(true).KeyChar;

    if (pressed != space) break;

    ready = stopwatch.Elapsed >= TimeSpan.FromSeconds(15);

    onOffSwitch.Fire(pressed);
}
```

To make it more self-contained, the `ready` evaluation could be moved into the guard condition of `PermitIf`, and the `IgnoreIf` could be replaced with an `OnUnhandledTrigger` (this prevents an exception being thrown when none of the guard conditions is met for a trigger).

```csharp
using Stateless;
using System.Diagnostics;

const string on = "On";
const string off = "Off";
const char space = ' ';

var onOffSwitch = new StateMachine<string, char>(off);

var stopwatch = new Stopwatch();

onOffSwitch.Configure(off).Permit(space, on);
onOffSwitch.Configure(on)
    .PermitIf(space, off, () =>
    {
        var ready = stopwatch.Elapsed >= TimeSpan.FromSeconds(15);
        if (!ready) Console.WriteLine("Not ready yet");
        return ready;
    })
    .OnEntry(stopwatch.Restart);
onOffSwitch.OnUnhandledTrigger((_, _) => { });

Console.WriteLine("Press <space> to toggle the switch. Any other key will exit the program.");

while (true)
{
    Console.WriteLine("Switch is in state: " + onOffSwitch.State);
    var pressed = Console.ReadKey(true).KeyChar;

    if (pressed != space) break;

    onOffSwitch.Fire(pressed);
}
```
