### ISSUE TITLE
Can exit from any substates to superstate exit ?

### ISSUE THREAD

**Issue by patopat** [dotnet-state-machine/stateless#508]
Hi,

I was wondering if it's possible to exit a superstate from any substates with the same condition transition or I need to set for each substates a the same condition  ? For example, I have an process error occurs in any substate and I would like exit the superstate to an Error state.

Regards,
Pat

**Comment by crozone** [comment]
This should be possible by simply placing a transition on the superstate i.e. `.Permit(Trigger.ErrorTrigger, State.Error)`. All substates of the superstate will effectively inherit the transition. If using a guard clause (`.PermitIf(...)`), all of the guard clauses must still be mutually exclusive across both the substate and superstate.

**Comment by patopat** [comment]
@crozone I try to write and understand how substates works.

Here is a test code 
```Csharp
        public TryFsm()
        {
            _stateMachine = new StateMachine<State, Triggers>(() => _state, s => _state = s);

            _stateMachine.Configure(State.Initialization)
                .Permit(Triggers.InitCompleted, State.WaitSelection);


            _stateMachine.Configure(State.WaitSelection)
                .Permit(Triggers.Start, State.MySuperstate);


            _stateMachine.Configure(State.MySuperstate)
                .Permit(Triggers.MySubstateTrig1, State.Substate1)
                .Permit(Triggers.ErrorTrigger, State.Error);

            _stateMachine.Configure(State.Substate1)
                .SubstateOf(State.MySuperstate)
                .Permit(Triggers.MySubstateTrig2, State.Substate2)
                //.Permit(Triggers.ErrorTrigger, State.Error) herited from MySuperstate
                ;

            _stateMachine.Configure(State.Substate2)
                .SubstateOf(State.MySuperstate)
                .Permit(Triggers.Finish, State.WaitSelection)
                //.Permit(Triggers.ErrorTrigger, State.Error) herited from MySuperstate
                ;

            _stateMachine.Configure(State.Error)
                .Permit(Triggers.ErrorClearedTrigger, State.WaitSelection);
        }
```

and give th efollowing graph 

![image](https://user-images.githubusercontent.com/20794916/223765172-2ef51e1d-1c4a-4ade-bb63-4e87cd3b9e60.png)


Is it the right way to use substates with each one can exit with an error trigger ?

Regards,
Pat

**Comment by mclift** [comment]
Yes, your code looks correct based on what you've described.

Unfortunately the dot graph output doesn't always handle substates well, and I can see you've hit one of those cases above as MySuperstate shouldn't appear twice.
