### ISSUE TITLE
VS 2012

### ISSUE THREAD

**Issue by beachwalker** [dotnet-state-machine/stateless#51]
Solution is VS 2012 but the project uses C# 6.0 (nameof etc.) and requires VS2015. Please update solution file to 2015 format to clarify what is really needed to build or stay with older compatible syntax that enables build with 2012.

Personally, I use 2013 and 2015. With the free available Express Editions there seems to be not much benefit with having an old 2012 Solution file (that does not build in 2012 or 2013).

**Comment by gopi8887** [comment]
How can we build this project and run it in vs 2013. I am having hard time to get this running.

**Comment by nblumhardt** [comment]
@gopi8887 2015 is required for C#6, but, you can grab an earlier release from Git.

**Comment by nblumhardt** [comment]
I've added a note to the README to clarify.
