### ISSUE TITLE
New example: Alarm

### ISSUE THREAD

**Issue by celloza** [dotnet-state-machine/stateless#517]
Always wanted to build an alarm system as a state machine. Project I'm working on (alarm system for a yacht) required me to do it, so I put together an example using Stateless.

I needed support for "temporary" states (i.e. PreArmed, a state between Disarmed and Armed (to allow for some configurable pre-arm delay)), which I've implemented using timers triggered via OnEntry() and OnExit() methods. These temporary states have a pre-defined TimeOut transition/command that progresses/regresses them to the relevant state.

PR #516 raised.

**Comment by HenningNT** [comment]
Well done, thank you for your contribution!
