### ISSUE TITLE
Yet another cannot install and use in VS 201x issue

### ISSUE THREAD

**Issue by billwoo** [dotnet-state-machine/stateless#53]
In this case VS 2013

I really have trouble figuring out why a project as excellent, and interesting, as this one doesn't provide a clear statement about what is _required_ to use it ... a simple statement. Do you really want new users to be frustrated figuring out why it won't compile ... why the 'nameof operator doesn't exist ?

I am able to use NuGet to install it in VS 2013, but then I have to use ReSharper's reflection tools to look at the source.

I'd appreciate one clean package that does not target SilverLight, or Win Mobile that I can add to Visual Studio.

thanks, Bill

**Comment by nblumhardt** [comment]
Hi Bill! Yet another _you'll need VS2015 to build this_ reply ;-) A lot of the .NET ecosystem's moved on to C#6, which permits targeting earlier .NET versions, but needs the new compiler to build.

A PR to README.md would be welcome, if you can suggest some wording.

Cheers,
Nick

**Comment by billwoo** [comment]
Hi Nick, 

Suggestion for 'ReadMe file:

Important notice: The source here requires VS 2015 to build and use. If you are using other versions of Visual Studio, you can install the compiled code using Nuget, and it will work fine.

That's all it would take, imho. I do read 'ReadMe files !

cheers,Bill

**Comment by nblumhardt** [comment]
Done, thanks Bill.
