### ISSUE TITLE
OnEntry does not get fired in a WinForms app

### ISSUE THREAD

**Issue by SpeedOfSpin** [dotnet-state-machine/stateless#538]
Hi

I seem to be having a problem that I just can't figure out why.

Basically the OnEntry event never gets fired. OnExit does however.

I have attached a simple WinForms app in .net 7.0 which demonstrated the issue.
I have configured it simply like this.

```
            machine = new StateMachine<State, Trigger>(State.New) { };

            machine.Configure(State.New)
                .OnEntry(t => Debug.WriteLine("test"))
                .Permit(Trigger.DetermineTasks, State.WaitForTasks)
                .OnEntry(t => Debug.WriteLine("test"));
```

And call it like this
```
machine.Fire(Trigger.DetermineTasks);
```

The state changes but the OnEntry events do not fire

[WinFormsApp1.zip](https://github.com/dotnet-state-machine/stateless/files/12105273/WinFormsApp1.zip)

Thank you!
SoS

**Comment by vittoso** [comment]
Hi,
the OnEntry that you show in your code refers to State.New while you are trying to move the state machine to State.WaitForTasks . As you haven't set any OnEntry() for State.WaitForTasks, you don't see anything.

You should configure some OnEntry on State.WaitForTasks by adding something like this in your code:
```c#
 machine.Configure(State.WaitForTasks)
                .OnEntry(t => Debug.WriteLine("WaitForTasks - test"));
```

**Comment by SpeedOfSpin** [comment]
Arrgghh. I can't believe I was being that dumb. It's obvious lol. Thank you very much!

**Comment by SpeedOfSpin** [comment]
All working now thanks.

**Comment by SpeedOfSpin** [comment]
All working now thanks.
