### ISSUE TITLE
Using PermitIf on a state with substates seems to lead to reentry

### ISSUE THREAD

**Issue by hooligan495** [dotnet-state-machine/stateless#543]
Hi, 

I've a setup where I have a state with Substates. 

When I configure the state with a permitif trigger guard, I fire the trigger and the substate transitions..  but if the trigger fires again.. the entry action of the substate I'm already in fires.  This seems counter to the documentation I've been reading.  

Is this supposed to happen? (I don't want the onentry to be called multiple times).   or is this a missunderstanding on my part. 

So say I configure a State with a parameterized trigger:

`
.Configure(SuperStateA).PermitIf(_paramTrigger, SubstateA, p == Event1)
.Configure(SubstateA).SubstateOf(SuperStateA).OnEntry(()=>{log.Info("HI)});
`

If my Event 1 fires multiple times I see Hi printed multiple times. 

If this is how you would expect Stateless to behave can someone indicate so?  I will update my guard conditions to account for the current state... 

Thanks

**Comment by HenningNT** [comment]
I think that this should not have happened.

If the state machine is in SubstateA, then the trigger should be handled by the super state handler. So far, so good.
But the state doesn't change, so the state machine should not execute the onEntry action.

So I would say this is a bug.

**Comment by hooligan495** [comment]
Thanks

**Comment by hooligan495** [comment]
@HenningNT 
in an attempt to be helpful I did create this unit test in the Stateless solution.  and implemented the fix this way.. .(I'm not real happy with this fix as it seems to go against the conventions this project has been following (meaning I feel like finding the trigger should determine that it gets ignored vs what I did)).

If you have other suggestions on how this should be addressed I'd be happy to modify my changes and open a PR. 
If you like this and would like me to open a PR I'm fine doing that too. 


Unit test: 
`
[Fact]
public void WhenInSubstate_TriggerSuperStateTwiceToSameSubstate_DoesNotReenterSubstate()
{
    var sm = new StateMachine<State, Trigger>(State.A);
    var eCount = 0;

    sm.Configure(State.B)
        .OnEntry(() => { eCount++;})
        .SubstateOf(State.C);

    sm.Configure(State.A)
        .SubstateOf(State.C);


    sm.Configure(State.C)
        .Permit(Trigger.X, State.B);

    sm.Fire(Trigger.X);
    sm.Fire(Trigger.X);

    Assert.Equal(1, eCount);
}
`

code change in statemachine.cs
`
               case TransitioningTriggerBehaviour _ when result.Handler.ResultsInTransitionFrom(source, args, out destination):
               {
                   //If a trigger was found on a superstate that would cause unintended reentry, don't trigger.
                   if (source.Equals(destination))
                       break;

                   // Handle transition, and set new state
                   var transition = new Transition(source, destination, trigger, args);
                   HandleTransitioningTrigger(args, representativeState, transition);

                   break;
               }
`

**Comment by hooligan495** [comment]
Hi,  I'm just checking in on this and my pull request.   Is there anything more I can be doing to help move this forward?  Thanks!

**Comment by HenningNT** [comment]
Ping! @crozone @mclift

**Comment by crozone** [comment]
> Ping! @crozone @mclift

Thanks for the ping. LGTM and tests are passing. I'll give @mclift a chance to review this but I think I understand what's going on now. If I understand it, the superstate is transitioning to itself with `TransitioningTriggerBehaviour` because only the primary substate will use the `InternalTriggerBehaviour` case which has been set up, so this effectively kills that edge case.

**Comment by HenningNT** [comment]
I think it's about time to merge in #544, bump the version number to 5.13.1, and make a new release :-)

**Comment by mclift** [comment]
It's been a little while since the last release. There was [a discussion about](https://github.com/dotnet-state-machine/stateless/discussions/525) bumping the major version number as we've changed the targeted frameworks to the LTS versions, but on reflection, this probably doesn't warrant a major release on its own. So maybe 5.14.0?

Anyway, I'll get on that :)
