### ISSUE TITLE
Can we have InternalTransition, please?

### ISSUE THREAD

**Issue by HenningNT** [dotnet-state-machine/stateless#59]
I have used the Quantum Leaps state machine framework quite a bit to run state machines on microcontrollers. It supports internal transitions, and it makes life a lot easier. The internal transition does not actually change state, so the state is the same after the event has been processed.

Consider the telephone call example. Let's say we need to adjust the volume. Every state would need an two extra lines: PermitReentry (AdjustVolumeEvent) and OnEntryFrom(AdjustVolumeEvent, HandleVolumeControl).

By using internal transition we only need to add a handler to a superstate (State.OffHook), which is much less verbose.
As a bonus the super states becomes much more useful as well.

**Comment by nblumhardt** [comment]
Hey @HenningNT  - interesting idea! Definitely open to a PR along these lines, so long as existing semantics/backwards compat are maintained. I have a bunch of other commitments that mean I won't be able to tackle this myself, so marking 'up-for-grabs' in case you or someone else watching the project is interested to have a go at it. Thanks!

**Comment by HenningNT** [comment]
I tried to do something with this...
I think I did a pull request, but I am very much a github noob...

**Comment by Cussa** [comment]
Any position about this? I think that it's very useful!

**Comment by nblumhardt** [comment]
@Cussa I'm still open to the idea, but the linked PR is incomplete/not building so I haven't looked any further into it.

**Comment by HenningNT** [comment]
Hi, I have done a bit on this, and I have something that works for me ;)
I haven't gotten round to uploading it yet, I'll try to do that soon.

**Comment by HenningNT** [comment]
Hi!
I have made a pull request, please have a look and see if it works for you :-)

It works for me and my needs ;-)

**Comment by tlk** [comment]
@HenningNT Neat! I have added some minor comments to the PR #73 

Considering the ToDotGraph support, would you expect these transistions to be rendered on a diagram? If so, how?

**Comment by HenningNT** [comment]
I haven't considered dotGraph support yet, but I do know that dotgraph can be used to draw uml charts, and internal transitions are part of uml so I expect that the ToDotGraph method can be modified to draw internal transitions.

So it's a matter of finding someone to do it 😊
I'll take a look at how the diagram is made, but I won't promise anything.

**Comment by nblumhardt** [comment]
I am not sure what the default behaviour will be, but we do probably need to make sure that the rendering in dotGraph is sane. Nothing fancy required though :-)

Otherwise +1 on the PR, thanks for pushing it forward @HenningNT!

(BTW @tlk thanks for the comments; I've added you to the newly-minted "Reviewers" team with commit/merge rights. Cheers!)

**Comment by HenningNT** [comment]
So I have a good look at dot graph, and it looks like the internal transitions could be inserted as (sub) labels or HTML tables. I'm thinking something that looks like this:
https://en.wikipedia.org/wiki/UML_state_machine#Internal_transitions

I stumbled across another issue with ToDotGrah; it draws all states as separate nodes even if they are substates. It's possible to use subgraph cluster to group nodes inside a box, but it's not optimal.
