### ISSUE TITLE
C#6.0

### ISSUE THREAD

**Issue by psibernetic** [dotnet-state-machine/stateless#61]
Would an upgrade to new standards be a good idea at this point or wait for v2.

**Comment by psibernetic** [comment]
@nblumhardt I am open to helping craft a 2.0 as this is the engine in my biggest side project. Plus, I really enjoy your work and would like to work closely with you in the future.

**Comment by nblumhardt** [comment]
Hey Ovan! Some help with Stateless would be hugely welcome, I am still enthusiastic about the project but have very little time to push it forward at the moment. What are the kinds of things you think we'd do in a "2.0"?

**Comment by psibernetic** [comment]
I think the biggest thing would be a level of transparency into state transitions, guards, and actions. In my fork for instance I have started tracking the trigger that caused the state change. I'd like to look to the values of event-sourcing to build around. 

Addition of strategies for how actions are handled. (When actions should be invoked for instance.)

Trigger parameterization could be cleaner and perhaps more opinionated, perhaps standard contracts rather than optionally attaching parameters with different types.

Adding at least a stub of a state container could be huge too, similar to Redux for those who need it.

**Comment by psibernetic** [comment]
Regarding the state container, actions would be the reducers.

**Comment by nblumhardt** [comment]
Sounds awesome - so much interesting stuff to investigate.

https://github.com/dotnet-state-machine/stateless/issues is also pretty thick with shortcomings/limitations in the current design, it'd be great to do some triage and figure out what can be incorporated in a future version.

Regarding the original topic of this thread - `master` already uses a little C# 6, so I'm open to converting the whole lot if a PR interests you?

Thanks for the input!

**Comment by psibernetic** [comment]
Yeah, I will probably open a PR sometime this week.
