### ISSUE TITLE
Transition / Actions

### ISSUE THREAD

**Issue by Sakamakak** [dotnet-state-machine/stateless#62]
Hi All, 

First many thanks for this amazing library. I have been using it in many projects for the past 2 years, it's been very helpful. 

I have however a small concern about a feature which seems to be missing, with regards to UML 2 state machines specifications. 

No action can be attached to an event. There is no possibility to execute an action on a Fire itself. 
The only way to achieve that today would be to create a Parameterised Triggers and then to execute the attached function on an EntryFrom.
But this does not cover all the cases. 

Let's take the example below :
![dessin1](https://cloud.githubusercontent.com/assets/3066411/15649966/aee7c85e-2675-11e6-9ab5-a7cc699e27d8.png)

In this example, the machine is deterministic, but depending on when and from where the event T1 is raise the associated action is not the same.

I though it would be amazing to configure a State mahcine like this:

```
stateMachine.Configure(State.A)
    .PermitIf(Trigger.T1, State.B, () => { return cond(); }, (a,b) => { Action1(a,b); } )
    .PermitIf(Trigger.T1, State.B, () => { return !cond(); }, (c) => { Action3(c); } );

stateMachine.Configure(State.B)
    .PermitReentry(Trigger.T1, (a,b) => { Action1(a,b)} );
```

Any idea on how to do that with Stateless ?
Anyone tried to extend the library this way ?

Thanks in advance.

**Comment by nblumhardt** [comment]
Thanks for the note. I haven't hit the need for this (but also haven't used stateless in a few years).. also interested to hear if anyone else has tried it.

**Comment by HenningNT** [comment]
I think the drawing might not be explaining the problem you are facing properly.
The state diagram shows that something has happened that caused a transition out of State A, and you'd like the frame work to select the appropriate Action to be executed based on some information?

I would introduce two new transitions from state A and make T1 re-entry state A. The T1 Action would evaluate the conditions and fire the correct trigger.

Regarding state B: I'm working on adding internal transitions, maybe that could be useful?

**Comment by nblumhardt** [comment]
This looks like something the recently-added internal transitions will cover, please let me know if I am mistaken. Thanks!
