### ISSUE TITLE
Parameterized triggers and multiple entry methods

### ISSUE THREAD

**Issue by 0davidreynolds0** [dotnet-state-machine/stateless#64]
I have a question about parameterized triggers.  I need to be able to pass objects into the triggers for a state but I need to pass different objects into the same state change.  Is this possible?

var createStayTrigger = sm.SetTriggerParameters<LineItemAddedEvent>(Trigger.CreateStay);
var createStayAfterItemTrigger = sm.SetTriggerParameters<ItemCreatedEvent>(Trigger.CreateStay);

sm.Configure(State.ProcessingStay)
    .Permit(Trigger.Finish, State.Complete)
    .Ignore(Trigger.Start)
    .Ignore(Trigger.CreateStay)
    .OnEntryFrom(createStayTrigger, e =>
    {
        // do something here with LineItemAddedEvent
    })
    .OnEntryFrom(createStayAfterItemTrigger, e =>
    {
        // do something here with ItemCreatedEvent
    });

**Comment by nblumhardt** [comment]
Hi David,

I don't think it is today. Under the hood, the trigger is evaluated without much consideration of the strongly-typed parameter bindings on top of it.

Cheers,
Nick

**Comment by rcmaniac25** [comment]
This is actually an issue I encountered recently, though I have different parameters (`TriggerWithParameters<Arg0>(State.Something)` and `TriggerWithParameters<Arg0, Arg1>(State.Something)`). I have a couple different OnEntryFrom that have different parameters but the same triggers.

Is there any chance that checking parameter types/count could be done so it doesn't try to mix parameterized triggers with an incompatible OnEntryFrom?
