### ISSUE TITLE
Target .NET Core

### ISSUE THREAD

**Issue by DamianReeves** [dotnet-state-machine/stateless#67]
Now that .NET Core is out Stateless makes sense as a project that targets .NET core

**Comment by shakdoesgithub** [comment]
Are there any plans to support dotnet core?

**Comment by nblumhardt** [comment]
A PR based on the project structure, Build.ps1 and appveyor.yml from https://github.com/serilog/serilog would be very welcome if anyone's able to give it a shot :+1:

**Comment by ArturKarbone** [comment]
I just tried to port to .NET Core really quick. Worked out pretty smoothly. The only showstopper is *.resx resource files. Will try to make a PR this week.

**Comment by ArturKarbone** [comment]
just added a [PR ](https://github.com/dotnet-state-machine/stateless/pull/75)for targeting .NET Core

**Comment by ArturKarbone** [comment]
I've just resumed my work on porting to .NET Core and got to the point where I have 2 .NET Core projects for stateless and tests respectivelly with ability to compile for core and other frameworks (got rid of existing "portable" projects). Build.ps1 and appveryor.yml follow Serilog approach with some little adoptation. Working in a separate branch, planning to update the PR later this week.

**Comment by nblumhardt** [comment]
@ArturKarbone great! Thanks for the update :+1:

**Comment by ArturKarbone** [comment]
@nblumhardt just updated pull request. CI pipline works.

**Comment by peekmessage** [comment]
I was just about to start working on getting stateless to build as a .Net Standard library.  From the looks of it, it can target netstandard1.0 which would cover a bunch of platforms including universal and core apps.  Have you considered .Net standard?

**Comment by nblumhardt** [comment]
This is out as 3.x-dev.
