### ISSUE TITLE
"Live" state-machine information with ToDotGraph()

### ISSUE THREAD

**Issue by abrasat** [dotnet-state-machine/stateless#68]
Is it possible to use ToDotGraph() to generate dynamic information about a running state machine ? For instance, would it be possible to visualize and actualize dynamically the actual and the previous state ?

**Comment by nblumhardt** [comment]
Hi @abrasat, no, the dotgraph support is for static configuration only.

Cheers!

**Comment by abrasat** [comment]
Hi @nblumhardt, thanks for information.
Is the PermittedTriggers property actualized dynamically depending on the actual state, or is just a static list containing all triggers used for the state-machine configuration ?

**Comment by nblumhardt** [comment]
Hi - it's dynamic (per-substate) - see https://github.com/dotnet-state-machine/stateless/blob/master/Stateless/StateRepresentation.cs#L196

Cheers,
Nick
