### ISSUE TITLE
best practice for parameterized triggers in conjunction with a domain object?

### ISSUE THREAD

**Issue by roncanepa** [dotnet-state-machine/stateless#72]
Hello,

Maybe I'm just missing something simple/obvious in my wiring, but I'm struggling to figure out how this should be implemented.

**The short version of my question**:  is there a way to call `Fire()` on parameterized triggers without having to store a reference to `SetTriggerParameters` and passing it around?  Or am I missing something fundamental and going about it the wrong way?

**The long version of my question...**

the implementation in the readme does the following in the config: 

```C#
var assignTrigger = stateMachine.SetTriggerParameters<string>(Trigger.Assign);

stateMachine.Configure(State.Assigned)
    .OnEntryFrom(assignTrigger, email => OnAssigned(email));

```

and then immediately calls `.Fire(assignTrigger, "joe@example.com")`.  Note the immediate use of `assignTrigger`.   However, how is this expected to work when the call to `.Fire()` comes elsewhere, like in a domain object?

```C#
private void MyMethod_OnDomainObject(){
    _machine.Fire( ___what goes here?___, "joe@example.com");
}
````

what should be the first argument?  It doesn't seem right that I would have to store assignTrigger as a class property somewhere.  This is what's done in the bug tracker example:

```C#
 public Bug(string title)
        {
        // ...
        _assignTrigger = _machine.SetTriggerParameters<string>(Trigger.Assign);
        // ....
}
```

but seems like it might quickly get out of hand when you have multiple parameterized triggers.

I took a look at the source and I see that there are methods such as this overload of Fire():

```C#
public void Fire<TArg0>(TriggerWithParameters<TArg0> trigger, TArg0 arg0) { // snipped }
```

I've tried multiple variations of calling this from my domain object to no avail, so maybe I'm just goofing up my generics / etc?  Such as calling ` _machine.Fire<string>();` and trying to pass in an argument that matches the `StateMachine<State,Event>.TriggerWithParameters<string> trigger, string arg0` signature.  Can this be done?  Or am I missing something fundamental and going about it the wrong way?

**Comment by nblumhardt** [comment]
Hi Ron, thanks for getting in touch.

The `_assignTrigger` approach is the recommended one; without a shared variable connecting the configuration and the firing of the trigger, there's no way for the trigger parameter types to be strongly validated by the compiler.

If things get a bit crazy with a lot of parameters, you might create a simple value type to hold the parameters, e.g. so that you can write `_triggers.Assign` and not deal with a whole host of fields for the individual values.

HTH!

**Comment by roncanepa** [comment]
Roger that.  Thank you!
