### ISSUE TITLE
ExitFrom

### ISSUE THREAD

**Issue by Cussa** [dotnet-state-machine/stateless#74]
I don't if anyone here needed this, but at my project, I need to fire some actions on exit from one state. 

Because of this state has the possibility to have a reentry, I can't control this only with the OnExit.

Is this a thing that only I have or does anybody had too?

**Comment by Maximusya** [comment]
The argument of type `Transition` (`StateMachine<TState, TTrigger>.Transition`) - passed into a callback specified in OnExit(...) configuration - contains all the info you need to know whether this is a reentry, know the Source and Destination:
https://github.com/dotnet-state-machine/stateless/blob/master/Stateless/Transition.cs

**Comment by Cussa** [comment]
@Maximusya it's a point to start. But I think that like the OnEntryFrom is used, I'll use would use OnExitFrom soo many times that it will be more easy if I have it.

Probably, if I have sometime, I'll try to implement it and do a pull request.

**Comment by HenningNT** [comment]
Sounds like you really need a trigger handler that doesn't cause a state transition.
Maybe an internal transition?
I used a lot of PermitReentry and OnEntryFrom to deal with triggers that didn't need to actually transition to a new state. I didn't like that the OnExit and OnEntry became useless, so I have added a pull request that adds internal transitions.
Please take a look, feedback is always welcome :-)

**Comment by nblumhardt** [comment]
Looks like OnExit(Transition) covers this, but please let me know if I'm mistaken.
