### ISSUE TITLE
OnEntryFrom() and InternalTransition() overloads consistency

### ISSUE THREAD

**Issue by edgarspiv** [dotnet-state-machine/stateless#76]
There is following **OnEntryFrom()** overload :

`public StateConfiguration OnEntryFrom<TArg0>(TriggerWithParameters<TArg0> trigger, Action<TArg0> entryAction, string entryActionDescription = null);`

For InternalTransition() the closest we currently have is :

`public StateConfiguration InternalTransition<TArg0>(TriggerWithParameters<TArg0> trigger, Action<TArg0, Transition> entryAction)`

Ddifference is in **action** argument :
-  `Action<TArg0, Transition> entryAction` 
- `Action<TArg0> entryAction`.

Would be nice to have same overload for InternalTransition() so I we can switch actions from OnEntryFrom() to InternalTransitions() without need to change the **action** signature by adding **Transition** argument.

PS. Perhaps we could have same set of overloads for both methods?

**Comment by HenningNT** [comment]
Good point! That would be very convenient.
This business with generics isn't my strongest side, but I'll see if I can do something about it. Or maybe someone else wants to?

**Comment by HenningNT** [comment]
All we need is this:
`            public StateConfiguration InternalTransistion(TTrigger trigger, Action entryAction)
            {
                _representation.AddTriggerBehaviour(new InternalTriggerBehaviour(trigger, () => true));
                _representation.AddInternalAction(trigger, (t, args) => entryAction());
                return this;
            }`

**Comment by nblumhardt** [comment]
Closed in #82.
