### ISSUE TITLE
Add support for do-Activities

### ISSUE THREAD

**Issue by heltonbiker** [dotnet-state-machine/stateless#77]
Some FSM models consider the existence of a `do-Activity`, that is, a process that keeps running while the machine is in a given state, such as a `Thread` or a `Task`.

A suggested "API" would be, say:

<pre>
     _phone.Configure(State.Ringing)
        <b>.Do(_phone.RingingTask)</b>
        .Permit(Trigger.HungUp, State.OffHook)
        .Permit(Trigger.CallConnected, State.Connected);
</pre>

Is there such feature, currently? Is this a planned feature? If not, would there be the intention to add it?

**Comment by nblumhardt** [comment]
Hey, very interesting idea! No, there's nothing direct: `OnEntry()` could call an async method passinga `CancellationToken` and `OnExit()` could cancel it/`Wait()` for the task, but I imagine it's a bit more subtle than that to get working smoothly.

Is it possible to build as an extension atop the existing API? That would probably make a good litmus test for how aligned it is with the current design of the library.

Also, do you have a scenario you're keen to apply this in presently, or just investigating the idea (which is neat, regardless)?

Cheers,
Nick

**Comment by heltonbiker** [comment]
Hi, thanks for your feedback!

I actually have a scenario. My very interest in that feature comes from my successfull attempt to replace, in the application I am currently developing, an implicit state machine implementation with an explicit `StateMachine` from `Stateless`.

The class containing the state machine is called `DeviceMonitor`, and it is supposed to be in one of two states: `SearchingDevices` or `MonitoringDeviceConnection`. The events are `DeviceFound` and `DeviceConnectionLost`. At predetermined intervals, it should run the `Poll` method, that untill now have been implemented either polymorphically using `State` pattern, or with a switch/case statement.

Now it is implemented using the `OnEntry` and `PermitReentrant` methods, and the timer fires the `Poll` method, which actually executes `_stateMachine.Fire(Event.ShouldPoll)`. Each state has the appropriate `Poll` implementation (either `SearchDevice` or `CheckConnection` methods in the same class).

Your idea of calling a Task `OnEntry` is elegant, but  I wonder if the legibility wouldn't be compromised.

I am going to further refine this tomorrow, and I will try to implement the `Do` method as an extension, like you suggested. As soon as I have something to tell, I'll come back and post some feedback.

Thanks for now!

**Comment by HenningNT** [comment]
This looks more or less like the reason I added the InternalTransitions :-) I was finding myself writing a lot of Permitreentry and OnEntryFrom for the repeating events.
I have a state machine polling the status of a connected device, where a timer post a Poll event to my event queue. The state machine uses internal transitions to process the poll events.

**Comment by heltonbiker** [comment]
Thanks @HenningNT for your extra feedback.

I have to say the InternalTransition left my code in a much more readable state.

So we have at least three ways to implement the "do/Activity" feature:

- Use a method that starts a task `OnEntry`, and cancels that task `OnExit` for a given state;
- Use the combination of `PermitReentry` and `OnEntry[From]` methods;
- Use `InternalTransitions`;

In the first option, the loop would be defined in the Task itself, while in the later two, the triggering interval would be defined by an external trigger source (a `Timer`, for example, or some `Task` or `Thread`).

As such, I have one last question: Do you think there would be some _benefit_ in explicitily introduce the `Do[Activity` method to `StateMachine`?

Some possible signatures:

    _fsm.Do(Action action, TimeSpan interval) { }
    _fsm.Do(Task task) { }

**Comment by HenningNT** [comment]
I've looked around for information about the "Do/Activity" and I am not sure.

One one hand I can see a particular use for it. Let's say you have a coffee machine, one of the states could be "GrindingBeans" and the Do activity would be "Grind Beans". When the grinding activity is done the state machine would automatically go to the next state. Other events would of course be handled as well, such as a "Cancel" event. But it do raises some concurrency issues that would need handling. What if the "Do" finishes while another event is being handled? At the moment I don't think Stateless would support this, as we would need queues to store event. (I wrap the statemachine in an active object that handles queueing of events)

For recurring events I don't see the need for the "Do / activity", as the internal transitions do more or less the same. In both cases the timer would have to be handled when leaving the state.

So... Yes, there might be a benefit, but it would require some effort to evaluate and spec this properly. I think internal transitions are good enough for recurring events.

**Comment by dgehri** [comment]
I just want to give you some information about the semantics of the entry/do/exit actions in UML state machines. Maybe it helps you to analyze the need for implementing the "do" action:

- the "**entry**" action is called upon entry of a state, and it is execute **atomically** (that is, no trigger event will interrupt it)
- the "**exit**" action is called before leaving a state, and like the "entry" action it is executed atomically.
- the "**do**" action is called after the "entry" action. It is **not** repeated (unless it contains a loop, of course). The difference with the "entry" action is, that its execution will be interrupted by any event trigger received during its execution (if there is valid transition for that trigger, and any associated guard is true).

A few remarks regarding triggers: after a **do** action has run to completion, the state machine sends to itself a "state completion" trigger. This is the trigger for any **default transitions** (the ones w/o any named trigger event).

In UML, when trigger events are received, the state machine checks if there are any outgoing transitions for that trigger event. If there are whose guard (if any) evaluates to true, then that transition is taken. If any, however, there is no transition for that trigger event, or none of the guards evaluates to true, then the trigger event **is lost**. This includes the **state completion** trigger for the default transition! So even if default transition's guard evaluates to true at a later time, that transition will not be taken.

Cheers,
Dan

**Comment by HenningNT** [comment]
Thanks for the information!
I guess it would be up to @nblumhardt to decide if this is something to include.
I think it could be worthwhile to include it.

**Comment by heltonbiker** [comment]
@dgehri , what would be a good source for that sort of sophisticated information about UML?

I've recently opened another issue about adding some material about FSM concepts and terminology, you seem to be very fluent on the topic!

Is there some site or book to read about all this?

**Comment by dgehri** [comment]
@heltonbiker , here are a few sources:

- [Formal Specification of Software - UML State Machines](http://formal.iti.kit.edu/~beckert/teaching/Spezifikation-SS04/10StateCharts.pdf)
- [Event Processing in Code Generation and Execution
Framework of UML State Machines ](http://staff.ii.pw.edu.pl/~adr/AdrPilt_SET_07.pdf)
- [A Formal Semantics for Complete UML State Machines with Communications](http://people.sutd.edu.sg/~sunjun/Publications/iFM13b.pdf)

They should provide you with all the details. I'll be happy to assist you in the implementation.

**Comment by nblumhardt** [comment]
I think the single-threadedness of Stateless will make this awkward to do well; I'd prefer layering this kind of thing on top using internal transitions if we have that option. Unless I'm missing something and it's a simple change to make?

(Forgive the quick post, doing a review of the issue tracker, lots to get through :-))

**Comment by dabbinavo** [comment]
Came accross this old topic as I also need a Do/DoAsync functionality.
For anyone searching for an extension method. Here is my starter template. One known issue with this apporach is that the statemachine ignores the `Fire` method inside the `action` when the `action` takes longer than `interval`.

```c#
using System.Threading;
using System.Threading.Tasks;
using Stateless;

namespace Your.Extension.Namespace;

static public class StatelessExtensions
{
    public static void Do<TState, TTrigger>(this StateMachine<TState, TTrigger>.StateConfiguration @this, Action action, int interval, TTrigger loopTrigger)
    {
        var timer = new Timer(_ => @this.Machine.Fire(loopTrigger), null, Timeout.Infinite, Timeout.Infinite);
        @this
            .OnEntry(() => timer.Change(0, interval))
            .OnExit(() => timer.Dispose())
            .InternalTransition(loopTrigger, action);
    }

    public static void DoAsync<TState, TTrigger>(this StateMachine<TState, TTrigger>.StateConfiguration @this, Func<Task> action, int interval, TTrigger loopTrigger)
    {
        Timer timer = new Timer(_ => @this.Machine.FireAsync(loopTrigger), null, Timeout.Infinite, Timeout.Infinite);
        @this
            .OnEntry(() => timer.Change(0, interval))
            .OnExit(() => timer.Dispose())
            .InternalTransitionAsync(loopTrigger, action);
    }
}

```

Example usage:
```c#
enum Trigger {
    // ... ,
   Loop,
}

machine.Configure(State.TestState)
    /* ... */
    .Do(() => Console.WriteLine("looping in state"), 2000, Trigger.Loop);
```

**Comment by crozone** [comment]
> Came accross this old topic as I also need a Do/DoAsync functionality. For anyone searching for an extension method. Here is my starter template. 

Careful, this method doesn't appear to fire the state machine transition in a threadsafe manner. If something other than the Timer task calls Fire at the same time, you may get ugly race conditions, or even weirdness with memory coherency across CPU cores.

Ideally for a Do action to work correctly, there needs to be some sort of global worker queue which serializes all state machine triggers such that a single worker task can then do the processing of each trigger, one after the other.

Using this sort of system, the Do timer could instead push the trigger to the queue instead, ensuring that two Fire methods are never called simultaneously.

I have accomplished this using a `Channel<Func<Task>>` and a worker task:

```
Channel<Func<Task>> eventQueue = Channel.CreateUnbounded<Func<Task>>();

async Task EventQueueTask(CancellationToken cancellationToken)
{
    await foreach (Func<Task> thisEvent in eventQueue!.Reader.ReadAllAsync(cancellationToken))
    {
        try
        {
            await thisEvent();
        }
        catch (Exception ex)
        {
            // Log the error
        }
    }
}
```

Then any code that needs to fire a trigger from a different thread (i.e. outside of the state machine action lambdas) can enqueue work like this:

```
eventQueue.Writer.TryWrite(
    async () =>
    {
        await stateMachine.FireAsync(Trigger.SomeTrigger);
    }
);
```
