### ISSUE TITLE
The project doesn't have resources (or a link to resources) about FSM terminology and concepts.

### ISSUE THREAD

**Issue by heltonbiker** [dotnet-state-machine/stateless#78]
Newcomers without much theoretical base about FSM (me included), might benefit from some basic terminology, like a glossary, a wiki with documentation about that, or at least some _recommended reading_ (a link, or a book name).

If a new user already has this knowledge, it is very natural for her to understand the API and use it properly, even without "reading the docs". The affordances are already right there in the class names. On the other hand, it gets a bit difficult to explore the full power of the library without this theoretical introduction, IMO.

**Comment by nblumhardt** [comment]
Thanks for the ticket! Some suggested links would be welcome. Closing this for now as I don't have anything at hand. Cheers!
