### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by makcakaya** [dotnet-state-machine/stateless#79]
Is StateMachine thread-safe? If it is not, is there a reason for not being so?

I could not find a track of synchronization at accessing or mutating the state. 

Thanks for the efforts, cool project!

**Comment by nblumhardt** [comment]
No, the state machine is not designed to be thread-safe, it's just a basic low-level building block. If synchronised access is required, application code needs to mediate this using `lock` and so-on.

Cheers,
Nick

**Comment by HenningNT** [comment]
... or use the actor model, where messages are exchanged between objects and state is only modified internally. According to Wikipedia this avoids the need for locks.
I've been using the active object (http://www.drdobbs.com/parallel/prefer-using-active-objects-instead-of-n/225700095) model without locking with Stateless.

**Comment by makcakaya** [comment]
I wrapped the StateMachine class and synced the access to the state, it works great. Thanks!

**Comment by bhaidar** [comment]
@HenningNT 
Can you share with us a sample of using an Active Object in C#? I am trying to use Stateless in Web App and I am getting concerned when it comes to thread-safety. 

Thanks

**Comment by HenningNT** [comment]
I'll check if I can share the implementation, I made it at work, so it belongs to my employer ;-)
