### ISSUE TITLE
SubstateOf and dotGraph

### ISSUE THREAD

**Issue by sle118** [dotnet-state-machine/stateless#80]
First, I want to say that this little state machine project has simplified quite significantly an application I am building for my own fun. I can see the benefits of this approach for future enterprise level projects, although the state machine will likely be an off the shelf solution that exist currently in our landscape.

I'm wondering if it would be possible to have the dot graph represent content inherited from SubstateOf , as it would help picturing more complex state machines. 

I got around the limitation by duplicating all of the "permit" from the parent States, but it defeats the purpose of inheritance and makes the code more complicated to maintain.

Thank you!

**Comment by HenningNT** [comment]
dotGraph doesn't really like substates. It is possible to use HTML inside the states, but I think it would require quite an effort to get right.
It might be easier to export to a different format, one that QM can parse.
http://www.state-machine.com/qm/

One could also make a import function to Stateless to read models from QM at run time, I guess.

**Comment by sle118** [comment]
Or perhaps sub states could be represented as clusters using sdp
http://www.graphviz.org/content/point-edge-cluster

An example here
https://stamm-wilbrandt.de/Viz.js/form10/?1425770108930#

**Comment by tlk** [comment]
@sle118 It would be interesting to see if this would work!

I take it that you meant "fdp" as in http://graphviz.org/content/fdpclust, right?

By the way, this sample link seems to work better for me:
http://stamm-wilbrandt.de/Viz.js/form10/?1425770108930#graph%20G%20%7B%0A%20%20layout%3Dfdp%0A%0A%20%20e%0A%20%20subgraph%20clusterA%20%7B%0A%20%20%20%20a%20--%20b%3B%0A%20%20%20%20subgraph%20clusterC%20%7B%0A%20%20%20%20%20%20C%20--%20D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20subgraph%20clusterB%20%7B%0A%20%20%20%20d%20--%20f%0A%20%20%7D%0A%20%20d%20--%20D%0A%20%20e%20--%20clusterB%0A%20%20clusterC%20--%20clusterB%0A%7D%0A

**Comment by sle118** [comment]
Ok. Forget about fdp. After a little more digging, I found what I believe is a better alternative. 

First add the following attribute
`compound=true;`
Next use sub graph clusters to represent nodes that have sub states (the stateless class makes this available) 
`subgraph cluster1 {
e -> g;
e -> f;
}
`
Attributes of a parent would be represented as links between sub graph using ltail and lhead to denote where lines header and tail are to be connected.

For example
`g -> c [ltail=cluster1,
lhead=cluster0];`

As for overwrites at the lower levels, where a state implements its own overwrite of a trigger, a line would be drawn between both the source state and target state, as it is already done today. For example 
`c -> e ;`

Here is a link to visualize an example:
[http://tinyurl.com/statemachine-inheritance](url)

**Comment by tlk** [comment]
@sle118 It looks promising! I will be happy to review a PR.

**Comment by sle118** [comment]
Just a quick update on this. I did quite a bit of refactoring on the dotgraph representation, implementing some formatting class with attributes stored as dictionary and all.

So far, a recursive is used to build clusters, which works pretty well for organising nodes together. Entries and exits don't have to be created in clusters, so they get built together outside of the recursive and this works well too. Entries are represented as invhouse lines at the top of the graph and exits are represented as houses lined up at the bottom. I will change this for a vertical alignment instead, as a complex state machine with several entries/exits will make a large graph.

What is left to implement is a proper edge handling (the arrows). This has proven more difficult than expected, and I'm looking for the best way to have arrows/edges coming out from/to clusters borders.

@tlk, my coding style is very much imperfect compared to yours, but I'm trying to clean it up using a tool called resharper. That tool taught me some neat tricks like string interpolation as well as better representation of some of my linq logic.

Stay tuned

**Comment by tlk** [comment]
@sle118 I think all credit goes to Nicholas (the author) and the other contributors :-)

Thanks for the update! Feel free to make a PR if you want some feedback while you are working on it.

Also, PR #82 is close to making it into the code - I suspect that it will affect your work...

**Comment by sle118** [comment]
If anyone is interested, I have saved my work here: https://github.com/sle118/stateless/tree/master

I am running out of time for now, so I won't be able to work much on it for a while.

**Comment by sle118** [comment]
I have updated my code to represent states with HTML instead. The idea is to have entries, exits (in yekllkow) and the state node in a single box to simplify the representation. 

![gvedit_2016-10-11_15-17-48](https://cloud.githubusercontent.com/assets/5656564/19284923/f8946e44-8fc5-11e6-80d2-f2fae2c9f707.png)

**Comment by HenningNT** [comment]
That's amazing!

**Comment by sle118** [comment]
@HenningNT  I am glad you like it! 

Note that the graph has confusing lines between washing and PowerOff. One arrow is pointed from the surrounding box (super state) towards "power off" with a trigger called "Power" and a condition "IsPowerOff", and it overlaps with PowerOff->washing (trigger start). I cannot think of a solution right now, as this is an artifact of the rendering engine which I used. 

I'll see if I can play with the trigger/guard conditions better at some point, but I think this works well enough to be useful to others.

**Comment by sle118** [comment]
So what would be the next step for this? Wouldn't want to have the code lagging to much behind

**Comment by nblumhardt** [comment]
@sle118 opening a PR from your codebase would be the way to go 👍

**Comment by nblumhardt** [comment]
@sle118 just wanted to send a heads-up, some changes on `dev` could make merging a little tricky; if you'd like a hand with it please just sing out. Cheers!

**Comment by psibernetic** [comment]
@sle118 Any updates on this, was going to look at this some point in the future myself.

**Comment by sle118** [comment]
I messed up my repo trying to merge (I come from TFS and still learning git) so I backed up everything and cloned again. Setting up my build environment right now I should be able to merge my changes very soon. If I am having problems again, I might ask for help!

**Comment by sle118** [comment]
I'm happy to report that I have finally created a pull request: https://github.com/dotnet-state-machine/stateless/pull/100

I pulled the latest dev, merged my code and updated the test conditions. Hoping this will be helpful to everyone. 

I'm using the following online viz tool, as the HTML representation requires some modules that aren't available on every sites
http://sandbox.kidstrythisathome.com/erdos/

I also use gvedit to display and tweak locally.

**Comment by betty-crokker** [comment]
@sle118 now that we have the reflection API far enough along, I think it's time to make your changes happen too!  Do you want to have the honor of making the change?  If not I want the DOT graph that your code creates so I'm happy to take on the task if you want ...

**Comment by betty-crokker** [comment]
@nblumhardt @HenningNT We can close this issue, the requested code is in.

**Comment by sle118** [comment]
@betty-crokker I haven't had time to touch this for a long time. I see that the issue is closed so I'll have a look at the code to see if anything was done
