### ISSUE TITLE
Offer a way to configure same transition configuration to all states

### ISSUE THREAD

**Issue by heltonbiker** [dotnet-state-machine/stateless#81]
Currently I have the following code. I need to allow the same internal transition whatever the current state is. I don't know if there is a way to do that without the repeated code, but it should, because for larger state machines, it would be very cumbersome, I think.

			_state_machine.Configure(EstadoColeta.Parada)
						  .OnEntry(Stop)
						  .Permit(ComandoColeta.Play, EstadoColeta.Coletando)
						  .InternalTransition(ComandoColeta.Reset, (t) => Reset());

			_state_machine.Configure(EstadoColeta.Coletando)
						  .OnEntry(Play)
						  .Permit(ComandoColeta.Pause, EstadoColeta.Pausada)
						  .Permit(ComandoColeta.Stop, EstadoColeta.Parada)
						  .InternalTransition(ComandoColeta.Reset, (t) => Reset());

			_state_machine.Configure(EstadoColeta.Pausada)
						  .OnEntry(Pause)
						  .Permit(ComandoColeta.Play, EstadoColeta.Coletando)
						  .Permit(ComandoColeta.Stop, EstadoColeta.Parada)
						  .InternalTransition(ComandoColeta.Reset, (t) => Reset());

I created an alternative solution by iterating over every possible value of my Enum, but that felt way hackish to my taste:

			foreach (var state in Enum.GetValues(typeof(EstadoColeta)))
			{
				_state_machine.Configure((EstadoColeta)state)
					          .InternalTransition(ComandoColeta.Reset, (t) => Reset());
			}

**Comment by HenningNT** [comment]
Create a superstate that handles the reset, and add a substateof(sp?) to the rest of the states.

**Comment by heltonbiker** [comment]
Got it.

Nice to have unit tests (I've just started to use them). Made your suggested change, everything still working fine!

Thanks!
