### ISSUE TITLE
About DSL question

### ISSUE THREAD

**Issue by victorsoliveira** [dotnet-state-machine/stateless#83]
Hi,

I saw that In the base project (http://simplestatemachine.codeplex.com/) we can configure a worfkow throught a DSL.

Do you intend to implement that ?
A configuration throught a DSL ?

Thanks!

**Comment by nblumhardt** [comment]
Hi Victor - thanks for the mail.

Stateless is a port of Simple State Machine's DSL from Boo to C#. I think the crux of the difference is that Boo is easier to load at runtime than C# is, but to achieve the same thing you could try loading Stateless state machines from C# files with Roslyn.

If runtime loading is the core goal however, I'd say Simple State Machine is probably a better fit for you.

Hope this helps!
