### ISSUE TITLE
Question, can StateMachine Fire method be called by different threads simultaneously ?

### ISSUE THREAD

**Issue by mrpepito** [dotnet-state-machine/stateless#85]

**Comment by HenningNT** [comment]
Yes. 
I suggest posting events to a queue, and empty the queue from a timer and fire triggers in the timer rick callback.

Check out this for inspiration: 
http://www.drdobbs.com/parallel/prefer-using-active-objects-instead-of-n/225700095

**Comment by mrpepito** [comment]
Thanks !
