### ISSUE TITLE
Document approval sample

### ISSUE THREAD

**Issue by papyr** [dotnet-state-machine/stateless#86]
Hi, can you please share a simple document approval sample, and if we could add a simple list/dictionary of keywords and a line to describe the usage it would greatly help.

**Comment by HenningNT** [comment]
Do you mean you would like to see another example added to the project?

Or that you need one for something you're working on?
The Bug example is easy to modify into a document approval workflow, it needs just adding an interface for setting tags and you're good to go?

**Comment by HenningNT** [comment]
Something like this?

`namespace DocumentWorkflow
{
    public enum DocumentState { Draft, Review, Approved, Released};
    public struct VersionNumber
    {
        public char Majorversion;
        public byte MinorVersion;
    }
    public class Document
    {
        enum DocumentTrigger { SendReview, Rejected, Approved, Released, StartNewRevision};
        private StateMachine<DocumentState, DocumentTrigger> _documentState = new StateMachine<DocumentState, DocumentTrigger>(DocumentState.Draft);
        private VersionNumber _versionNumber;

        private List<string> _documentKeywords = new List<string>();

        public Document()
        {
            _documentState.Configure(DocumentState.Draft)
                .OnEntry(DraftOnEntry)
                .Permit(DocumentTrigger.SendReview, DocumentState.Review);

            _documentState.Configure(DocumentState.Review)
                .Permit(DocumentTrigger.Rejected, DocumentState.Draft)
                .Permit(DocumentTrigger.Approved, DocumentState.Approved);

            _documentState.Configure(DocumentState.Approved)
                .Permit(DocumentTrigger.Released, DocumentState.Released);

            _documentState.Configure(DocumentState.Released)
                .Permit(DocumentTrigger.StartNewRevision, DocumentState.Draft)
                .OnExit(ReleasedOnExit);

            _versionNumber.Majorversion = 'A';
            _versionNumber.MinorVersion = 0;
        }

        private void ReleasedOnExit()
        {
            _versionNumber.Majorversion++;
        }
        private void DraftOnEntry()
        {
            _versionNumber.MinorVersion++;
        }
        public void SendReview()
        {
            _documentState.Fire(DocumentTrigger.SendReview);
        }
        public void ApproveReview()
        {
            _documentState.Fire(DocumentTrigger.Approved);
        }
        public void RejectReview()
        {
            _documentState.Fire(DocumentTrigger.Rejected);
        }
        public void Release()
        {
            _documentState.Fire(DocumentTrigger.Released);
        }
        public void NewRevision()
        {
            _documentState.Fire(DocumentTrigger.StartNewRevision);
        }
        public void AddKeyword (string keyword)
        {
            _documentKeywords.Add(keyword);
        }

        public bool HasKeyword(string keyword)
        {
            return _documentKeywords.Contains(keyword);
        }
        public void RemoveKeyword(string keyword)
        {
            if (HasKeyword(keyword))
            {
                _documentKeywords.Remove(keyword);
            }
        }
    }
}
`

**Comment by SirRufo** [comment]
Just use indentation for the code like (section inside pre tags)
<pre>
    void foo()
    {
        bar();
    }
</pre>
to get

    void foo()
    {
        bar();
    }

Do not use
<pre>
`void foo()
{
    bar();

    baz();

}
ˋ 
</pre>
that will look ugly :o)
`void foo()
{
    bar();

    baz();

}
ˋ

**Comment by Maximusya** [comment]
```csharp
namespace DocumentWorkflow
{
	public enum DocumentState { Draft, Review, Approved, Released};
	
	public struct VersionNumber
	{
		public char Majorversion;
		public byte MinorVersion;
	}
	
	public class Document
	{
		enum DocumentTrigger { SendReview, Rejected, Approved, Released, StartNewRevision};
		
		private StateMachine _documentState = new StateMachine(DocumentState.Draft);
		private VersionNumber _versionNumber;

		private List<string> _documentKeywords = new List<string>();

		public Document()
		{
			_documentState.Configure(DocumentState.Draft)
				.OnEntry(DraftOnEntry)
				.Permit(DocumentTrigger.SendReview, DocumentState.Review);

			_documentState.Configure(DocumentState.Review)
				.Permit(DocumentTrigger.Rejected, DocumentState.Draft)
				.Permit(DocumentTrigger.Approved, DocumentState.Approved);

			_documentState.Configure(DocumentState.Approved)
				.Permit(DocumentTrigger.Released, DocumentState.Released);

			_documentState.Configure(DocumentState.Released)
				.Permit(DocumentTrigger.StartNewRevision, DocumentState.Draft)
				.OnExit(ReleasedOnExit);

			_versionNumber.Majorversion = 'A';
			_versionNumber.MinorVersion = 0;
		}

		private void ReleasedOnExit()
		{
			_versionNumber.Majorversion++;
			_versionNumber.MinorVersion = 0;
		}
		private void DraftOnEntry()
		{
			_versionNumber.MinorVersion++;
		}
		public void SendReview()
		{
			_documentState.Fire(DocumentTrigger.SendReview);
		}
		public void ApproveReview()
		{
			_documentState.Fire(DocumentTrigger.Approved);
		}
		public void RejectReview()
		{
			_documentState.Fire(DocumentTrigger.Rejected);
		}
		public void Release()
		{
			_documentState.Fire(DocumentTrigger.Released);
		}
		public void NewRevision()
		{
			_documentState.Fire(DocumentTrigger.StartNewRevision);
		}
		public void AddKeyword (string keyword)
		{
			_documentKeywords.Add(keyword);
		}

		public bool HasKeyword(string keyword)
		{
			return _documentKeywords.Contains(keyword);
		}
		public void RemoveKeyword(string keyword)
		{
			if (HasKeyword(keyword))
			{
				_documentKeywords.Remove(keyword);
			}
		}
	}
}
```

**Comment by Maximusya** [comment]
Single quotes are for inline code strings. Use triple quotes with the language specified:
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by HenningNT** [comment]
I see, thanks!
