### ISSUE TITLE
Anonymous methods/lambda descriptions

### ISSUE THREAD

**Issue by sle118** [dotnet-state-machine/stateless#87]
I recently worked on an updated dotGraph class which leverages the existing one and add sub states representations as well as a new simplified layout (see issue #80 ). 

Perhaps this is a v2 request, but it would be interesting to have a way to pass actions and guard descriptions when creating new states. Those would allow using anonymous methods for simple guards and actions and retain readability.

**Comment by nblumhardt** [comment]
This sounds like a good improvement. I had a feeling some APIs were already present for this, but it might be the case that they're non-public. Needs some investigation.

**Comment by psibernetic** [comment]
Just verified this is in the public API. .OnEntry(Action, description).

**Comment by nblumhardt** [comment]
Great, thanks @psibernetic. Will close then - but @sle118 please let us know if we've missed something! :-)
