### ISSUE TITLE
Is there a clear way to transition to a different state if PermitIf's conditional function fails?

### ISSUE THREAD

**Issue by marcelbound** [dotnet-state-machine/stateless#88]
I am surprised I am not seeing this in the open issues or pull requests.   There is something that appears remotely similar in the unit tests addressing PermitDynamic but it is doing both declaring the machine's states/transitions and the deciding function's code in the same context.   

Is there an analogous way in Stateless to do something that would be similar to the following?

**machine.Configure(openSale).PermitIf(closeSaleTrigger, saleClosedSuccessfully, conditionFunc, saleClosedWithWarnings);**

Where there fourth parameter is a destination state if the conditionFunc evaluates to false.   

The workaround for now would be for the client to manage if the machine's state hasnt transitioned after a Fire() call and then call Fire() again with some hacky trigger to force the machine into the saleClosedWithWarnings state.

This should not be.

**Comment by nblumhardt** [comment]
Hi Marcel, I think that's the use case for PermitDynamic(); is what you mean something like:

```csharp
machine.Configure(openSale)
    .PermitDynamic(closeSaleTrigger, t => conditionFunc() ? saleClosedSuccessfully : saleClosedWithWarnings);
```

**Comment by marcelbound** [comment]
Thank you for your quick reply.  I was able to put together a workflow using PermitDynamic<T> since I have triggers with data deciding transitions.

One limitation,  am I right in saying that PermitDynamic conceptually does not work with mapping out the state machine before it runs, and thus the state machine graph comes out incomplete?    

Is there a workaround for this, or a way to run code with parameters between state transitions so that PermitDynamic is not used, and the graph comes out okay?

**Comment by tlk** [comment]
Hi Marcel,

How about using named delegates like https://github.com/dotnet-state-machine/stateless/blob/6f1b23e5f92b6234aa35421c4c9c99e0941cace4/Stateless.Tests/DotGraphFixture.cs#L106

So you would have something like this:

```
sm.Configure(State.A)
    .PermitIf(Trigger.X, State.B, IsTrue, "foo description")
    .PermitIf(Trigger.X, State.C, IsFalse, "bar description");
```

Though not the most elegant syntax :-)

**Comment by tlk** [comment]
The challenge with translating PermitDynamic to a graph is that you would have to evaluate the delegates in order to discover all possible destination states, so PermitDynamic does not work well with the dot graphs unfortunately.

**Comment by marcelbound** [comment]
I appreciate everyone's insightful observations.
