### ISSUE TITLE
make stateless thread-safe

### ISSUE THREAD

**Issue by SurajGupta** [dotnet-state-machine/stateless#94]
It would be great if stateless were thread-safe.

**Comment by nblumhardt** [comment]
Thanks for the note!

While handy in some situations, the need to control lock acquisition order in user code means Stateless itself can't easily be made reliably concurrent (e.g. do entry/exit actions fire under locks? If not, how can they be synchronized, and if so, will user code deadlock if the action itself requests a lock held by another thread waiting on Fire()?). For that reason we suggest adding a `lock` statement around the state machine object if concurrency is required.
