### ISSUE TITLE
What version of the code do I use for .Net (not .Net Core)?

### ISSUE THREAD

**Issue by markwhitfeld** [dotnet-state-machine/stateless#99]
Please could you tag or branch the code at the point before the move to .NET Core.
I would really love to use your project but I am not on .NET Core.

With regard to nuget packages I see that there is an "unofficial" package for .NET 4.0:
http://www.nuget.org/packages/stateless-4.0/ 
It would be really great if you published an official nuget package.

**Comment by nblumhardt** [comment]
Hi Mark, the current package should support all platforms, not only .NET Core (3.0 has actually expanded support to include .NET 4.0 as well). Which platform are you targeting?

**Comment by markwhitfeld** [comment]
I am targeting .NET v4.6.2. Will it work with this? 
From the readme on the main page it seemed that it was just for .NET Core.
Maybe it is worth adding a note there.

**Comment by markwhitfeld** [comment]
Oh wow, I have just seen a Scott Hanselman article from today detailing this very fact!!!
See here: [http://www.hanselman.com/blog/Stateless30AStateMachineLibraryForNETCore.aspx](http://www.hanselman.com/blog/Stateless30AStateMachineLibraryForNETCore.aspx)

**Comment by nblumhardt** [comment]
README updated, thanks for the feedback Mark 👍
